code/web/Drivers/CarlX.php, code/web/sys/SIP2.php
N.B. the code that replaces CarlX PatronAPI holds queue position calculation with SIP2 patron information call/response for 'unavail' could be sidestepped with CarlX SIP ini flag USEHOLDOCCUR first available in CarlX 9.6.5.1. See https://ww2.tlcdelivers.com/helpdesk/Default.asp?TicketID=500458
=> 20.09.00 carl xsip2 holds

code/web/services/API/SearchAPI.php
This change should fix the memory size the API reports.  StringUtils::formatBytes expects bytes, but /proc/meminfo provides kilobytes.
=> Fix reported memory size

code/web/Drivers/CarlX.php
https://trello.com/c/S1w3Cy0T
FWIW: Nashville will upgrade to CarlX 9.6.8 on March 16, 2021 -- at which point this change will need to change again because of changes to the CarlX table column names.
=> Fixes school holds report

code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/base.js, code/web/release_notes/21.04.00.MD
Menu links with dropdowns will automatically close after mouse leaves element or when another touch event is triggered
=> Automatically close menu links with dropdowns

code/web/interface/themes/responsive/Record/hold-popup.tpl, code/web/interface/themes/responsive/Record/hold-select-volume-popup.tpl, code/web/services/Record/AJAX.php, code/web/sys/DBMaintenance/version_updates/22.01.00.php, code/web/sys/IP/IPAddress.php
On a per-IP basis, add the option to hide the autologout checkbox that
appears on the Place Holds pop-up.  Defaults to current behavior.
resubmitted with whitespace corrections and more optimal interface variable assignment location
=> Add option to hide Log Me Out checkbox on holds popup

code/web/interface/themes/responsive/MyAccount/worldPayPayments.tpl
for if library has set to pay "all fines", otherwise when patron selects individual fines it will overwrite it to the appropriate amount
=> preload total fines amount for worldpay so it's not 0

code/web/RecordDrivers/CourseReservesRecordDriver.php, code/web/RecordDrivers/EbscoRecordDriver.php, code/web/RecordDrivers/EbscohostRecordDriver.php, code/web/RecordDrivers/GroupedWorkDriver.php, code/web/RecordDrivers/IndexRecordDriver.php, code/web/RecordDrivers/ListsRecordDriver.php, code/web/RecordDrivers/PersonRecord.php, code/web/release_notes/22.07.00.MD, code/web/sys/DBMaintenance/version_updates/22.07.00.php, code/web/sys/Theming/Theme.php
Adds "Browse Category Image Size" category to themes under "Browse Categories" where the image size can be set to medium or large. Related drivers that fetch medium image size for covers were updated. OpenArchivesRecordDriver.php was not updated since only small book covers are fetched. Also updated Release notes to include updates for this and for ticket 99624 (titles in tabbed spotlights)
=> Browse Category Image Size

install/createSite.php
This commit fixes the problem detailed in issue #601. The fix obtains
the system's temp directory via sys_get_temp_dir() (removing any
trailing /), rather than using a hardcoded /tmp/ path
=> Issue #601: Dev installation on Windows

code/web/interface/themes/responsive/Springshare/event.tpl, code/web/release_notes/22.07.00.MD
Staff view for LibCal events will be hidden for all users except those who have permissions to administer LibCal settings. Updated 22.07.00.MD release notes
=> Hide LibCal Staff View

code/web/interface/themes/responsive/Record/hold-popup.tpl, code/web/interface/themes/responsive/Record/hold-select-volume-popup.tpl, code/web/interface/themes/responsive/Record/hold-success-popup.tpl, code/web/release_notes/22.07.00.MD, code/web/services/MyAccount/AJAX.php, code/web/services/Record/AJAX.php, code/web/sys/DBMaintenance/version_updates/22.07.00.php, code/web/sys/LibraryLocation/Library.php
Removed "Show Detailed Hold Notice Information" setting as well as "treatPrintNoticesAsPhoneNotices".  Updated release notes
=> Remove the setting "Show Detailed Hold Notice Information"

code/web/interface/themes/responsive/Search/home.tpl, code/web/interface/themes/responsive/theme.css.tpl
Border round browse thumbnails is hidden if ratings are turned off and grid display is being used. Items are also centered in this case
=> Hide border for no ratings grid display in browse

code/web/sys/DataObjectUtil.php
This commit makes validateObject recursive, enabling it to traverse
down a tree of $structure fields and sections, gathering validation
results as it goes.
=> Fix traversal of $structure

.gitignore, code/web/Drivers/marmot_inc/SearchSources.php, code/web/release_notes/22.08.00.MD, code/web/sys/ExploreMore.php, code/web/sys/LibraryLocation/CombinedResultSection.php
If both modules are enabled and settings/search settings exist for both EDS will be preferred and will be the only option that shows in the search source, explore more, and combined results. If EDS settings are set to "none" EBSCOhost will be the only option in these areas. This should make it easy for libraries to use either/or within a consortium that uses both
=> EBSCOhost vs EDS 

code/web/interface/themes/responsive/CollectionSpotlight/collectionSpotlightTabs.tpl, code/web/interface/themes/responsive/CollectionSpotlight/horizontalCarousel.tpl, code/web/interface/themes/responsive/CollectionSpotlight/titleScroller.tpl, code/web/release_notes/22.09.00.MD, code/web/sys/LocalEnrichment/CollectionSpotlight.php
Fixed the view more link for tabbed spotlights not redirecting to the correct list. The view more link is now placed under the book covers (bottom right) for the horizontal/horizontal carousel. Updated release notes
=> Collection Spotlight: View More Link

code/reindexer/src/com/turning_leaf_technologies/reindexer/GroupedWorkSolr2.java, code/web/release_notes/22.09.00.MD
Adds checks to GroupedWorkSolr2.java to hide Unknown and Not Coded lit forms if that is chosen in Indexing Profiles. Also updated 22.09.00 release notes
=> Hide Unknown/Not Coded

code/web/interface/themes/responsive/CollectionSpotlight/collectionSpotlightTabs.tpl, code/web/interface/themes/responsive/CollectionSpotlight/horizontalCarousel.tpl
In tabbed Collection Spotlights, includes the CS name in the View More link text.
E.g., if a tabbed CS included CSes named Unicorns, Glitter, Rainbows, and Glitter is selected, the View More link would read "View More Glitter", and when clicked would take the patron to the search described in the Glitter CS admin page.
=> Improves View More links in tabbed Collection Spotlights

code/reindexer/src/com/turning_leaf_technologies/grouping/BaseMarcRecordGrouper.java, code/reindexer/src/com/turning_leaf_technologies/grouping/RecordGroupingProcessor.java, code/web/sys/DBMaintenance/version_updates/22.09.00.php
Reindex grouped works with IDs that contain spaces. Added to the checks to look for spaces in 008 language field
=> Reindex Grouped Works with IDs that contain spaces

install/installer_debian.sh
* On Debian 10 and Debian 11, php8.1 is selected by the sury list erroneously.
* This proposition will resolve this problem, by specifying to apt which version to use.
=> Fix for installer overwriting php7.3 with php8.1

code/web/Drivers/Evergreen.php
Use the "override" variant when placing a hold. This allows the Evergreen admin to configure (via user permissions) overriding events that would otherwise otherwise prevent a hold from being placed.
For example, if age protection should not block self-service holds placed from the discovery interface, the Evergreen admin could assign the ITEM_AGE_PROTECTED.override permission to the relevant Evergreen permission groups.
=> Evergreen: use override variant when placing hold requests

code/web/Drivers/Evergreen.php
Otherwise, any hold limit set at the Aspen patron type level would not be enforced.
=> Evergreen Driver: change patron type to use correct field

code/web/Drivers/Evergreen.php
When a set of billings is associated with a checkout, the response from open-ils.actor.user.transactions.have_charge.fleshed for the underlying transaction will have additional keys with more details about the loan and the title associated with the loan. The billing summary record is the value of the 'transaction' key in all cases, however.
To put it another way, the response from that method is an array of hashes, each of which is guaranteed to have a 'transaction' key, while most but not all will have additional keys.
This patch fixes the handling of the response and avoids a crash that causes no fines to be displayed if one of them is associated with a checkout.
Further enhancement is possible to include title, author, due date, etc. in the Aspen fines display.
=> Evergreen Driver: fix crash when displaying certain fines

code/reindexer/src/com/turning_leaf_technologies/reindexer/IlsRecordProcessor.java
Updates to logic for checking for large print. Check did not work when nested under if (!recordInfo.allItemsHaveFormats()). Also added recordInfo.addFormat(translatedFormat) on line 1578 to add the translated format to the correct place.
=> Updates to Large Print Check

.gitignore, code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
Added check for  goreader sans space :)
Added check for "pop-up" and "toy and movable books" for 650 and 655 fields
For Book+CD : CD-ROM will display as Book+CD-ROM and CD will display as Book+CD to distinguish software from other CDs
=> Updates to Formats

code/web/app/viewIdpMetadata.php, code/web/sys/Authentication/SAML2Authentication.php
In order to configure Aspen to work with an SSO IdP we need to know what attributes are being used for what data in the metadata that comes back from the IdP. This commit adds a new viewIdpMetadata.php page that, when called forwards the user to the IdP and, upon authentication, then dumps the metadata that is subsequently received
PR note: @mdnoble73 I think you merged my last commit into 22.09.01 (since the rest of the stuff went into 22.09.00 I think), should we do the same here? If so, does this also get pulled forward into 22.10.00?
=> Add ability to view IdP metadata

code/web/release_notes/22.10.00.MD, code/web/services/Record/AJAX.php, code/web/services/Search/AJAX.php
Return empty string when saved search ID no longer exists for AJAX prospector. Updated release notes. Side Note: needed to use ($searchObject->id) to catch the IDs that have been purged from the database. Without the "->id" the error still gets thrown.
=> AJAX updates

code/web/services/Admin/ObjectEditor.php, code/web/sys/DataObjectUtil.php
If a form contains an input of type "file" the content type should be set accordingly. This commit ensures that the test for file type inputs is recursive through the form structure.
=> Fix content type of forms

code/web/release_notes/22.10.00.MD, code/web/sys/DBMaintenance/version_updates/22.10.00.php
DB update to force reload of Hoopla records. Updated release notes
=> Force Hoopla Reload for 22.10.00 

code/web/app/viewIdpMetadata.php, code/web/cron/refreshSsoMetadata.php, code/web/interface/themes/responsive/MyAccount/ajax-login.tpl, code/web/interface/themes/responsive/MyAccount/login.tpl, code/web/saml2auth.php, code/web/services/MyAccount/AJAX.php, code/web/services/MyAccount/Login.php, code/web/sys/Authentication/SSOSetting.php, code/web/sys/DBMaintenance/version_updates/22.09.01.php, code/web/sys/LibraryLocation/Library.php, sites/ptfse.dev/conf/config.cron.ini, sites/ptfse.dev/conf/config.ini, sites/ptfse.dev/conf/crontab_settings.txt, sites/ptfse.dev/httpd-ptfse.dev.conf, sites/ptfse.dev/ptfse.dev.sh
This commit adds the following:
- Add the ability for the SSO admin to define the entityID for an IdP
- Add the ability to upload metadata as an XML file, this is in addition to the pre-existing ability to specify a URL that the metadata can be retrieved from
=> SSO: Add definable entityId & XML metadata upload

code/web/RecordDrivers/HooplaRecordDriver.php, code/web/release_notes/22.11.00.MD, code/web/sys/Grouping/GroupedWorkDisplaySetting.php
Hoopla titles with season/episode info will now display the same title on full record view that displays in search results. Also changed "Show Standard Reviews" to "Show Syndicated Reviews" for consistency in Admin settings. Updated release notes
=> Hoopla Title Display

code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
Moves printFormats check for Playaway after checks for other Playaway formats so they don't get overwrritten
=> Another Format Fix

code/web/interface/themes/responsive/MyAccount/linkedAccounts.tpl, code/web/interface/themes/responsive/Search/Recommend/multiSelectFacet.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js, code/web/interface/themes/responsive/js/aspen/results-list.js, code/web/release_notes/22.12.00.MD, code/web/services/MyAccount/AJAX.php, code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/22.12.00.php
- Added user ability to block all account linking which severs currently linked accounts. 
- Added new column to user for disableAccountLinking. 
- Added check for linking accounts that prevents users from linking to accounts with account linking disabled. 
- Currently account linking information is still visible when disabled since I thought that'd be useful for testing for now. I did add a check to hide the "add account" button if account linking is disabled. 
- Added ability for users to remove specific accounts that are linking to them. 
- Added ability to translate "More Formats/Authors/etc" and "Apply Filters" for multiselect popup. 
=> Account Linking and Translations

code/web/interface/themes/responsive/MyAccount/linkedAccounts.tpl, code/web/interface/themes/responsive/Search/advanced.tpl, code/web/release_notes/22.12.00.MD, code/web/services/MyAccount/AJAX.php, code/web/sys/Account/User.php
Hide/show account link settings when users toggle account linking
Allow user to sort holds by date placed for Koha and Symphony (did not find necessary data in other ils drivers) 
Allow for use of ' in translations for advanced search join phrases 
=> Various Things

code/web/interface/themes/responsive/Error/401.tpl, code/web/services/Error/Handle401.php, code/web/services/WebBuilder/BasicPage.php
This patch makes accessing a basic page without the right permissions return a 401 instead of a plain 404 as it did before.
- response codes now match messages.
- new files added: Handle401.php and 401.tpl
=> BasicPage should return better HTTP response codes

code/web/interface/themes/responsive/CollectionSpotlight/formattedHorizontalCarouselTitle.tpl, code/web/release_notes/22.12.00.MD
This patch adds a missing space that provoked that the name of the book and the 'by' connector, corresponded to the author name, were together.
-Added a new space between book's name and 'by'
=> Spotlighting Collections should have space now

code/web/services/WebBuilder/PortalPage.php
This patch makes accessing a custom page without the right permissions return a 401 instead of a plain 404 as it did before.
- response codes now match messages.
=> PortalPage should return better HTTP response codes

code/web/sys/Account/User.php
Dismiss account link confirmation when managing account link is removed or account linking is disabled
=> Dismiss Account Link Confirmation

code/web/interface/themes/responsive/MyAccount/addAccountLink.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js, code/web/services/MyAccount/AJAX.php, code/web/sys/Account/User.php
- Go to /MyAccount/ResetPinPage instead of /MyAccount/RequestPinReset 
- Submit processAddLinkedUser() when hitting enter on the username/password input modal for adding a link
- Add prompt to change pin for users disabling account linking (if library does not allow, tell user to contact library) 
- If user removes managing account, notify that managing account and link to /MyAccount/LinkedAccounts
=> Small Linking Fixes

code/web/interface/themes/responsive/MyAccount/addAccountLink.tpl, code/web/services/MyAccount/AJAX.php, code/web/sys/Account/User.php
When hitting 'enter' in the Add Account Link modal - the modal would close and the page would refresh and if there were an error, the message wouldn't show. Added an event listener for the user hitting enter that will just click the submit button so messaging shows as intended. 
Changed "No" to "Manage Linked Accounts" in user message asking if user wants to continue allowing a new link
=> Account Linking Changes

code/web/interface/themes/responsive/MyAccount/expirationFinesNotice.tpl, code/web/interface/themes/responsive/MyAccount/fines.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js
When clicking "manage linked accounts" button in message for a new link, bring patron to /MyAccount/LinkedAccounts and dismiss message
=> Dismiss Message for Linked Account

code/web/Drivers/Sierra.php
Fix names displaying wrong in Sierra, names are stored as 'lastname, firstname'
=> Sierra Name Display

code/web/RecordDrivers/GroupedWorkDriver.php, code/web/release_notes/23.01.00.MD
If a library has Novelist but updates grouped work display for series or volume, use that updated information instead of Novelist data
=> Grouped Work Display

code/web/release_notes/23.01.00.MD, code/web_indexer/src/com/turning_leaf_technologies/website_indexer/WebsiteIndexer.java
Adds functionality to index sitemaps. 
- If sitemap is a sitemap index (ex: https://www.gymshark.com/sitemap.xml), it will index each individual sitemap in that sitemap index.
- In "paths to exclude", to exclude a site from the sitemap, put the full path in (ex: https://www.gymshark.com/about-us) and the indexer will skip that path.
Updated release notes.
=> Index Sitemaps

code/web/interface/themes/responsive/MaterialsRequest/dashboard.tpl, code/web/services/MaterialsRequest/Dashboard.php, code/web/services/MaterialsRequest/Graph.php, code/web/sys/DBMaintenance/version_updates/23.01.00.php, code/web/sys/MaterialsRequestUsage.php
- Changed column name in materials_request_usage from "locationId" to "libraryId" since that's what is being stored in that column 
- Updated other files to reflect this change in nomenclature 
- Dropped ability to choose location on this dashboard since it wasn't working correctly - we will now pull the stats for the user's home library. If they are an admin with no home library, stats will show for the active library. 
- Updated usage dashboard csv exports to reflect this change
=> Materials Request Usage Dashboard

code/web/Drivers/Koha.php
Fix for Koha ILS materials request form not honoring mandatory fields set
=> OPACSuggestionMandatoryFields 

code/web/interface/themes/responsive/Record/evergreenHoldNotifications.tpl
Fix for smarty errors on porter county place hold modal for mobile carrier and mobile number:
Warning: Attempt to read property "value" on null in /usr/local/aspen-discovery/tmp/smarty/compile/9b434256fcacb8a2becae83323f0610faadcdb1c_0.file.evergreenHoldNotifications.tpl.php on line 43
and
Warning: Attempt to read property "value" on null in /usr/local/aspen-discovery/tmp/smarty/compile/9b434256fcacb8a2becae83323f0610faadcdb1c_0.file.evergreenHoldNotifications.tpl.php on line 47
=> PHP 8/Smarty Updates

install/samlsso_config.sh, install/samlsso_installer_debian.sh
SSO installation isn't working on CentOS or Debian because the config script had several off-by-one errors in its parameter handling.
Signed-off-by: Jason Boyer <jboyer@equinoxOLI.org>
=> Adjust SSO installers

code/web/interface/themes/responsive/Record/hold-popup.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/record.js, code/web/services/Record/AJAX.php
- Add popup for when title is already on hold for user to confirm placing a duplicate hold. 
- Disable hold button for when user submits hold form through the modal and reloadHolds when action is taken 
- Made requested changes, confirmed with QA that we want to prompt for placing duplicate holds on item & volume level holds
=> Holds Messaging Updates

code/web/services/Report/StudentReport.php
Two school libraries with apostrophes (Hunter's Lane and Neely's Bend) tripped an error on the Student Overdue Report
=> Fixes Hunter's Lane Student Report

code/cron/nightly_mysql_dump.sh, install/60-aspen.cnf, install/createSite.php, install/installer_debian.sh, install/setup_aspen_user_debian.sh, install/solr_limits.conf
Rather than copying whole files just make the necessary edits or use partial files for *.d/ style configs. (php and mysql config; solr security limits)
Simplify installer_debian.sh a little and make it behave better if run a second time. Also use more portable constructions for some bash-specific builtins used even though the shebang is #!/bin/sh. (user / group creation, 'read -p' vs 'printf ; read', path creation and perms)
You can't always assume #!/bin/sh is bash (it isn't on recent Debian, certainly) so a pass with shellcheck at some point would be a good idea for most shell scripts.
Signed-off-by: Jason Boyer <jboyer@equinoxOLI.org>
=> Debian installer updates

install/installer_debian.sh
Package was being installed during upgrades but not new installs.
Signed-off-by: Jason Boyer <jboyer@equinoxOLI.org>
=> Missing php-imagick on install

code/web/interface/themes/responsive/Record/hold-popup.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/record.js, code/web/release_notes/23.02.00.MD, code/web/services/Record/AJAX.php, code/web/sys/Account/User.php
- If title is on hold, mark $bypassHolds as false so hold form popup will show 
- If title is on hold, let patron know in modal that it is on hold (whether they have "remember my pickup location" on or off) 
- Change text for "Place Hold" button after hold is successfully placed. This will show the translated value for "On Hold for %1%" and "You" and will show the username instead of "You" if it is a linked account 
- Updated release notes to reflect changes (no more page refresh)
=> Small Changes to Hold Form Bypass

code/web/sys/Interface.php
ccfls received a smarty error because they had an empty home link instead of '/'. Their homeLink for the library system was blank, changing it to 'default' fixed the error. This should set it to be '/' if homeLink is blank
=> Fix for blank home link

code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js
Refresh holds after cancelling a hold. Fix for titles no longer showing "on hold for you" after cancelling a duplicate hold
=> Holds Messaging

code/web/RecordDrivers/GroupedWorkDriver.php, code/web/RecordDrivers/MarcRecordDriver.php, code/web/sys/Grouping/Record.php
Adds $recordVariations to $relatedRecord(s) so we can check all formats for a record and display them on the marc record page. If there is only one variation (one format), then we just use the $relatedRecord->format as usual.
=> Show All Variation Formats

install/upgrade_debian.sh
In more recent versions of git when upgrading Aspen and pulling the new branch git will throw an error due to having many different owners of the directories inside /usr/local/aspen-discovery. This tells git to ignore the ownership and pull anyway
=> Fix Git dubious ownersip errors when pulling

data_dir_setup/update_solr_files_debian.sh, install/upgrade_debian.sh
This points the debian install script to a new "update_solr_files" script in data_dir_setup exclusively for debian that replaces "runuser" with "su -c ''user"
=> Remove "runuser" from debian upgrade script

code/web/Drivers/Evergreen.php, code/web/Drivers/Koha.php, code/web/Drivers/OverDriveDriver.php
This changes the displayed date format for frozen holds for the Koha, Evergreen and OverDrive Drivers in 'code/web/Drivers/' allowing them to be read correctly internationally.
=> Fix frozen holds date format to 'M d, Y'

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java, code/events_indexer/src/com/turning_leaf_technologies/events/LibraryMarketLibraryCalendarIndexer.java, code/events_indexer/src/com/turning_leaf_technologies/events/SpringshareLibCalIndexer.java
Trim strings for branch and room names for events where applicable. 
In SpringshareLibCalIndexer.java - didn't add trimTrailingPunctuation() to getNameStringForKeyLibcal() because we use that to get the description - added it to the individual places where we add branch and room instead
=> Trim Strings for Events (facet search fix)

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java, code/web/RecordDrivers/CommunicoEventRecordDriver.php, code/web/interface/themes/responsive/Communico/event.tpl, code/web/interface/themes/responsive/Events/share-tools.tpl, code/web/sys/Events/CommunicoSetting.php
- Cut off the "s" at the end of the url for events for communico for individual event indexing (we want event/38823 instead of events/38823) 
- Update the display page for events that have no image 
- Update language around Communico settings to match the language they use 
- Update getEventCoverUrl to actually fetch the event image :)
=> Communico Updates

code/web/RecordDrivers/CommunicoEventRecordDriver.php, code/web/interface/themes/responsive/Communico/event.tpl
- Added some more metadata to Communico Event pages
- Updated the .tpl so pages have a consistent display whether or not they have images or program type metadata being displayed 
- Staff View will always be on its own row for display
=> Communico Event Display Tweaks

code/web/sys/DBMaintenance/version_updates/23.04.00.php
The *_records_owned tables used to have a default weight of 0, but that was not transferred to *_records_to_include when they were dropped, so auto-inserts of owned records fail with an SQL error. This patch adds a default of 0 to allow them to succeed again.
=> Default weight on (library|location)_records_to_include

code/web/interface/themes/responsive/MyAccount/deletedListEntry.tpl, code/web/interface/themes/responsive/MyAccount/myEventsList.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js, code/web/services/API/ListAPI.php, code/web/services/MyAccount/AJAX.php, code/web/sys/UserLists/UserList.php
- When removing events from "Your Events", event is removed immediately (no page reload needed) 
- No more Events being pulled for lists in LiDA
- For past events in lists - display message "This event has passed" instead of "This entry no longer exists in the catalog"
=> Small Updates

code/web/services/MyAccount/AJAX.php
If event has passed, pull event info from DB, not solr. 
Also, events that are no longer in solr will be marked as past events instead of checking curTime.
=> Past Events Fix

code/web/Drivers/Evergreen.php
- Evergreen allows on-shelf holds to be canceled
- Whether or not the pickup location of an on-shelf hold can be changed depends on the user's permissions, so just try it and catch the error if it fails
=> Evergreen: adjustments to hold editing

code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/23.04.00.php
- Allow up to 255 characters for location when saving events
- Update Communico - Settings to Communico - Attend Settings (continuity for how we display Springshare and Library Market settings)
=> Small Changes

code/web/Drivers/Nashville.php
Patrons seeking to pay for NR fees should be able to do so despite NOT wanting to pay other non-COLLECTION AGENCY fees.
=> Fixes Nashville NonResident fee payment sequence

code/web/release_notes/23.05.00.MD, code/web/sys/Browse/BrowseCategoryGroupEntry.php
- Updated the Browse Category Groups page to check for the user's home library as well as their permissions so if they have "Administer Library Browse Categories" they will only be able to edit browse categories shared with everyone or with their library. They also cannot select a new browse category if it is not shared with everyone or their library, they can only delete it from the group. 
=> Browse Category Group Edit

install/installer_debian.sh
' is considered a special character by ansible and is causing issues with some scripts. This just replaces the abbreviation that uses this character to the original word
=> Remove special character from debian install

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java, code/web/interface/themes/responsive/Communico/event.tpl, code/web/interface/themes/responsive/LibraryMarket/event.tpl, code/web/interface/themes/responsive/MyAccount/myEventsList.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl, code/web/interface/themes/responsive/Springshare/event.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js, code/web/release_notes/23.05.00.MD, code/web/services/MyAccount/AJAX.php
- Adds Check Registration buttons to various places in Aspen for all event integrations. These will appear in search results for events they have added to their events, as well as on the individual event pages.
- Also added a check registration column on the "Your Events" page if an event requires registration
- Made a couple modal titles translatable
- Updated modal for when a user adds an event to their events that requires registration. If they have pop-ups blocked there is a direct link they can follow in the modal.
- Don't index private and canceled events for Communico (Note: I did not include the newly built .java files because of the extra indexing things I'm working on)
- Updated Release Notes
=> Events Changes

install/createSite.php
When using the template for createSite the ilsDBUser variable appears to not be set. This patch adds the assignment back into the script.
=> Add missing variable assignment

code/web/interface/themes/responsive/Communico/event.tpl, code/web/interface/themes/responsive/LibraryMarket/event.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl, code/web/interface/themes/responsive/Springshare/event.tpl, code/web/release_notes/23.05.01.MD, code/web/services/API/ListAPI.php
Remove check for $title['source'] != "Events" - this array did not exist and returned no results for all lists in LiDA. We filter out event results from lists for LiDA in getListEntries() in UserList.php
=> User List API Results

code/web/release_notes/23.07.00.MD, code/web/sys/Covers/DefaultCoverImageBuilder.php, code/web/sys/DBMaintenance/version_updates/23.07.00.php, code/web/sys/Theming/Theme.php
Adds ability to use a custom image for default covers
- Added column defaultCover to themes table
- Added ability to upload a default cover image in Theme settings 
- Updated DefaultCoverImageBuilder.php to use uploaded image if one exists 
=> Custom Default Covers

code/web/release_notes/23.07.00.MD, code/web/sys/Covers/BookCoverProcessor.php, code/web/sys/Covers/DefaultCoverImageBuilder.php
- EBSCOhost default covers will use the logo uploaded for the individual databases if one exists - if there is not one, Aspen will use the default cover image uploaded in Themes (if one exists) 
=> EBSCOhost default covers

code/web/RecordDrivers/WebsitePageRecordDriver.php, code/web/release_notes/23.08.00.MD, code/web/sys/Covers/BookCoverProcessor.php, code/web/sys/Covers/WebPageCoverBuilder.php, code/web/sys/DBMaintenance/version_updates/23.08.00.php, code/web/sys/OpenArchives/OpenArchivesCollection.php, code/web/sys/Recommend/TopFacets.php, code/web/sys/WebsiteIndexing/WebsiteIndexSetting.php
Set default covers for each instance of website indexing settings 
- WebsitePageRecordDriver.php - Added function to get settingId 
- WebPageCoverBuilder.php - if webpage belongs to an indexing setting that has a set default cover, that image will be used instead of the globe 
- WebsiteIndexSetting.php - Added area to upload default cover image 
- Updated 23.08.00.php and release notes
=> Webpage Default Covers

code/web/RecordDrivers/CommunicoEventRecordDriver.php, code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php, code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php, code/web/interface/themes/responsive/Communico/event.tpl, code/web/interface/themes/responsive/GroupedWork/singleVariationManifestion.tpl, code/web/interface/themes/responsive/LibraryMarket/event.tpl, code/web/interface/themes/responsive/MyAccount/myEventsList.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl, code/web/interface/themes/responsive/Springshare/event.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/account.js, code/web/release_notes/23.08.00.MD, code/web/services/MyAccount/AJAX.php, code/web/sys/Covers/BookCoverProcessor.php, code/web/sys/DBMaintenance/version_updates/23.08.00.php, code/web/sys/Events/CommunicoSetting.php, code/web/sys/Events/LMLibraryCalendarSetting.php, code/web/sys/Events/SpringshareLibCalSetting.php
Add an option for libraries to show a custom modal for linking out to event registration pages (if modal body field is empty, no modal will show and user will be redirected to external event page)
New columns added to event settings tables for registrationModalBody
Updated Your Events - no more "Is Registration Required?" column & "Check Registration" button follows new modal rules
=> Event Registration Updates 

code/web/index.php, code/web/interface/themes/responsive/footer_responsive.tpl, code/web/release_notes/23.08.00.MD, code/web/sys/DBMaintenance/version_updates/23.08.00.php, code/web/sys/Interface.php, code/web/sys/SystemVariables.php
Allows the company name in the footer to be set in system variables. Defaults to ByWater Solutions if not changed.
Test Plan:
1.Scroll to the footer on any of the pages on an Aspen site and note that it says supported by ByWater Solutions.
2.Navigate to Administration and then to Database Maintenance and complete updates.
3.Navigate to System Variables within Administration and click edit.
4.The last box should now be an option to edit the name of the supporting company.
5.Edit the company name if needed and save the changes.
6.Ensure that the footer reflects the changes.
=> Footer company variable

code/web/index.php, code/web/interface/themes/responsive/css/cookie-consent.less, code/web/interface/themes/responsive/css/layout.less, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/theme.css.tpl, code/web/release_notes/23.08.00.MD, code/web/sys/DBMaintenance/version_updates/23.08.00.php, code/web/sys/LibraryLocation/Library.php, code/web/sys/SystemVariables.php, code/web/sys/Theming/Theme.php
This PR adds the ability to customise the cookie consent bar using the theming menu
Additionally, also allows you to set cookie consent enabled/disabled and have a separate cookie consent policy per library system.
Test Plan:
Apply Patch
Run DB maintenance.
Navigate to main Library System and make sure a theme is set in "Basic Display" settings
In same library system, set cookie consent to enabled.
Cookie consent should now appear with default blue scheme
Test functionality
Navigate to Theme settings in Aspen Administration
Change Cookie Consent Colorway
Check that Colors have applied on save
Navigate to another Library system and enable a different theme.
Enable cookie consent and make library system your new default
Cookie Consent should have alternate theming based on this Library …
=> Cookie consent enhancements

code/web/Drivers/OverDriveDriver.php, code/web/release_notes/23.09.00.MD
Fix issue where barcodes with a "+" couldn't check out Overdrive items 
=> Barcode with "+"

install/createSite.php
If given a non-localhost database host use it when initially creating the new db.
=> Use supplied db host when creating new database

.gitignore
This patch stops the .vscode folder from being added to git source control.
=> fix: add vscode folder to .gitignore

code/web/interface/themes/responsive/MyAccount/sso-login.tpl
in d6f3c3e4c the hrefs for SSO were updated for one portion of the if statement in sso-login but it appears may have been missed in the else statement below
This patch amends the hrefs to match (as the ones there previously no longer work)
=> fix: update href in sso-login.tpl to new saml auth

code/web/index.php, code/web/interface/themes/responsive/MyAccount/myPreferences.tpl, code/web/interface/themes/responsive/cookie-consent.tpl, code/web/interface/themes/responsive/css/cookie-consent.less, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/cookieConsent.js, code/web/services/AJAX/JSON.php, code/web/services/MyAccount/MyPreferences.php, code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/23.11.00.php, code/web/sys/LibraryLocation/Library.php
This PR changes the cookie consent cookie to a session based cookie, allows storage on a per user basis and allows the preferences to be amended in myPreferences. Also redesigns the cookie consent banner slightly to be more user friendly 
This WILL need a small patch to go alongside to disable google analytics when analytics cookies have not been allowed but would like your input on where you would like it disabled  (I was thinking index.php - around line 138) let me know if you have a preference. Should just be an if statement so literally 30 seconds worth of work.
Test plan:
Enable cookie consent in library settings
Allow cookies,
Check that cookies are set,
delete cookie and check cookie is reapplied from DB on refresh,
delete cookie from both browser and set the cookies to 0 in the …
=> Cookie consent user storage

code/axis_360_export/src/com/turning_leaf_technogies/axis360/Axis360Extractor.java, code/web/release_notes/23.12.00.MD
Fix error "Did not get a successful API response ..." for unavailable Boundless titles
=> Boundless Errors

code/web/Drivers/Evergreen.php
Evergreen has settings and rules for handling patron renewals via the OPAC. If we pass the opac_renewal option to Evergreen, then Aspen will act like Evergreen when renewing on behalf of a patron.
This commit also removes four extraneous lines that are commented out in the Evergreen renewal code.
=> Use OPAC renewals with Evergreen

code/web/release_notes/23.12.00.MD, code/web/sys/WebBuilder/QuickPollSubmission.php
- Now,if the name field is completed for unathenticated users, it will be completed on the form instead a blank space.
- If an authenticated user fill the name field,then the form submission will have the name the user entered in the form instead the user name.
=> Fixed user name property

code/web/services/MyAccount/AJAX.php
Depending on PHP and MySQL driver versions, PHP is increasingly more likely to return numeric columns as PHP integers or floats.
For example, PHP 8.1+ will now do this for emulated prepared statements.
Since Square requires that the idempotency_key be a JSON string, but Aspen uses the numeric user_payments ID for the purpose, this patch ensures that it gets cast to a string.
Concretely, this patch fixes a bug where payments can fail to be created in Square with the following error (as found in Square's API logs):
```
{
"errors": [
{
"code": "EXPECTED_STRING",
"detail": "Expected a string value (line 1, character 20)",
"field": "idempotency_key",
"category": "INVALID_REQUEST_ERROR"
}
]
}
```
=> ensure that Square is passed a string for idempotency_key

code/web/Drivers/Evergreen.php, code/web/interface/themes/responsive/MyAccount/evergreenHoldNotificationPreferences.tpl, code/web/interface/themes/responsive/Record/evergreenHoldNotifications.tpl, code/web/release_notes/23.12.00.MD, code/web/release_notes/24.01.00.MD
If a user has phone notifications enabled but no default phone notification number set, fallback to the day / evening / other phone on their account. This is how the Evergreen OPAC works; the default notification phone number will be used if present, but is not required if another phone number is available on the account.
=> Fallback to User Phone When Placing Holds in Evergreen

code/web/Drivers/Evergreen.php
Add a getCallNumberForCopy() method to the Evergreen driver to retrieve the call number label for a mapped copy.
Refactor the Evergreen driver's getCheckouts() method to use the open-ils.circ.actor.user.checked_out API, to build the checkout object itself from the returned values, and to use the getCallNumberForCopy() method to get the copy's call number for display.
The loadCheckoutData() method remains untouched because it is currently used elsewhere.
This is intended to fix the "issue" of copy barcodes and call numbers not showing up in Aspen when the ILS is Evergreen.
=> Get Barcode and Call Numbers of checkouts in Evergreen

code/web/sys/Covers/BookCoverProcessor.php
Update cover processor to use $_REQUEST['isPast'] for building past event covers, if applicable
=> Past Event Logic for Covers

code/web/sys/SearchObject/SummonSearcher.php
This patch alters the order and concatenation of Summon filters so that Summon filters that contain an ampersand return a result rather than an error.
TEST PLAN:
1) Log into Aspen as admin and ensure that Summon is set up correctly. 
2) Carry out a Summon search (ensuring that the dropdown is set to 'Article and Databases.'
3) Filter your search ensuring any of the facets on the left-hand menu that contain an ampersand ('&').
4) This search will return an error. 
5) Apply the patch and repeat the steps above. The facets that contain ampersands will now return the correct results instead of an error.
=> Fix: Summon facet ampersand error

code/web/release_notes/24.02.04.MD, install/upgrade_debian_23.09.01.sh, install/upgrade_debian_23.12.00.sh, install/upgrade_debian_24.01.00.sh, install/upgrade_debian_24.02.00.sh, install/upgrade_debian_24.02.03.sh
This patch adds the new debian upgrade scripts to match the upgrades scripts for centos.
=> chore: Update debian upgrade scripts to match centos

code/web/release_notes/24.03.00.MD, code/web/sys/ConfigArray.php, code/web/sys/Interface.php
If Aspen is behind a TLS-terminating proxy we don't want to use http:// when building links, even though $_SERVER['HTTPS'] will be false. The X-Forwarded-Proto header is enabled by default for AWS and Google Cloud load balancers, and is easily enabled if using nginx directly.
=> Respect Proxy Protocol

code/web/Drivers/Evergreen.php
Switch to open-ils.actor.patron.settings.retrieve and always pass the user ID to get the default pickup location for new users.
Using this API instead of open-ils.actor.setting.retrieve.atomic allows us to look up setting for patrons even when masquerading.
=> Use better method to get user settings for Evergreen

code/web/ResultsAction.php, code/web/release_notes/24.03.00.MD, code/web/services/Author/Home.php
/Author/Home puts the (normalized) author name in the breadcrumbs, reasonably enough. However, the author name was getting added to the list of translatable terms, pooching it out with a bunch of terms that normally should be displayed as is. This patch marks normalized author breadcrumbs as not to be translated.
=> avoid putting authors into list of translatable terms

security.md
Electron -> Aspen Discovery
security@aspendiscovery.org (Doesn't currently exist) -> security@bywatersolutions.com - can be temporary
=> Fixing typos and email addresses

code/web/Drivers/Koha.php
Koha's API accepts either:
- null
- RFC 3339 formatted dates
passing an empty string is not an option, as it doesn't match the RFC 3339 format.
This patch just makes the empty string use case pass NULL.
I'm not versed enough in PHP but:
- The DateTime class seems to handle reading/writing RFC3339 formatted date/time strings.
- It is not advisable to manually adjust strings to match date formats
- The software should internally pick a representation format and make sure all inputs are sanitized to comply with it
- Each 'driver' should handle converting those DateTime objects to the needed format depending on the external system's requirement
Best regards
=> Empty strings are not correctly formatted dates

.github/workflows/main.yml
We should be running GitHub actions on all pushes. This will let the GitHub Actions build the Docker images which the latest release branch is pushed to Aspen-Discovery/aspen-discovery
=> Run GitHub actions on all pushes

.github/workflows/main.yml
Aspen-Discovery/aspen-discovery has been all set up for building and pushing the images. This commit will prevent the actions for running and failing on other clones of the codebase in GitHub.
=> Only run GitHub Actions for building docker images from Aspen-Discovery/aspen-discovery

code/web/Drivers/Evergreen.php, code/web/release_notes/24.04.00.MD, code/web/sys/LibraryLocation/Library.php
declare $institutionCode
Fix issue for Evergreen driver when doc_id is an integer and we can't read it since we need a string value 
=> Small Fixes

.github/workflows/main.yml
In the GitHub actions, there is a step named "Log in to Docker" but it actually logs into Quay.io The name for this step should be updated to reflect what it actually does.
=> Change step name to refer to Quay.io, not Docker Hub

code/web/release_notes/24.05.00.MD, code/web/sys/DBMaintenance/version_updates/24.05.00.php, code/web/sys/Interface.php, code/web/sys/LocalEnrichment/JavaScriptSnippet.php
This patch adds the ability to flag a JavaScript snippet as containing analytics cookies or not and then runs/does not run the snippet accordingly.
To Test:
Navigate to JavaScript snippets and add a snippet to test is running/not running
Notice the new option for if snippet contains Analytics cookies.
Check that the snippet runs as expected.
Navigate to Library systems and enable cookie consent
Check that snippet runs if "contains Analytics cookies" is disabled and does not if "contains Analytics cookies" is enabled
Accept all cookies.
Snippet should always run regardless of "contains Analytics cookies"
Go to my preferences and disable consent for Analytics cookies.
Check that snippet runs if "contains Analytics cookies" is disabled and does not if "contains Analytics cookies" is enabled
=> Cookie consent snippets

code/web/interface/themes/responsive/WebBuilder/quickPoll.tpl, code/web/release_notes/24.05.00.MD, code/web/services/WebBuilder/QuickPoll.php, code/web/services/WebBuilder/SubmitQuickPoll.php
Fix issue where if a user is doing a quick poll that requires logging in, opens a new tab, signs out in that tab and another user logs in - the new user won't be able to submit the poll that is still open in the other tab 
=> Quick Poll Quick Fix

code/java_shared_libraries/src/com/turning_leaf_technologies/indexing/BaseIndexingSettings.java, code/reindexer/src/org/aspen_discovery/format_classification/MarcRecordFormatClassifier.java, code/reindexer/src/org/aspen_discovery/reindexer/MarcRecordProcessor.java, code/web/release_notes/24.06.00.MD
Fix issue where target audiences were not being mapped using the correct translation maps
Add match for graphic novels where 655a equals "manga" we will add "Manga" as a format
=> Target Audience & Manga vs Manga Graphic Novels 

code/web/interface/themes/responsive/CollectionSpotlight/horizontalCarousel.tpl, code/web/interface/themes/responsive/css-rtl/main.css, code/web/interface/themes/responsive/css-rtl/title-scroller.less, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/css/title-scroller.less, code/web/release_notes/24.06.00.MD
Test plan
Perform a search
Scroll down to the bottom of the page. Click 'Create Spotlight'.
Enter name, click 'Create Spotlight'
Click "Edit" at the top.
Set 'The cover size to use when showing the display' to 'Small' and access the spotlight i.e.: http://localhost:8083/API/SearchAPI?method=getCollectionSpotlight&id=2
Before the patches: Notice the title covers are distorted and the carousel controls don't match the height of the title covers.
After the patches: Notice the title covers are presented with the original aspect ratio and the carousel controls match the new (shorter) height of the title covers
=> Fix display of 'small' covers in collection spotlights

code/web/interface/themes/responsive/js/merge_javascript.php, code/web/release_notes/24.06.00.MD
This PR changes the merge_javascript script to instead call other files relative to the location of the script and not relative to the location the script was called from.
To test:
Make a change to the js files.
Notice the merge_javascript script will only work if executing the script from the containing folder and will fail otherwise.
Apply patch
Notice the script will work regardless of where you run it from
Check the JS files are agglomerated correctly
=> Merge javascript relative fix

code/web/Drivers/Koha.php
Koha's API for renewability will pick the logged in user home branch for calculating renewability. So depending on the home branch for the logged in user, the results it will return.
In order to properly replicate OPAC behavior, Aspen should override the 'current' branch, by passing the `x-koha-library` header, which was designed for this specific purpose. And it should override using the patron's home branch.
That's what this patch does:
Add a new parameter to the `checkAllowRenewals` method so it can be passed the library id.
Use the new parameter to build the `x-koha-library` header.
Retrieve the home library ID from the DB, the same way Aspen already does for other bits, and pass it to `checkAllowRenewals`.
=> Make checkAllowRenewals pass the patron's library ID

code/web/release_notes/24.06.00.MD, code/web/release_notes/24.07.00.MD, code/web/sys/DBMaintenance/version_updates/24.07.00.php
Adjust code to allow Summon facet filters to be unchecked if they are clicked why $isApplied is true
TEST PLAN:
Before applying patch:
Carry out a Summon Search as usual
1.Apply one of the facets
1.Notice that the page reloads and the number of results reflects the chosen filter
3.Click the same filter again, notice the page reloads but the filter is still checked and applied
4.Click the red minus in the Applied Filters section for the filter you wish to remove
5.Notice that the page reloads and the filter has now been removed
APPLY PATCH:
1.Carry out a Summon Search and apply an filter as above
2.Click the same (checked) filter
3.Notice that the page reloads and the filter is now removed.
=> Summon facet uncheck fix

code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/collection-spotlights.js, code/web/release_notes/24.06.00.MD, code/web/services/Admin/CreateCollectionSpotlight.php
This is related to Ticket 133171: "Replace existing spotlight with current search" not updating tabbed spotlights.  The problem happened when doing a search, choosing Create Spotlight from search tools, then choosing to replace an existing spotlight.  If the spotlight only had one tab, it wasn't replaced at all.  If it had more than one, then no matter which tab the user picked, the first tab was the one that would be replaced.  I've tested this in Firefox, Edge, and Chrome with single and multi-tabbed spotlights.
=> Fix replacing Spotlight tabs with a new search

code/web/interface/themes/responsive/Record/view-subjects.tpl, code/web/release_notes/24.07.00.MD, code/web/sys/SolrConnector/Solr.php, sites/default/conf/groupedWorksSearchSpecs2.yaml
Searches that included hyphens, apostrophes, ampersands, question marks, and words that contained both letters and numbers were failing, especially when in quotation marks.  These searches should work now.  This covers tickets: 124011, 125190, 126636, 125764, 125718, 96412, 126604, 127927, 129569, 125996, 127927, 104133, 122594, 106178, 121322, and 104134.
Some example searches that this change fixes are: "World War, 1939-1945 -- Fiction.", "Bush Brothers & Company -- History.", "Chi's Sweet Home", Rejection++(+Psychology+)+--++Religious+++aspects++--++Christianity, K-Ming Chang gods of want, "Economic history -- 21st century.", Did Ye Hear Mammy Died? O'Reilly, Kevin the unicorn: why can't we be bestie-corns?
There are still some things that this change does not fix.  There are lingering …
=> Fix searches that fail because of special characters

code/web/interface/themes/responsive/Search/browse-sub-category-tab.tpl, code/web/interface/themes/responsive/Search/home.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/browse.js, code/web/release_notes/24.06.00.MD
This relates to ticket 133620. Tabbing through accessible browse categories on the homepage went to the next book off the screen instead of to the Next button, which caused Next to move. This change adds tabindex="-1" to the hidden books that are off the screen so that they won't get focus. It also moves the Previous button so that the tab order is now Previous -> Book Cover 1-5 -> Next instead of Book Cover 1-5 -> Previous -> Next. I have tested in Firefox, Edge, and Chrome.
Sorry for any confusion when I accidentally deleted this pull request a moment ago.
=> Fix browse category tab order keyboard navigation

code/web/release_notes/24.07.00.MD, code/web/services/Admin/CreateCollectionSpotlight.php
When replacing a Spotlight tab with a new search there's an option to rename the tab.  But if there's only one tab, it makes sense to rename the whole Spotlight.
=> Change Spotlight title when changing title of only tab

code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryAvailabilityType.java, code/web/release_notes/24.07.00.MD
- Set default value of 1 for AvailabilityType, since CloudLibrary frequently doesn't send an AvailabilityType at all.  This should still get set to 0 if the AvailabilityType is "PREPUB".  I tested that books that are not on order no longer show as on order and that checked out books show as checked out, but I wasn't able to test that books that really are on order still show up that way.
=> Fix CloudLibrary so that books don't always show as On Order

code/web/Drivers/OverDriveDriver.php, code/web/release_notes/24.06.01.MD
-Translated error message when you try to return an OverDrive book that has been transferred to Kindle.
-Updated release notes.
=> Translate Kindle/OverDrive message

code/web/Drivers/Koha.php, code/web/Drivers/Polaris.php, code/web/Drivers/Sierra.php, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/overdrive.js, code/web/release_notes/24.07.00.MD, code/web/services/WebBuilder/CustomFormSubmissions.php
- Made message translatable.
- This is for ticket 123151, which has been closed already.  I couldn't actually get this error message to show up and it looks to me like it may only show for Polaris or possibly not at all, since the ticket says the problem is not happening anymore.
=> Message "old PIN provided is incorrect" should be translatable

code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/overdrive.js
QA fix for the Kindle error message problem. The header said "Title Returned" even when there was an error and the title was not actually returned. Now it displays the appropriate header if the request doesn't succeed.
=> Kindle return error message update

code/reindexer/src/org/aspen_discovery/grouping/GroupedWork.java, code/web/release_notes/24.07.00.MD
- Instead of removing any phrase in the title that is "by" followed by two words, now "by..." is only removed if at least one of the following words is part of the author's name and it's at the end of the title.  So "by Bram Stoker" would be removed from "Dracula by Bram Stoker" but "Death by Vanilla Latte" stays "Death by Vanilla Latte".
=> Only strip by author's name from titles

code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/browse.js
- In Edge and Chrome only, if the user clicked too fast on the arrow Accessible Browse Categories arrows, all the covers in that category would get selected because it was getting detected as a double click. This fixes that problem and you can still select covers and tabbing still works.  I tested in Edge, Chrome, and Firefox.
- No release notes update since this a QA fix relating to a different browse category bug.
=> Fix for Chrome/Edge Browse Category bug

code/web/sys/SolrConnector/Solr.php
Quoted searches that contained a slash on its own (not in the middle of a word) were not returning results.  This was a problem for subject heading searches like "fiction / fantasy".  This change continues to remove slashes in the middle of words but retains and escapes slashes that are not part of words.  
This works well for forward slashes and you get the correct results for backslashes, but they will show up as escaped in the query in the search box, which causes issues if you resubmit the search.  Backslashes in subject headings ought to be really rare though, so it's probably not going to impact many searches.
=> Fix searches that contain slashes

code/web/release_notes/24.07.00.MD, install/createSite.php, install/createSiteTemplate.ini
**Description**:
This patch adds the options to set the name of the supporting company when creating a new site. The user will be prompted to either accept the default (ByWater Solutions), or input their own preferred company name. It also adds the supporting company to the template options for createSiteTemplate.ini.
**Test plan**:
to test without templating:
- cd into the install folder
- run `php createSite.php` and follow the prompts (note that the aspen database credentials must be correct. Also, the aspen database name given here must be unique)
- open your aspen database host, and navigate to the database which you have just created
- open the system_variables table
- check that there is only one row within this table
- also check that the value stored under supportingCompany …
=> Add supporting company to new site install

code/reindexer/src/org/aspen_discovery/format_classification/MarcRecordFormatClassifier.java, code/web/release_notes/24.07.00.MD, code/web/sys/DBMaintenance/version_updates/24.07.00.php
- Add logic for assigning the format 'Physical Object' if position 6 of the Leader is 'R' and the record has no 008 field 
- Increase column length for format in user_hold table to accommodate concatenated OverDrive/Libby formats 
- Tested on my local
=> Small Bug Fixes

code/web/Drivers/CloudLibraryDriver.php, code/web/interface/themes/responsive/CloudLibrary/add-alternate-library-card.tpl, code/web/interface/themes/responsive/CloudLibrary/ajax-checkout-prompt.tpl, code/web/interface/themes/responsive/CloudLibrary/ajax-hold-prompt.tpl, code/web/interface/themes/responsive/MyAccount/libraryCard.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/cloud-library.js, code/web/release_notes/24.08.00.MD, code/web/services/CloudLibrary/AJAX.php, code/web/services/MyAccount/LibraryCard.php, code/web/sys/Account/User.php, code/web/sys/CloudLibrary/CloudLibrarySetting.php, code/web/sys/DBMaintenance/cloud_library_updates.php
This is for Tickets 69336 and 133101 to allow Kansas State Library cards to be used for cloudLibrary.
- Added new field to Cloud Library settings to use the alternate library card for checkout (instead of the main card) and updated database with new field.
- Added success message when updating Alternate Library Card from the Your Library Card(s) page
- If Use Alternate Library Card is turned on for cloudLibrary, then Aspen will send that barcode and password to cloudLibrary for checkouts, holds, etc.  Otherwise it will continue to send the main card information.
- If a user does not have an alternate library card set up or if it's not a valid cloudLibrary account, then they will have an opportunity to add/update it during checkout.  
- If they don't have a valid account, the transaction …
=> Allow alternate library cards to be used with cloudLibrary

code/web/release_notes/24.08.00.MD, code/web/sys/SolrConnector/Solr.php
- This was related to the fixes for special character searches - periods in the middle of words/numbers were getting stripped out and replaced with spaces.  This made the results for something like 1.0 slightly better, but broke call number searching, so it's better to just leave periods alone.
=> Fix for call number searches not returning expected results

code/web/release_notes/24.08.00.MD, code/web/services/MyAccount/AJAX.php
- Add !empty check for 'toLocation' for donations
- Correctly assign Square Token values in 'squareToken'  column instead of 'aciToken' in user_payments table 
=> Square AJAX Error

code/java_shared_libraries/src/com/turning_leaf_technologies/indexing/IndexingProfile.java, code/reindexer/src/org/aspen_discovery/reindexer/ArlingtonKohaRecordProcessor.java, code/reindexer/src/org/aspen_discovery/reindexer/IlsRecordProcessor.java, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/indexing-profile.js, code/web/release_notes/24.08.00.MD, code/web/sys/DBMaintenance/indexing_updates.php, code/web/sys/Indexing/IndexingProfile.php
- Added setting in the Indexing Profile, 'Bib Based Call Number Field', which defaults to the standard Dewey fields (099:092:082), but can be changed to LC fields instead (090:086:050) or whatever the library uses.  These are in order of preference, so only if 099 doesn't exist, use 092, etc.
- Updated database to add new setting field.
- The ILS Record Processor now uses the fields defined in the new setting.  If "use099forBibLevelCallNumbers()"  is set to false (just Arlington), it will skip the 099 even if it's listed.
This is for ticket #133082.
=> Allow custom fields for bib-level call numbers

code/web/release_notes/24.08.00.MD, code/web/sys/SolrConnector/Solr.php, sites/default/conf/groupedWorksSearchSpecs2.yaml
Changes made to improve searches with special characters broke searching by grouped work ID and by ISSN (Ticket 135616).
- If the search query looks like a grouped work ID, skip all special character processing.
- ISSNs are indistinguishable from year ranges (such as '1939-1945') so we can't just skip them since hyphens in year ranges cause lots of subject and author searches to fail.  So instead, allow ISSNs to have a space in place of the hyphen.
=> Fix search by grouped work ID and ISSN

code/web/Drivers/CloudLibraryDriver.php, code/web/release_notes/24.08.00.MD, code/web/sys/Grouping/Manifestation.php, code/web/sys/Grouping/Record.php
- Changed sorting to natural sort so that volumes would sort Vol 1, Vol 2, Vol 10, Vol 11 instead of Vol 1, Vol 10, Vol 11, Vol 2.
=> Sort volume numbers correctly

code/reindexer/src/org/aspen_discovery/reindexer/IlsRecordProcessor.java, code/web/release_notes/24.08.00.MD
- Added missing translation for shelf location facets that were coming from records with both an 852 and an 866 (Ticket 133350).
=> Missing translations for shelf location facets

code/web/interface/themes/responsive/Summon/summonDashboard.tpl, code/web/interface/themes/responsive/Summon/usage-graph.tpl, code/web/release_notes/24.08.00.MD, code/web/services/Summon/UsageGraphs.php
**Description**
An Aspen admin can now view a usage graph and a raw data table for each of the variables included in the Summon Dashboard. This feature used to be limited to the System Reports dashboard, is being added to the ILS Integration https://github.com/PTFS-Europe/aspen-discovery/pull/91, and it is now being extended further.
Note: as with ILS Integration, the implementation for Summons is based on the the System Reports existing usage graphs, and intends to mirror it where possible
Features:
The dashboard now includes links next to the title of each of its sections
Those links lead to the relevant Usage Graph page
The Usage Graph page contains both a graph and a raw data table
While the user is on a given Summon Usage Graph page, the Summon section on the left hand-side options …
=> feat: summon usage graphs

docker/README.md, docker/docker-compose.yml, docker/files/scripts/start.sh, docker/files/tunnel/docker-compose.tunnel.yml
- Fix image's default name used in the stack (docker-compose.yml)
- Add a new label which indicates .env file path
- Add a health check for database's service
- Add a fallback value for the port used for Solr (default : 8983)
- Use a docker volume instead a mount directory to store Solr configurations
- Update README based on new changes
=> Add improvements to docker deploy

code/web/release_notes/24.08.00.MD, code/web/sys/DBMaintenance/version_updates/24.08.00.php, code/web/sys/LibraryLocation/Location.php, code/web/sys/SearchObject/GroupedWorkSearcher2.php
Description:
The request was to add a setting in Primary Configuration > Locations > Searching to hide the branch from the search facets.
This patch implements the first part of that request by adding a 'Show This Branch In Search Facet' checkbox under Searching > Search Facets. This removes the need for additional CSS or JS scripts to hide the ability to search by a specific branch, without affecting the search results themselves (the relevant stock for a branch with a hidden visibility in the search facet will still be found and rendered).
Test plan:
- implement the patch
- login in to Aspen as an admin
- go to Catalog / Grouped Works > 'Grouped Work Facets' in Aspen Administration
- edit 'public'
- add a new facet: Facet: Branch, Display Name: Library, Plural Display Name: Libraries, …
=> Toggle display location in search facets

code/web/interface/themes/responsive/CloudLibrary/add-alternate-library-card.tpl, code/web/interface/themes/responsive/MyAccount/libraryCard.tpl, code/web/services/CloudLibrary/AJAX.php, code/web/services/MyAccount/LibraryCard.php, code/web/sys/DBMaintenance/library_location_updates.php, code/web/sys/LibraryLocation/Library.php
Fixed some QA problems:
- Labels didn't wrap correctly if they were long
- Added default labels if they aren't added at setup
- Fixed problem where adding a card on Your Library Card(s) screen didn't show the updated card number
- Added new field Alternate Library Card Form Message so that optionally an explanation can be added to the form explaining what an alternate card is and how to get one.
=> Alternate Library Card/cloudLibrary form updates

code/web/Drivers/Koha.php, code/web/release_notes/24.09.00.MD
In the function updateHomeLibrary, there is a select to pull the user data from the database. The fetch_assoc is in a while loop that will only ever have a single result because it is a query of the borrowers table based on the borrowernumber. There is no need for a while loop and we can simply call fetch_assoc after checking that the query succeeded.
Test Plan:
1) Check out the latest working branch of Aspen
2) Set up an instance of Aspen connected to Koha with the latest Aspen
and Koha 24.05
3) Log in as a user, browse to Your Account / Your Preferences 4) Set the home library to a different value, click "Update My Preferences" 5) Note the home library has been updated
6) Check out the branch from this pull request
7) Repeat steps 3-5
8) Note there is no change in behavior!
=> Remove superfluous loop in Koha driver function updateHomeLibrary

code/web/Drivers/Koha.php, code/web/release_notes/24.08.01.MD, code/web/sys/SearchObject/GroupedWorkSearcher2.php, install/updateCron_24_08_01.php
- Update the Koha.php message_queue queries to include timestamp of less than 24 hours from time of query to reduce load on servers.
- Update fetchILSMessages cron to run every 40 minutes to relieve other crons happening on the ILS.
=> Fetching ILS Messaging fixes

code/web/interface/themes/responsive/RecordDrivers/GroupedWork/browse_result.tpl, code/web/interface/themes/responsive/RecordDrivers/GroupedWork/result.tpl, code/web/release_notes/24.09.00.MD
Set title to the same text as the alt text so a tooltip shows on hover of the cover image. This was done for both browse category view and search results view of GroupedWork. This fixes  ticket 131697
=> Added title to cover images

install/updateSitePermissions_debian.sh
Logs directory was getting wrong ownership, moving the logs directory ownership command to after the permission changes for the parent should fix it
to test: 
run updateSitePermissions.sh <sitename>, observe that the permissions for var/log/aspen-discovery/<site>/logs are www-data:aspen_apache
apply this patch
run updateSitePermissions.sh <sitename>, observer that the permissions for /var/log/aspen-dsicovery/<site>/logs are now aspen:aspen
=> Change order of permission changes for debian

code/web/services/MaterialsRequest/ManageRequests.php
Looks like I had a typo in the default pageSize value. Fixed to 30, our regular default.
=> Increase pageSize for Materials Requests

code/koha_export/src/com/turning_leaf_technologies/koha_export/KohaExportMain.java, code/web/release_notes/24.09.00.MD
In Koha, it is possible to create item groups (i.e. volumes) without attaching items to that group. If an item group has no items, the volume level hold will be unfillable unless items are added to it at a future time. For these reasons, it makes sense to filter these empty volumes out.
A possible future enhancement would be to make the display of empty volumes configurable.
Test Plan:
1) Set up an instance of Koha connected to Aspen Discovery 2) Create 10 items, and four item groups on one record 3) Attach 3 items to each of 3 of the item groups
4) Run koha_export.jar
5) Note the empty volume shows in the list of volumes you can place
holds on
6) Check out this branch
7) Recompile koha_export.jar
8) Repeat step 4
8) Note the empty volume is no longer in the volume pulldown
Closes …
=> Hide empty item groups for volume-level holds

.github/workflows/main.yml, code/web/release_notes/24.09.00.MD
When a developer pushes a branch of Aspen Discovery to their own repo to create a pull request, it triggers the building of Docker images. The building of the images itself is good to find issues in the build process, but the actions fail because the the actions can only log in on the official repo.
This change resolves this be only logging in to the registries if the commit is pushed to the official repo, while still allowing the docker images to be build for testing purposes.
You can see it working successfully in my personal repo: https://github.com/kylemhall/aspen-discovery/actions/runs/10510807021
=> For GitHub Actions only attempt to log in and push to container repos if the commit is pushed to the official repo

.github/workflows/pull_request_qa.yml, code/web/release_notes/24.09.00.MD
This change adds another test to the GitHub actions that trigger when a pull request is made. This test will check to see if any lines have been indented using spaces instead of tabs.
Test Plan:
1) Include this in a branch
2) Make a pull request for that branch
3) Introduce another commit that uses spaces instead of tabs 3) Note the test fails!
4) Introduce another commit that changes those spaces to tabs 5) Push to your remote pull request branch
6) Note the tests pass!
=> Add check for tabs vs spaces to GitHub Actions for Pull Requests

code/web/Drivers/Koha.php, code/web/release_notes/24.09.00.MD
Within Koha circulation rules are selected by branchcode, categorycode, and itemtype in that order where precedence takes the more specific rule over the less specific rule. This can be seen in the Koha code here: https://git.koha-community.org/Koha-community/Koha/src/branch/main/Koha/CirculationRules.pm#L275
Aspen attempts to replicate this but has a flaw.
The problem only comes into play if the query ends up selecting multiple rules. Koha will always select first rule of the results, but Aspen will always select the last rule of the results.
Closes Aspen-Discovery/aspen-discovery#2008
=> Fix query to select circulation rules for Koha #2008

code/web/Drivers/Koha.php, code/web/release_notes/24.09.00.MD
It is best practice to close all database connections after the data from a query has been ingested and parsed.
This change calls close() on all mysqli result sets that do not already call close after use.
No changes in Aspen behavior should be noted, but this should result in a reduction of used connections to the database.
=> Properly close the connections to Koha from Aspen

code/aspen_app/src/components/Action/ActionButton.js, code/aspen_app/src/components/Action/AddAlternateLibraryCard.js, code/aspen_app/src/components/Action/CheckOut/CheckOut.js, code/aspen_app/src/components/Action/Holds/HoldPrompt.js, code/aspen_app/src/components/Action/Holds/PlaceHold.js, code/aspen_app/src/navigations/drawer/DrawerContent.js, code/aspen_app/src/navigations/stack/LibraryCardStackNavigator.js, code/aspen_app/src/screens/GroupedWork/Editions.js, code/aspen_app/src/screens/GroupedWork/Variations.js, code/aspen_app/src/screens/MyAccount/MyLibraryCard/MyAlternateLibraryCard.js, code/aspen_app/src/screens/MyAccount/MyLibraryCard/MyLibraryCard.js, code/aspen_app/src/translations/defaults.json, code/aspen_app/src/util/api/user.js, code/web/release_notes/24.09.00.MD, code/web/services/API/UserAPI.php
- Added prompts for providing an alternate library card while placing a hold or checking out cloudLibrary items.
- Added a screen to modify or remove alternative library card information, if enabled for the library. This screen is accessible in both the Account Drawer and on the Card screens.
=> add alternate library cards to LiDA

code/web/Drivers/Nashville.php
Fixes mixup on item-level holds between patron name and pickup branch. https://trello.com/c/RQQkLQ3L/3844-add-robertson-academy-gate#comment-66c656a7e4aae5792da48f87
=> Fixes Nashville holds report

code/symphony_export/src/com/turning_leaf_technologies/symphony/SymphonyExportMain.java, code/web/Drivers/SirsiDynixROA.php, code/web/release_notes/24.09.00.MD
Sirsi is not putting volume information in volumes.txt anymore for new Aspen libraries.  The volume description is in the MARC record in the volume subfield, but the call number key (necessary for placing holds) is not.  Existing libraries still use volumes.txt, so that needs to continue to work unchanged.
- Get the volume information from the MARC record from the item field, volume subfield.  
- Prefix volumeId in the ils_volume_info table with LOOKUP: to trigger looking up the call number key while placing the hold.
- Use the Sirsi API to look up all the call number keys for the record, then look up the keys one by one and find the first one that matches the volume description.  There does not appear to be a more efficient way to do this with the Sirsi API.  Holds with lots of items may …
=> Get volume info for holds from MARC record when there is no volumes.txt for Symphony

.github/workflows/pull_request_qa.yml, code/web/release_notes/24.09.00.MD
It appears that quoting a regex in bash causes it to use it as a string
literal so the grep chained to the git diff command never worked.
=> Fix the check_tabs_vs_spaces GitHub Action

code/web/release_notes/24.09.00.MD, code/web/sys/Email/SMTPSetting.php
previously if attachments were not present, it would result in an error when reaching the for loop, and unable to send the email.
=> check smtp attachments array not empty before loop

code/web/openapi/aspen_openapi.json, code/web/release_notes/24.10.00.MD
All edits made with reference to [OpenAPI Specification v3.1.0](https://spec.openapis.org/oas/v3.1.0.html).
- Added servers object and nested the basePath information inside as a variable
- Added license object
- Defined tags to organize paths by API php file
- Updated parameters with the schema attribute
- Replaced produces array with content
- Renamed the definitions array to schemas and placed it under the components object
- Added responses array under the components object and included reusable 400, 401, and 404 responses
- Added summary information, 400, and 401 responses to existing methods
- Removed redundant basePath information from existing paths
=> Migrate Swagger 2.0 documentation to OpenAPI 3.1.0

code/web/release_notes/24.09.01.MD, code/web/sys/DBMaintenance/version_updates/24.09.01.php
Increase the length for debuginfo column in the grouped_work_debug_info table to prevent data truncation errors Updated release notes
=> debuginfo column length

code/web/cron/backupAspen-mydumper.php, code/web/release_notes/24.10.00.MD
#2077 
To test:
Make sure MyDumper is installed, for Debian that is `sudo apt install mydumper`
Apply this patch
Run the backup thusly:
`sudo php backupAspen-mydumper.php blackgold-koha.test`
Notice that it creates a tar.gz backup in /data/aspen-discovery/site.production/sql_backup
Notice that there is a tablewise backup in /data/aspen-discovery/site.production/sql_backup/mydumper
This script will split tables into chunks of 500,000 rows to keep memory usage low on MariaDB, which may reduce OOM events.
To load from this backup, untar/gz the backup file OR point the command at the /usr/local/aspen-discovery/site.production/sql_backup/mydumper directory, and issue (fill in the variables - a myloader importer may be coming along shortly as the code for that also exists but is not …
=> Alternatively use MyDumper for Aspen backups #2077 

code/web/release_notes/24.10.00.MD, code/web/sys/Administration/BlockPatronAccountLink.php
Fixes a bug where users with linked accounts received an error when trying to log in.
https://ticket.bywatersolutions.com/SelfService/Display.html?id=139355
=> 139355: Fixes login error

code/aspen_app/src/translations/defaults.json, code/web/interface/themes/responsive/MyAccount/aspenEmailResetPinResults.tpl, code/web/interface/themes/responsive/MyAccount/emailResetPinResults.tpl, code/web/release_notes/24.10.00.MD, code/web/services/API/UserAPI.php
This replaces instances of 'A email' with  'An email' for consistency
=> Fix typo in default password reset email text

code/web/interface/themes/responsive/Report/studentReport.tpl, code/web/release_notes/24.10.00.MD
Fixes: In Show Data on all three Student Reports in Aspen Admin, the first line of data is being dropped. https://trello.com/c/aZeH6q7C
=> Fixes Nashville student report

code/web/interface/themes/responsive/API/apiDocumentation.tpl, code/web/openapi/.htaccess, code/web/openapi/aspen_openapi.json, code/web/services/API/Documentation.php
Just some changes after some office hours with Mark:
- Changed how the json file is being referenced
- Removed unnecessary HTML from apiDocumentation.tpl
- Removed Abstract and Anode API tags in API documentation
- Added htaccess file to openapi folder
=> Fix adding API documentation to interface

code/web/Drivers/Koha.php
- Remove the 'message' variable that makes sense with the ILS-di mechanism, but not using the API
=> Delete a non-existent field in Koha API response

code/web/release_notes/24.11.00.MD, code/web/services/API/UserAPI.php
Linked Account expiration information is in the user_account_summary table and wasn't getting included in the getLinkedAccounts API call and was therefore missing in LiDA.
=> Include linked account expiry date in getLinkedAccounts API call

code/web/interface/themes/responsive/EBSCO/searchError.tpl, code/web/release_notes/24.10.00.MD, code/web/sys/SearchObject/EbscoEdsSearcher.php
EDS errors should be logged and not echoed, and a standard Aspen Error should be displayed to the user.
**Displaying the Aspen Error:** 
Bug: When an Aspen error is thrown for EBSCO EDS search and the `searchError.tpl` file is displayed, instead of the original error message, a PHP error is shown: `Cannot use object of type AspenError as array`
Expected behaviour: ~~The error message refers to a specific cause~~.
Instead of the rather obscure 'Cannot use object of type AspenError as array', the message should clearly indicate that it is to do with processing the EDS search, and indicate whether it is related to authentication. 
(EDITED)
Test plan:
- navigate to Aspen Administration > EBSCO EDS >
Settings
- create a new Setting, make sure to use invalid
credentials and save
- navigate to …
=> FIX: 24.10.00 handle EDS search error

code/web/release_notes/24.11.00.MD, code/web/services/Record/AJAX.php
Use natural sort for hold items so that if they include volume numbers, they will appear in the expected order (1, 2, 3 not 1, 10, 11).
=> Use natural sort for selecting items when placing a hold

code/aspen_app/src/screens/MyAccount/MyLibraryCard/MyLibraryCard.js, code/aspen_app/src/util/api/user.js, code/web/release_notes/24.11.00.MD
- On the library card page in LiDA, show the home library name instead of the logged-in library for each card.  
- Only show the library logo if the name matches the account's home library.  Ideally, the logo for other libraries would show here, but that might require updates to the Discovery API.
=> LiDA: show linked account home library on Library Card page

code/web/migrations/importSymphonyLists.php, code/web/release_notes/24.10.10.MD
change array position for columns in symphony list import to reflect their current practices (no more last activity and email columns)
updated release notes
=> Symphony List Import

code/web/release_notes/24.11.00.MD, code/web/sys/DBMaintenance/version_updates/24.11.00.php, code/web/sys/Ebsco/EBSCOhostSetting.php, code/web/sys/Ebsco/EDSSettings.php
Store EBSCO passwords as hashed values.
Test plan:
- In Aspen Administration > System Adminstration > modules, enable EBSCO
EDS and EBSCO host
- In Aspen Administration > EBSCO EDS > Settings, create a new setting
and save it
- In Aspen Administration > EBSCOhost > Settings, create a new setting
and save it
- In the Aspen database, check the values of the profilePwd in
ebscohost_settings and edsApiPassword in ebsco_eds_settings
Expected behaviour:
Before the patch, these will be stored as plain text.
Apply the patch, run the db maintenance, then go through the test plan
once more: the values should now be stored as hashed values.
=> 24.11.00 encrypt fields

code/web/Drivers/Koha.php
- Correctly use parameters as object properties instead of array elements after casting parameter array
=> Fix typo issue

code/web/release_notes/24.11.00.MD, code/web/services/MyAccount/AJAX.php
A bug has been reported where user can add to the list of another user. 
TEST PLAN: 
Prior to Applying Patch:
Replicate the bug:
1. Log into Aspen and go to your account, select Masquerade and Masquerade as Library card user number 42. 
2. Create a list. 
3. Carry out a search and select a book, click add to list. Use the developer tools to take notice of the id of the list you are adding to and note it down. 
4. End your masquerade and create a list as Aspen_Admin. 
5. Use the search function and add a different book to your list. 
6. In the Dev Tool, use the Network tab to navigate to the saveToList method and right click. 
7. Select Edit and Resend
8. In the Network console, alter the list id number to the one you noted down and click send. 
9. Masquerade as library card number 42 …
=> 24.11.00 idor fix

code/web/interface/themes/responsive/GroupedWork/ajax-innreach.tpl, code/web/release_notes/24.10.10.MD
Refer to correct array keys for innReach results to prevent no results showing when there should be and php errors
Tested on my local by enabling INN-Reach and viewing various records
=> INN-Reach Fix

code/web/Drivers/Sierra.php, code/web/release_notes/24.11.00.MD, code/web/services/Admin/eCommerceReport.php, code/web/services/MyAccount/AJAX.php, code/web/sys/Account/UserPayment.php, code/web/sys/DBMaintenance/version_updates/24.11.00.php, code/web/sys/SystemVariables.php
Add extra error logging for NCR integration to help debug persistent issues that cannot be replicated on a local machine 
Update the order ID in the user payment table whether we get a good response from NCR or not to help with debugging
Tested on my local
To Test:
Turn on debugging for your IP
As a user with fines, attempt to pay those fines
You should now see external request log entries for creating and completing an NCR order
=> NCR Error Logging

code/aspen_app/src/helpers/item.js, code/aspen_app/src/screens/GroupedWork/Editions.js, code/aspen_app/src/screens/GroupedWork/Variations.js, code/aspen_app/src/screens/GroupedWork/WhereIsIt.js, code/aspen_app/src/screens/MyAccount/CheckedOutTitles/MyCheckout.js, code/aspen_app/src/screens/MyAccount/TitlesOnHold/MyHold.js, code/aspen_app/src/translations/defaults.json, code/web/release_notes/24.11.00.MD
- Updated functions for renewing checkouts, returning checkouts, thawing/freezing holds that are OverDrive items to send sourceId instead of recordId to accommodate for multiple OverDrive settings.
- For libraries with multiple OverDrive connections, holds and checkouts will now display Collection name.
- On the Grouped Work screen, OverDrive items will now display "Where Is It?" to show users the Collection name.
=> Handle multiple OverDrive collections in LiDA

code/web/release_notes/24.11.00.MD, code/web/sys/CurlWrapper.php
This patch relies on a flag that exists for this purpose [CURLOPT_ENCODING](https://www.php.net/manual/en/curl.constants.php#constant.curlopt-encoding).
By setting this flag to an empty string two things happen, according to the docs:
* All supported compression methods are set on the `Accept-Encoding` header (which should be better than hardcoding a specific set of values)
* The response contents get automatically decoded, if required.
I tested keeping the current header we set, and not setting it (I picked the `getOutstandingCreditTotal()` method in the Koha.php file for testing purposes.
In both cases, this change worked. So this change feels forward safe.
To test:
1. Have a dev Aspen instance running along with KTD or connected to *some* Koha instance.
2. Have a valid patron with a …
=> [#2135] Make the CurlWrapper decode compressed contents automatically

.github/workflows/main.yml, code/web/release_notes/24.11.00.MD
At some point Aspen-Discovery/aspen-discovery became Aspen-Discover/aspen-discovery, without they "y" in the org name. This is causing GitHub actions to never run the docker image build process.
=> Fix typos in GitHub Actions for building docker images

code/web/Drivers/Koha.php
To reproduce the bug:
- set up Koha as the ILS Aspen uses
- in Koha, create at least two new patron attributes and give each of these at least two
authorised values
- on Aspen, visit /MyAccount/SelfReg, and scroll down to the Additional Information section
- notice that, while the first dropdown field contains the options it is expected to, further
field will contain the options of the fields
before them as well as their own.
Test plan:
- Apply the patch
- Reload the /MyAccount/SelfReg page
- Notice that the dropdowns now only contain the options they are supposed to
=> fix: populate authorizedValues properly

code/web/interface/themes/responsive/Report/studentReport.tpl
Feedback from the school librarians includes
+ tweak the appearance of the overdue cards 
- increase the white space between cover image and text description
+ Return to report via End Masquerade instead of browser back button is slightly confusing and slightly annoying
=> Tweak Nashville Student Report

code/web/release_notes/24.12.00.MD, code/web/services/MyAccount/SelfReg.php
Motivation:
Some users are accessing <aspen_url>/MyAccount/SelfReg directly,
possibly through search engines, even though
$library->enableSelfRegistration is set to 2 ('Redirect to Self
Registration URL').
This page does not consider that option, and still shows the local
registration form.
This patch aims to fix that.
Test plan (adb):
1) Edit Main Library, visit:
http://localhost:8083/Admin/Libraries?objectAction=edit&id=1
2) Expand 'ILS/Account Integration'
3) Expand 'Self Registration'
4) On 'Enable Self Registration', pick 'Redirect to Self Registration
URL'
5) On 'Self Registration URL, put some valid URL e.g.
'https://help.aspendiscovery.org/'
6) Access the self reg URL directly:
http://localhost:8083/MyAccount/SelfReg
7) Notice you are now directed to the configured selfReg URL
=> Redirect to selfRegistrationUrl if accessing the /MyAccount/SelfReg URL directly.

code/web/interface/themes/responsive/WebBuilder/grapesPage.tpl, code/web/release_notes/24.12.00.MD, code/web/services/WebBuilder/GrapesPage.php
https://aspen-discovery.atlassian.net/jira/software/c/projects/DIS/issues/DIS-33?jql=project%20%3D%20%22DIS%22%20ORDER%20BY%20created%20DESC
Remove Edit button from grapes view as page as the editor can be accessed through the breadcrumbs and this option is more in keeping with the rest of Aspen.
TEST PLAN:
Ensure Web Builder is enabled System Administration->Modules->Web Builder.
Ensure that Grapes JS is enabled System Administration->System Variables-> Enable Grapes Editor
Prior to applying patch:
Navigate to Web Builder->Grapes Pages and select Add new.
Create a page and click Open in Editor.
Add some content using Grapes JS.
Ensure you save the page.
Navigate back to the list of pages using the breadcrumbs at the top of the editor. Click view as page.
Notice that there is an "Edit …
=> 24.12.00 grapes js remove edit button

code/web/release_notes/24.12.00.MD, data_dir_setup/solr7/grouped_works_v2/conf/schema.xml
- Updated Grouped Work Index so that ampersands are replaced with the word 'and' for both the indexed value and the query.  This way a search for 'Love and olives' will return the same results as 'Love & olives'.
Testing Plan
- Copy /usr/local/aspen-discovery/data_dir_setup/solr7/grouped_works_v2/conf/schema.xml into your site's data directory, [data-directory]/aspen-discovery/[your site]/solr7/grouped_works_v2/conf/schema.xml.
- Restart Solr and reindex records.
- Perform a variety of searches that include and or & and verify that they return the same results and that these results are good.  Examples:
- Love and olives / love & olives (keyword or title)
- Bonnie and Clyde / Bonnie & Clyde (keyword or title or subject)
- Dollars and Sense / Dollars & Sense …
=> DIS 45 - A search with 'ampersand' should be the same as 'and'

code/aspen_app/src/translations/defaults.json, code/web/interface/themes/responsive/MyAccount/yearInReview.tpl, code/web/services/API/UserAPI.php, code/web/services/MyAccount/YearInReview.php, code/web/sys/YearInReview/YearInReviewSetting.php
- Adds a direct route to Year In Review if available for user MyAccount/YearInReview that can be called from Aspen LiDA
- Adds setting in User API to check if the user has Year In Review available for determining if a link should be displayed in the Account Drawer in Aspen LiDA
=> Initial setup for Year In Review for LiDA

code/aspen_app/src/navigations/drawer/DrawerContent.js, code/web/release_notes/24.12.00.MD
- If enabled for the user, Year in Review link (labeled as named in the Year in Review settings) will display in Account Drawer and open up a session in Aspen Discovery to load the slideshow.
=> add Year In Review link to Account Drawer in LiDA

code/web/release_notes/24.12.00.MD, code/web/sys/YearInReview/YearInReviewGenerator.php
- When generating a new Year in Review, check for and dismiss old Year in Review messages if they haven't already been dismissed.
=> Don't show old Year in Review messages

code/web/release_notes/24.12.00.MD, code/web/sys/DBMaintenance/version_updates/24.12.00.php
Removes VDX specificity in the default Administer Hold Groups permission description when updating to 24.12.00. 
@mdnoble73 I thought making a new line in the release notes for just this would be extra, so I included myself on your existing entries about updating hold groups, but that's also overselling this PR. I'll bow to your preference about how to represent this in the release notes if you have one.
=> Update Administer Hold Groups description

code/web/release_notes/25.01.00.MD, code/web/sys/Covers/BookCoverProcessor.php
Inadvertently closed the original PR:
https://github.com/Aspen-Discovery/aspen-discovery/pull/2180
On adb, with ktd, we can use record '76' as that has a UPC with a leading zero:
http://localhost:8083/Record/76
Enter valid syndetics credentials or apply the test only patch to override the need for syndetics credentials through the UI, though you still need to add a valid key through the code, your pick.
Access the record:
http://localhost:8083/Record/76
Notice the image is not found, this is because this record's UPC is '021561601628', and processImageURL is not identifying the returned image as a "not found" because it doesn't match any of the checksums it's verifying.
Apply the patch. Repeat the test plan. You'll need to click "Staff View" -> "Reload Cover" on the record page to clear …
=> DIS-139 Syndetics bookcover not showing

code/web/Drivers/Koha.php, code/web/release_notes/25.01.00.MD
Previously, when library's 'showOpacNote' was disabled, the Koha user's
opac note was still being displayed. This is because it's getting added
to _web_note regardless of the setting's value.
This patch removes the opacnote from Koha's getILSMessages, and adds the
setting check to when opacnote should be added to loadContactInformation
or not.
=> Koha showopacnote

code/web/Drivers/Koha.php, code/web/release_notes/25.01.00.MD
In code/web/Drivers/Koha.php, modified the conditional check for $volumeId to use !empty($volumeId) instead of $volumeId != 0. This ensures that when volumeId is undefined, the check can work successfully and remove the "item_group_id" in $postParams. In this case, the items can be placed successfully even without a valid volume Id.
Use-Case:
Before PR:
Placing a hold on a volume with a valid item group worked correctly.
Placing a hold without selecting a specific volume caused a server error.
After PR: Both holds (with and without selecting a specific volume) are placed successfully without errors.
=> DIS-147 Fix volumeId check for the items without valid item group while placing volume holds

code/web/release_notes/25.01.00.MD, code/web/sys/Hoopla/HooplaSetting.php
In the DIS-180 original pull request, Hoopla indexByDay is set to default 1 and readOnly. This will cause the problem once the user clicks "save" for Hoopla Settings, the submission form will not include the value of indexByDay and cause indexByDay to be set as 0. 
In this pull request the indexByDay remains to be default 1 and set it to hidden. So it's unchangeable for the users.
=> DIS-180 Follow up hide Hoopla indexByday in Hoopla Settings

code/web/release_notes/25.02.00.MD, code/web/sys/WebBuilder/PortalCell.php
Jira ticket https://aspen-discovery.atlassian.net/browse/DIS-226
(is a subtask of https://aspen-discovery.atlassian.net/browse/DIS-194)
Test plan on the Jira subtask
=> Dis 226 fix save url to link image to on web builder portal cells

code/web/RecordDrivers/OpenArchivesRecordDriver.php, code/web/interface/themes/responsive/RecordDrivers/OpenArchives/result.tpl, code/web/release_notes/25.02.00.MD
This fix only eliminates the time portion of display dates from Aspen Open Archives search results.
=> DIS-242: simple fix for Open Archives dates

code/web/bootstrap.php, code/web/release_notes/25.02.00.MD
- Reorganized the user agent and IP address usage tracking so it only runs once the instance is confirmed valid and found.
Note: This bug relates to DIS 250, so usage tables will still be spammed with only this patch applied, _but_ this patch works if you see that `aspen_internal` is no longer a table entry once your server has loaded and instance validated (e.g., `localhost` in a local environment).
=> DIS 257: Prevented Spamming of Usage Tables

code/web/interface/themes/responsive/WebBuilder/createTemplatejs.tpl, code/web/interface/themes/responsive/WebBuilder/grapesjs.tpl, code/web/release_notes/25.02.00.MD, code/web/services/WebBuilder/AJAX.php, code/web/services/WebBuilder/GrapesPages.php
https://aspen-discovery.atlassian.net/jira/software/c/projects/DIS/boards/2?search=92&selectedIssue=DIS-92
This commit adds feedback in the form of a message when a grapes page is saved.
=> Dis-92: Add feedback when saving grapes page

code/web/release_notes/25.02.00.MD, code/web/services/MyAccount/MyList.php, code/web/sys/UserLists/UserList.php
- Modified `UserList::getListEntries()` to do SQL-level pagination rather than PHP array slicing of all list entries.
- Removed dynamic weighting from `UserList::getListEntries()`.
- Moved weighting to be performed when titles are added or removed from a patron's list.
To test:
1. Create a very large list of titles (e.g., 600-1,000+) for a patron as which you are masquerading.
2. Create a browse category out of that list.
3. Navigate to the browse category page, and it will likely output an AJAX request error. Depending on the load the server can bear, there may be no error; but, with 1,000+ titles being loaded from the list, an error is guaranteed.
4. Apply the patch and reload the browse category page. The page should load faster with no AJAX request error.
=> DIS-305: Improved Performance When Fetching List Entries for Browse Categories

code/web/release_notes/25.03.00.MD, code/web/services/MyAccount/AJAX.php
to test:
1. Sign in as Aspen Admin (fallslibrary.aspendiscovery.org)
2. Masquerade as PTMPL000000006
3. View their fines
4. Click "Continue to payment"
If you do not have access to fallslibrary another library with paypal set up should suffice. Before this change the iframe is not scrollable if it overflows the space inside the modal. After the change you should be able to scroll to see the entire iframe.
=> DIS-334: Payflow modal cutoff

code/web/release_notes/25.03.00.MD, code/web/sys/LibraryLocation/Library.php
- Added check to make sure `$catalog` is not null before calling `hasIlsConsentSupport()` in `Library.php`.
=> DIS-394: Catalog Instance Must Exist Before Calling ILS Consent Method

code/web/release_notes/25.02.00.MD, code/web/sys/LibraryLocation/Library.php
- Added check to make sure `$catalog` is not null before calling `hasIlsConsentSupport()` in `Library.php` for v25.02.00.
=> DIS-394: Catalog Instance Must Exist Before Calling ILS Consent Method For 25.02.00

code/web/interface/themes/responsive/WebBuilder/resource.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/web-builder.js, code/web/release_notes/25.03.00.MD, code/web/services/WebBuilder/AJAX.php, code/web/sys/DBMaintenance/version_updates/25.03.00.php, code/web/sys/WebBuilder/PortalCell.php
Add Source Type for Custom Web Resource Pages for custom web builder pages (in portal cells)
Add option to upload a custom image for custom_web_resource_page  source type (to use as page logo) Add option to hide description for custom_web_resource_page source type
=> DIS-336 : Updates to Aspen Web Resources Part III

code/web/release_notes/25.03.00.MD, code/web/services/Search/AJAX.php
This patch removes a duplicated block from Search/AJAX.php, in the `getInnReachResults` method, that could yield duplicated hits to the INN-Reach server.
=> DIS-395 Remove redundant code block on InnReach-related method

code/web/release_notes/25.03.00.MD, code/web/sys/InterLibraryLoan/InnReach.php
This patch adds
* logging of the external request made to INN-Reach, through `ExternalRequestLogEntry::logRequest`
* a check for the HTTP response status code, and if it is not 200, an error log will be generated
Test plan:
1. Enable the INN-Reach integration
2. Have random credentials for the OAuth2 section
3. Perform a search
4. Make sure your IP gets external requests logged => An error log should be generated
=> There's a log on the external requests logs
=> DIS-397 Add logging to INN-Reach results fetch method

code/web/Drivers/Polaris.php, code/web/release_notes/25.03.00.MD
- Added check for existence of `$response->AccessToken` and `$response->PatronID`; set either to `null` and log it if either do not exist.
- Underlying problem seems to be that Aspen was trying to make Polaris API calls with a null or empty password during masquerade mode, so undefined properties were being returned in a JSON response from the Polaris authentication API request. Thus, those properties must be set to `null` if they do not truly exist.
=> DIS-425: Added Existence Checks for Polaris API Response Properties

code/web/release_notes/25.02.01.MD, code/web/sys/Covers/BookCoverProcessor.php
- Added check to `BookCoverProcessor::getUploadedListCover()` to make sure the list's cover is actually from an 'upload' source.
Note to anyone who stumbles upon this ticket/pull request:
After this patch has been applied, if there is an existing list that incorrectly uses a cover from a record that has the same ID, you must SQL query to change the `imageSource` of the existing list to `default` (e.g., `UPDATE bookcover_info SET imageSource = 'default' WHERE recordType = 'list' AND recordId = '664'`). This is because `BookCoverProcessor.php` will now properly check the source of the list's book cover before assuming its source and thus create a default cover image. Any future list creations that happen to have the same ID as an existing record will not need this additional step because of …
=> DIS-364: Added Image Source Check for Uploaded List Covers for 25.02.01

code/web/cron/updateNYTLists.php, code/web/release_notes/25.02.01.MD
- NYT List updater was stalling due to a missing include statement for `GroupedWork.php`.
=> DIS-453: Stalling NYT List Updater Due to Missing Include Statement

code/web/CatalogConnection.php, code/web/release_notes/25.03.00.MD
The library reported that patrons can’t log in if their password contains ‘<' ‘&’ while we can masquerade the patron account. 
Found that in CatalogConnection.php `patronLogin()`, we use `strip_tags()` for passwords, which is not necessary since patrons want to use special characters in passwords and passwords usually won’t be displayed.
=> DIS-389 Allow users use special characters in their password

code/web/Drivers/Axis360Driver.php, code/web/interface/themes/responsive/js/aspen/axis360.js, code/web/release_notes/25.03.00.MD
When a Boundless record is showing “available” in Aspen, but actually “waitlist” on Boundless website, if a patron wants to checkout the record, Aspen will redirect to place holds. But it will fail and shows “invalid email address”.
To replicate the bug:
1. Find a Boundless record that “available” in Aspen but “waitlist” on Boundless. 
2. Checkout the record 
3. A pop-up displaying “Sorry, we could not checkout this Boundless title to you. Would you like to place a hold instead?”
4. Click Ok and place a hold 
5. Get the error “Could not place Boundless hold, Invalid Email Address” 
The error comes from when redirecting from Checkout to Placeholds, the email is not being passed, so, add the parameters to the doHold method.
=> DIS-452 Boundless: Pass email during Checkout-to-placeHolds transition

code/web/sys/Series/Series.php
- Fixed case typo; it should have been placeholderListEntry.tpl.
- To test: add a placeholder record to a series (add a record but don't include a grouped work ID) then view the series.  It should load correctly without an error.
=> DIS-454: Unable to load template 'file:Series/placeHolderListEntry.tpl'

code/web/release_notes/25.03.00.MD, install/debian_install_php.sh, install/installer_debian.sh, install/installer_debian_w_av.sh, install/logrotate-debian.conf, install/setup_aspen_user_debian.sh, install/upgrade_debian_25.03.00.sh
Default to php 8.4 and add a helper script to install or upgrade php as needed. Also added some necessary packages that are no longer installed by default (cron, rsyslog, etc.)
Addresses DIS-287
=> DIS-287 Debian Installer Improvements

code/web/release_notes/25.03.00.MD, install/debian_install_php.sh, install/upgrade_debian.sh
Update upgrade_debian.sh script to call upgrade_debian_X.Y.Z.sh scripts correctly and always force correct php version to be enabled in debian_install_php.sh.
=> DIS-287 Debian Installer Followup

code/web/RecordDrivers/OverDriveRecordDriver.php, code/web/release_notes/25.03.00.MD
Adding null check for `OverDriveRecordDriver.php`, `getSubjects() ` for preventing error: `OverDriveRecordDriver::getSubjects(): Return value must be of type array, null returned`
=> DIS-473 Add null check for OverDrive getSubjects()

code/web/RecordDrivers/MarcRecordDriver.php, code/web/release_notes/25.03.00.MD
- Added nullable type hint to `?array $items` parameter for `MarcRecordDriver::oneOrMoreHoldableItemsOwnedByPatronHoldGroups()`. (DIS-502) (*LS*)
=> DIS-502: Fixed Null Type Error When Placing Volume Holds

code/events_indexer/src/com/turning_leaf_technologies/events/AspenEvent.java, code/events_indexer/src/com/turning_leaf_technologies/events/AspenEventsIndexer.java, code/web/interface/themes/responsive/Events/event-graph.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/admin.js, code/web/release_notes/25.03.00.MD, code/web/services/Admin/AJAX.php, code/web/services/Events/EventGraphs.php, code/web/services/Events/EventsFacets.php, code/web/services/Events/IndexingSettings.php, code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/25.03.00.php, code/web/sys/Events/Event.php, code/web/sys/Events/EventField.php, code/web/sys/Events/EventFieldSet.php, code/web/sys/Events/EventsFacetGroup.php, code/web/sys/Events/EventsIndexingSetting.php, code/web/sys/Events/LibraryEventsFacetSetting.php, code/web/sys/LibraryLocation/Library.php, code/web/sys/Recommend/SideFacets.php
- Fixed permissions problem with event reports that wasn't limiting All Locations to be All Locations at their home library
- Added weekNumber to numeric columns so that it would not prevent creating new events by being empty.
- Separated library events facet settings and from library events settings.  This allows each library to have a different set of events facets independent from which event platform they are using.  
- Also allows creating new sets of facets and copying them.
- I didn't remove the old facet settings from the library events setting table out of an abundance of caution to make sure no data gets lost, but I'm pretty sure it could be removed.
- Added libraries field to Indexing Settings and changed the name to Aspen Event Settings.  This only determines whether or not …
=> DIS-192: QA Fixes for Aspen Events part 1

code/web/services/CommunityEngagement/AJAX.php, code/web/services/CommunityEngagement/AdminView.php, code/web/services/CommunityEngagement/CampaignTable.php, code/web/sys/CommunityEngagement/Campaign.php, code/web/sys/CommunityEngagement/CampaignMilestoneUsersProgress.php
This fix ensures that the milestone reward status is only updated for the milestone scope to the particular campaign.
=> DIS-51: Fix Milestone Reward Status

code/web/services/WebBuilder/CustomWebResourcePage.php, code/web/services/WebBuilder/CustomWebResourcePages.php, code/web/services/WebBuilder/WebResourceSettings.php, code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/25.03.00.php, code/web/sys/WebBuilder/CustomWebResourcePage.php, code/web/sys/WebBuilder/WebResourcesSetting.php
Fix issue when viewing Custom Web Resource Pages list without the "Administer All Custom Web Resource Pages"
Limit Web Resource Settings page access to those with the "Administer All Web Resources" permission
Remove "Add To Index" checkbox for object edit pages for Custom Web Resource Pages - this functionality is tied to Web Resource Settings only for now
Only show web resources for the active library on custom web resource pages
=> DIS-336 : Updates to Aspen Web Resources - QA Updates

code/web/cron/runScheduledUpdate.php, install/debian_install_php.sh
Differences in PATH when manually running an upgrade vs default cron path require changes to debian_install_php.sh to operate in either situation. Also use systemctl in runScheduledUpdates.php to properly stop / start cron on Debian systems.
=> DIS-287 Debian PHP Installation / Upgrade via Scheduled Update

code/web/RecordDrivers/MarcRecordDriver.php, code/web/release_notes/25.04.00.MD, code/web/services/Record/AJAX.php, code/web/sys/Grouping/Manifestation.php, code/web/sys/Grouping/Record.php
- Split out isPeriodical determination to its own function in MarcRecordDriver.php and in Manifestation.php 
- Update sorting  functionality in Record.php, Manifestation.php, and Record\AJAX.php to do a custom uasort for periodicals (custom sort will sort things alphabetically, while showing the most recently released items first, according to their call number)
- Update release notes
=> DIS-353: Sort Serials with the newest issue copy first in search results and in the place hold modal

code/events_indexer/src/com/turning_leaf_technologies/events/AspenEventsIndexer.java, code/events_indexer/src/com/turning_leaf_technologies/events/EventsIndexerMain.java, code/web/release_notes/25.04.00.MD, code/web/sys/DBMaintenance/version_updates/25.04.00.php, code/web/sys/Events/EventsIndexingSetting.php, code/web/sys/Events/LocationEventsSetting.php
- Added two new fields to Aspen Events Settings: a settings name for keeping track of multiple settings and a locations field.
- Updated event indexing so that scopes are based on the libraries associated with the setting ID and only events at the locations in the setting are indexed.
- Updated event indexing logging so that the event count is correct for each setting and so that it includes the setting name.
=> DIS-192: Use Aspen Event settings to set library scope instead of basing it on the event type

code/sierra_export_api/src/com/turning_leaf_technologies/sierra/SierraExportAPIMain.java, code/web/release_notes/25.03.01.MD
For Sierra Libraries,  if in Indexing profiles > Sierra Field Mappings > Bib Level Locations Destination Subfield has a value, then the exporter will look for the “locations” array in the API response. Adding the “locations” field in the API call to fix this bug. 
Also add a "marc" field check for better error handling.
=> DIS-571 Sierra API fix the missing locations field

code/web/CatalogConnection.php, code/web/release_notes/25.03.01.MD
For libraries using Sierra, the patrons (including newly registered patrons and existing patrons) will see an error when they want to reset their PIN.
To replicate:
Click Reset PIN before logging in
Input library card number or username
See error Call to a member function findNewUser() on string
When it’s Sierra libraries,  $accountProfileInfo['driver'] is only a string (“Sierra”), To fix this, we need to create a new driver instance.
Submit this PR for 25.03.01
=> DIS-547 Create a new Driver Instance for reset PIN

code/web/release_notes/25.03.01.MD, code/web/sys/Covers/BookCoverProcessor.php, code/web/sys/DBMaintenance/version_updates/25.03.00.php, code/web/sys/DBMaintenance/version_updates/25.03.01.php
- Added a directory creation step to ensure the target `/original/lists/` directory exists before attempting to copy files into it.
- Implemented a fallback mechanism in `getUploadedListCover()` that checks both the new and old directories for list cover images, ensuring covers remain visible during the migration process.
=> DIS-568: Fix List Cover Image Migration and Display Issues

code/web/interface/themes/responsive/MyAccount/aspenEmailResetPinLink.tpl, code/web/interface/themes/responsive/MyAccount/evergreenEmailResetPinLink.tpl, code/web/interface/themes/responsive/MyAccount/kohaEmailResetPinLink.tpl, code/web/interface/themes/responsive/MyAccount/resetExpiredPin.tpl, code/web/interface/themes/responsive/MyAccount/resetPin.tpl, code/web/interface/themes/responsive/MyAccount/sirsiROAEmailResetPinLink.tpl, code/web/release_notes/25.04.00.MD
- Changed `Reset My Pin` inputs to buttons in many reset-pin related template files to prevent malformed HTML and allow the use of the Translation Button.
Note: When using translation mode, the embedded span elements inside buttons initially triggered Cloudflare's WAF security protections, which were then addressed with a custom WAF rule allowing these form submissions. If you encounter similar Cloudflare blocking issues with form submissions containing translated content, consider adding a WAF exception rule to allow the specific submission pattern.
=> DIS-558: Fixed Translation Mode for Reset Pin Buttons

code/web/release_notes/25.04.00.MD, code/web/sys/Account/User.php
For Libraries that don’t select Library System > Allow Patrons to Update Their Preferred Pickup Location, patrons’ pickup locations are always their home library. There’s a case where:
1) Patrons update their home library in the ILS
2) Log in to Aspen, in the My Preferences pages, Home Library, change to the new Home Library
3) Patrons try to place a hold 
4) The default pickup location in the modal still remains the old Home Library 
5) Go back to the My Preferences pages, click “Update My preferences” without making any changes 
6) Try to place a hold again, the default pickup location has changed to the new Hold Library 
In User.php, getPickupLocation(), we can check whether “Allow Patrons to Update Their Preferred Pickup Location” is selected or not, to help determine the patrons' …
=> DIS-574 Fix pickup Loc sync with Home Library if patrons can't customize pickup loc 

.github/workflows/main.yml, code/web/release_notes/25.04.00.MD
This bug is causing indexing to fail on all ADB instances. Since there is no 'latest' tag, the development environments (which rely on moving images and not static ones) have been getting outdated for a while. This means that the SOLR schema has now become out of date, causing the indexing to fail for any users of an image without a specified tag. Docker is designed to automatically pull 'latest' if no tags are given but this image is not updated when a static tag is pushed (as we do currently). We need to do this separately in the github actions and push both to the static tag and latest.
Since this is such a small patch that doesn't touch or affect the codebase at large, I have not updated the release notes here. Let me know if you would prefer this to be included in there and I can get …
=> DIS-575: Add latest tag to github actions for docker image push 

code/web/release_notes/25.04.00.MD, code/web/services/API/SystemAPI.php
If the Android-specific icon is not set for LiDA, return the Apple icon rather than the Login Logo
=> DIS-580: fix Android Icon API request default (now with release notes!)

code/web/release_notes/25.04.00.MD, code/web/sys/Covers/BookCoverProcessor.php, code/web/sys/DBMaintenance/version_updates/25.03.00.php, code/web/sys/DBMaintenance/version_updates/25.04.00.php
- All existing list cover images will be moved to their new directory to maintain backwards compatibility.
=> DIS-568: Move All List Cover Images to the New Directory for Backwards Compatibility

code/web/Drivers/Koha.php, code/web/interface/themes/responsive/MyAccount/emailResetPinResults.tpl, code/web/release_notes/25.04.00.MD, code/web/services/MyAccount/EmailResetPin.php, code/web/services/MyAccount/EmailResetPinResults.php
- Fixed the "Get new password recovery link" so it attempts to send users a new email if one has already been sent for password recovery for Koha ILS.
- Enhanced messages upon successful password resets via email to properly display messages, if any exist, sent from the respective ILS.
Test Plan:
1. On an Aspen-Koha instance, navigate to the site's home page and click "Sign In." Then, click "Reset My PIN / Password."
2. Enter a patron's barcode and email and click "Reset My Pin." If this is your first attempt at a password/pin reset for that patron in the last two days, then a screen with a success message will be displayed.
3. Repeat steps 1-2. An error message will be displayed and click "Get new password recovery link."
4. You will be incorrectly redirected to the screen where you …
=> DIS-602: Fixed Password Reset Resend Email Link for Aspen-Koha Instances

.gitlab-ci.yml, code/web/release_notes/25.05.00.MD
The paths for solr and tunnel services have been corrected.
=> DIS-629: Fix paths for tunnel and solr Dockerfiles on gitlab-ci.yml

code/web/release_notes/25.05.00.MD, docker/files/scripts/start.sh
Data within the source didn't persist between sudden container's restarts.
This patch fix that problem.
=> DIS-710: Fix symbolic links

code/web/interface/themes/responsive/Events/eventsIndexLog.tpl, code/web/release_notes/25.05.00.MD, code/web/services/Events/IndexingLog.php, code/web/sys/Events/EventsIndexingLogEntry.php
- Enhanced the Events Indexing Log page by adding standard filtering controls (e.g., "Min Processed," "Show Errors Only") and refactoring the underlying code for consistency with other administrative log pages.
Test Plan:
1. Navigate to the Events Indexing Log page of the admin interface. Notice that features are missing from other log pages (e.g., "Min Processed," "Show Errors Only").
2. Apply the patch and refresh the page.
=> DIS-706: Refactored Events Indexing Log Page for Consistency and Filtering

code/web/Drivers/PalaceProjectDriver.php, code/web/release_notes/25.05.00.MD, code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/25.05.00.php, code/web/sys/LibraryLocation/Library.php
Usually, libraries that use the Palace Project will have their own collections even if they are in the same consortium, so with the individual Palace Project setting and scope, it’s working well with circulation. 
But here is a case where one consortium has multiple member libraries that share the same Palace Project collections, but every member library has a unique Palace Project ID. And patrons need to circulate with their Home Library Palace project ID so their accounts in the Palace Project can sync well and correctly with Aspen, since Palace Project manages patrons at the library level. Adding multiple unnecessary settings is not an ideal solution.
With this PR, one setting for collection feeding can apply to different member libraries with different Palace Library Id
=> DIS-703: Add Palace Project Library ID in Library

code/web/release_notes/25.05.00.MD, code/web/services/MyAccount/AJAX.php
When patrons pay their fines, they can select the amount they wish to pay. Recently, an issue was discovered where processing a fine with a small amount of $0.10 fails validation.
The problem is likely due to floating-point precision. When converting the string "0.10" to a floating-point number, PHP might internally represent it as something like 0.10000001
Rounding both $fineAmount and $maxFineAmount to 2 decimal places during the validation can help resolve this.
=> DIS-640 Round Fines to 2 decimal

code/web/Drivers/Sierra.php, code/web/release_notes/25.05.00.MD
Sierra.php  _connectToApi() is making the API request with User-Agent Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) and such API got rejected because the User-Agent is outdated. We should use a more modern User-Agent or “Aspen Discovery”
=> DIS-635 Update Sierra User Agent

code/web/release_notes/25.05.00.MD, code/web/sys/Browse/BrowseCategoryGroup.php
- Added edit-pencil icon for the Browse Category Groups table in the admin interface.
Test Plan:
1. Navigate to the Browse Category Groups page in the admin interface. Notice that there is no pencil-edit icon on the left side of each row.
2. Apply patch and repeat step 1.
=> DIS-78: Added ID Property with Label to the Object Structure

code/reindexer/src/org/aspen_discovery/reindexer/GroupedWorkIndexer.java, code/web/RecordDrivers/GroupedWorkDriver.php, code/web/interface/themes/responsive/GroupedWork/series-summary.tpl, code/web/interface/themes/responsive/GroupedWork/work-details.tpl, code/web/interface/themes/responsive/RecordDrivers/GroupedWork/result.tpl, code/web/release_notes/25.05.00.MD, code/web/services/Series/AdministerSeries.php, code/web/sys/DBMaintenance/version_updates/25.05.00.php, code/web/sys/Series/Series.php, code/web/sys/Series/SeriesMember.php
- Fix problems with deleting series.  When deleting a series, also delete its series members.  Titles will not get added to deleted series during reindexing and deleted series won't get re-added.  Added a deleted field to the series_member table.
- If a title belongs to multiple series, show them all, not just the first one.
=> DIS-188: Series fixes

code/web/release_notes/25.05.00.MD, code/web/sys/CommunityEngagement/Campaign.php
Change to more than or equal to in order to account for milestones that can be completed beyond 100 percent
=> DIS-352: fix: correct completed milestones count

code/web/interface/themes/responsive/footer_responsive.tpl, code/web/release_notes/25.05.00.MD, code/web/sys/DBMaintenance/version_updates/25.05.00.php, code/web/sys/Interface.php, code/web/sys/LibraryLocation/Library.php
To test: 
1. Apply the patch
2. Navigate to Primary Configuration > Library Systems > and select a library system. 
3. Scroll down to Contact Links and expand the menu. You should see the options to add a BlueSky link and a Threads URL. 
4. Add a general URL to both options for testing. 
5. Notice that both URLs are functioning in the footer.
=> DIS-458: Added Bluesky and Threads Social Media links

code/reindexer/src/org/aspen_discovery/reindexer/GroupedWorkIndexer.java, code/web/release_notes/25.05.00.MD, code/web/sys/DBMaintenance/version_updates/25.05.00.php
- During indexing, remove grouped works from series when the grouped work permanent ID no longer exists because the record has been edited or removed.  Not removing these was causing orphaned titles to show up on Series pages.
- Add script to remove duplicate records to 25.05.00 database maintenance.  This will only remove duplicates that were not manually added and haven't already been excluded.
=> DIS 188: duplicate series record fixes and cleanup script

code/web/interface/themes/responsive/css/browse-categories.less, code/web/interface/themes/responsive/css/main.css, code/web/release_notes/25.05.00.MD
- Changed `.browse-thumbnail` CSS rule from `display: inline-block` to `display: block` to properly align items within the grid without affecting masonry layouts.
=> DIS-741: Correct Browse Thumbnail to Use Display Block

code/web/services/MyAccount/AJAX.php, code/web/sys/LibraryLocation/Library.php
Amend wording of label 
Ensure selected user exists when filtering exports - if on "all" page filter by record only.
=> DIS-313: Fix: amend wording and check selected user exists prior to filtering for exports

code/web/Drivers/Koha.php, code/web/release_notes/25.06.00.MD
- Resolved an issue that could prevent users with expired passwords from successfully resetting their password when prompted on the login screen.
Test Plan:
1. In any Koha version greater than or equal to 24.11.0, the `ForcePasswordResetWhenSetByStaff` system preference must be enabled.
2. Create a new patron account in Koha.
3. Navigate to Aspen and attempt to log in. You will see a notification display that the password/pin must be reset.
4. In the password-reset pop-up modal, input a new password and submit it. You will see a "Token not found" error display on a new page.
5. Apply the patch and repeat steps 1-4 _but with another, new patron account_. You may delete the initial one created for this test and subsequently recreate it. Now, your password reset in Aspen will be successful.
=> DIS-744: Fixed Koha Password Reset Failure for Expired Passwords

code/reindexer/src/org/aspen_discovery/reindexer/PalaceProjectProcessor.java, code/web/release_notes/25.06.00.MD
- Palace Project titles will now display the correct language more reliably, so language filters and searches better match the actual content.
Test Plan:
1. Find a grouped work with only a Palace Project record whose language displayed is correct, but when you view the language set in the Staff View (i.e., the language stored in Solr), it is different, likely “English.”
2. Apply the patch. Force reindex the grouped work and wait a couple of minutes. Notice that the language in the Staff View (and in Solr) matches the displayed language next to the grouped work’s cover.
=> DIS-752: Palace Project Grouped Work Language Not Properly Set

code/web/Drivers/Koha.php, code/web/release_notes/25.06.00.MD
- Patrons’ reading histories now update correctly each night, ensuring their recent check-outs and returns are always recorded, even if they haven’t signed in daily.
Test Plan: Difficult to recreate for testing, but if you glance at the Cron Logs in the admin interface, large numbers of updates are skipped because of the incorrect logic.
=> DIS-768: Incorrect Bypass Logic for Koha Reading History Updates

code/web/interface/themes/responsive/RecordDrivers/List/listEntry.tpl, code/web/release_notes/25.06.00.MD
- List entries will no longer occasionally display confusing PHP warnings or broken layouts.
Test Plan: Difficult to test because I have only seen one case of it. Regardless, those parameters are not used.
=> DIS-789: Remove Undefined Smarty Parameters for List Entries

code/axis_360_export/src/com/turning_leaf_technogies/axis360/Axis360Extractor.java, code/web/release_notes/25.06.00.MD
Inactive Boundless records couldn't be removed from the database because records' related availability didn't get deleted successfully from the database. This patch corrected the query.
=> DIS-785 Remove Inactive Boundless Records

code/reindexer/src/org/aspen_discovery/grouping/RecordGroupingProcessor.java, code/web/release_notes/25.06.00.MD
- Fixed a Java compilation issue caused by ambiguity between `org.marc4j.marc.Record` and the new `java.lang.Record` class in Java 14+.
=> DIS-808: Fix Ambiguous Record Reference in New Java

code/events_indexer/src/com/turning_leaf_technologies/events/SpringshareLibCalIndexer.java, code/web/release_notes/25.06.00.MD
- Strip trailing whitespace and punctuation from JSON‐sourced fields to allow for proper facet searching.
Test Plan: Difficult to recreate unless your Springeshare LibCal integration sends Aspen JSON‐derived fields with trailing white-space and/or punctuation. Regardless, if you apply the patch, the events indexer will properly index events as before.
=> DIS-857: Trim Trailing Space & Punctuation for LibCal JSON Fields

code/web/interface/themes/responsive/AJAX/libraryHoursAndLocations.tpl, code/web/interface/themes/responsive/js/aspen/web-builder.js, code/web/release_notes/25.06.00.MD, code/web/sys/DBMaintenance/version_updates/25.06.00.php, code/web/sys/WebBuilder/PortalCell.php
- Added configuration to the "Library Hours and Locations" cell to always display a specific library's information if a location is selected under the new "Static Location" dropdown on the Portal Cells page.
Test Plan:
1. Apply the patch.
2. Navigate to the Custom Pages setting in the admin interface.
3. Create a new custom page or select an existing one.
4. Add or edit a row and add or edit an existing Portal Cell.
5. On the WebBuilder Portal Cells page, select “Library Hours and Locations” as the Source Type.
6. Select a location under the Static Location dropdown and click “Save Changes and Return.”
7. Navigate to the actual custom page you created (e.g., https://beta.aspendiscovery.org/hours_locations). Notice that users cannot select locations and that the static location’s …
=> DIS-849: Add Static Location Selector for Hours & Locations Cells

code/java_shared_libraries/src/com/turning_leaf_technologies/dates/DateUtils.java, code/reindexer/src/org/aspen_discovery/reindexer/GroupedWorkSolr2.java, code/web/release_notes/25.06.00.MD, code/web/sys/Recommend/SideFacets.php
- Added a dedicated "In Processing" option within the "Added in the Last" facet group.
- Extended the indexing logic in `GroupedWorkSolr2` to use an item’s grouped status (e.g., "On Order," "In Processing," "Under Consideration") for building all related facets, no longer relying solely on the detailed status.
Tested on GMILCS Test server.
Test Plan:
1. Locate grouped works that have a grouped status of “In Processing.”
2. Apply the patch and reindex those grouped works.
- Note: I’m not sure if this is a general bug, but after rebuilding and uploading the `reindexer.jar`, if I click “Force Reindex” under the Staff View, the `local_days_since_added_{library}` field under Solr Details will properly display `-2`, but the `local_time_since_added_{library}` will display `On Order`. If I run a …
=> DIS-834: Add In-Processing Facet

code/web/interface/themes/responsive/MaterialsRequest/manageRequests.tpl, code/web/interface/themes/responsive/MaterialsRequest/request-form-fields.tpl, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/materials-request.js, code/web/release_notes/25.06.00.MD, code/web/services/MaterialsRequest/AJAX.php, code/web/services/MaterialsRequest/Update.php
- Add "Assigned To" as an editable field when updating a single materials request as an admin 
- On Manage Materials Requests page, remove separate buttons for changing status/assignee and replace with a single button labeled "Update Selected Requests" If one is left as the default "Select One" value, it will not be updated for the selected materials requests
=> DIS-802: Materials Request: Assign and change status at the same time for materials request

code/reindexer/src/org/aspen_discovery/reindexer/GroupedWorkIndexer.java, code/web/RecordDrivers/GroupedWorkDriver.php, code/web/RecordDrivers/SeriesRecordDriver.php, code/web/interface/themes/responsive/GroupedWork/series-summary.tpl, code/web/interface/themes/responsive/GroupedWork/work-details.tpl, code/web/interface/themes/responsive/RecordDrivers/GroupedWork/result.tpl, code/web/release_notes/25.06.00.MD, code/web/sys/DBMaintenance/version_updates/25.06.00.php
- Add check to make sure that series are only deleted when they don't have any members.  This wasn't getting checked if the update was due to a grouped record permanent ID getting deleted.
- Delete series from Solr at the same time that they are being deleted from the database.
- Better handling in templates for situations where series don't exist but are still in the index or database for some reason.
=> DIS-188: Series bug fixes

code/web/interface/themes/responsive/DataObjectUtil/objectEditForm.tpl, code/web/interface/themes/responsive/DataObjectUtil/oneToMany.tpl, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/css/responsive_base.less, code/web/interface/themes/responsive/js/aspen/form-fields.js, code/web/interface/themes/responsive/js/javascript_files.txt, code/web/release_notes/25.06.00.MD
- Added front-end validation for fields with character limits to prevent users from inputting beyond the defined character limit.
- Character counters display when users type in fields or interact with fields nearing their maximum length.
Test Plan:
1. Locate any field that has a character limit set by a `maxLength` attribute within its property declaration (e.g., “Collections to include” field in Library System settings).
2. Input a number of characters larger than the field’s set `maxLength` and save the form. Notice that the field will not save because it exceeded the number of characters its respective database column could accept.
3. Apply the patch.
4. Input a couple of characters and notice that the character counter will display at the rightmost side of the input field.
5. Input a …
=> DIS-803: Add Character Limit Feedback and Validation to Forms

code/web/Drivers/Koha.php, code/web/release_notes/25.06.00.MD
- The navigation bar now immediately reflects the patron's updated display name after saving Contact Information.
- Fixed PHP warnings in the Koha driver when fetching empty extended attributes on the Contact Information page.
Test Plan:
1. Navigate to your Contact Information page, fill out the form, and submit it. Notice that your display name at the top right above the navigation bar has not changed.
2. Apply the patch and repeat step 1. Notice that your display name has updated.
=> DIS-866: Update Display Name When Updating Koha Contact Info

code/web/interface/themes/responsive/MaterialsRequest/manageRequests.tpl, code/web/interface/themes/responsive/MaterialsRequest/myMaterialRequests.tpl, code/web/interface/themes/responsive/MaterialsRequest/update-result.tpl, code/web/release_notes/25.06.00.MD, code/web/services/MaterialsRequest/ManageRequests.php, code/web/services/MaterialsRequest/MyRequests.php, code/web/services/MaterialsRequest/Submit.php, code/web/services/MaterialsRequest/Update.php
Remove both created/updated successfully pages for materials requests and instead redirect to the appropriate /MyRequests or /ManageRequests page
For most errors on submitting new requests, the user will still be redirected to a new page
=> DIS-806: Remove Materials Request updated successfully page

code/web/release_notes/25.06.00.MD, code/web/sys/Account/User.php
Below error happened when patrons' home library has Hoopla Flex turned off, in My Account page and sometimes above Place Hold buttons with debugging on:
`Warning: Attempt to read property "includeFlex" on null in /usr/local/aspen-discovery/code/web/sys/Account/User.php on line 866`
Adding a null check for Hoopla Scope can fix this issue
=> DIS-871 Add Null Checks for Hoopla scope

code/web/interface/themes/responsive/MyAccount/hooplaHold.tpl, code/web/release_notes/25.06.00.MD
For holds that are ready for pickup, Aspen will display their expiration date for the holds reservation. ILS and other eContent expiration dates are displaying as ‘Expires’ while Hoopla Flex’s holds are displaying as ‘Expiration Date’. We should keep the consistency.
=> DIS-872 Ensure consistent expiration date display for reserved holds

code/web/CatalogConnection.php, code/web/release_notes/25.06.00.MD
- Fixed an issue where reading history entries missing an author were being pushed to the top of the sort when sorting Reading History by author.
Test Plan:
1. Navigate to your account’s Reading History page and select “Sort by Author.” If any entries are missing authors, notice that they are incorrectly pushed to the top.
2. Apply the patch and repeat step 1. Notice that entries with authors are properly sorted alphabetically.
=> DIS-876: Reading History “Sort by Author” Should Push Entries with Missing Authors to the Bottom

code/web/Drivers/Sierra.php, code/web/release_notes/25.06.00.MD
Include 'placed' field in Sierra get holds request so that holds can be sorted by when they were placed.
=> Dis 720 sorting sierra holds by date placed

code/web/interface/themes/responsive/Admin/propertiesList.tpl, code/web/release_notes/25.06.00.MD, code/web/services/Admin/AJAX.php, code/web/services/Admin/ObjectEditor.php, code/web/services/Admin/Themes.php, code/web/services/Greenhouse/ScheduledUpdates.php, code/web/sys/LibraryLocation/Library.php, code/web/sys/Theming/Theme.php
- The essential default theme can no longer be deleted, as there must be at least one theme for site stability.
- If deleting a theme would leave a library with no theme, deletion is prevented.
- If deleting a parent theme on which other child themes depend, deletion is prevented.
- If a theme cannot be deleted because it's actively in use, there is a clear alert after saving that explains exactly why it cannot be removed.
- The "Delete All" button has been removed from the Themes administration page to prevent the deletion of all themes.
Test Plan:
1. Navigate to the Themes admin interface and delete a Theme that is the parent theme of another theme (i.e., another themes extends the about-to-be-deleted theme). I recommend creating backup tables of the following tables so they can be …
=> DIS-759: Validate Before Removing Themes and Libraries from Themes

code/web/interface/themes/responsive/Admin/adminMenu.tpl, code/web/interface/themes/responsive/css/layout.less, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/layout.tpl, code/web/release_notes/25.06.00.MD
- Allow the admin sidebar to be expanded and collapsed to be able to better view the contents of a page. (DIS-848) (*MDN*, *LS*)
Test Plan:
1. On the current 25.06.00, navigate to the admin interface and notice the position of button to collapse the admin sidebar.
2. Apply the patch and notice the new position and styling of the button to collapse the admin sidebar.
=> DIS-848: Reposition & Style Expand Admin Sidebar Button

code/web/Drivers/Koha.php, code/web/release_notes/25.06.00.MD
**Test plan** 
Before the patch:
- Users with expired cards can login ignoring the Aspen preference "Prevent Login for Expired Cards" 
After the patch:
- Users with expired cards are not able to login if the preference "Prevent Login for Expired Cards" is enabled
=> DIS-825: Prevent login of expired cards

code/web/index.php, code/web/interface/plugins/function.translate.php, code/web/release_notes/25.06.00.MD, code/web/services/Search/Results.php, code/web/sys/Interface.php, code/web/sys/Translation/Translator.php
- Translation database insertions and updates now only occur when actively in translation mode, improving performance and data integrity.
- Added protection against malicious search attempts, including directory traversal and invalid search parameters.
Translations Test Plan:
1. Start translation mode and locate a translatable phrase in Aspen that is publicly visible for testing purposes. Exit translation mode.
2. Delete the translated phrase from the `translation_terms` and `translations` tables.
3. Log out of your administrator account and refresh the page containing your chosen phrase. Query those two tables to see that the term has been automatically reinserted.
4. Apply the patch and repeat steps 1-3. Notice that the translated term is not reinserted into either of those tables.
5. …
=> DIS-911: Prevent Unauthorized Translation Term Insertion & Add Search Security

code/cron/src/com/turning_leaf_technologies/cron/CronProcessLogEntry.java, code/cron/src/com/turning_leaf_technologies/cron/reading_history/UpdateReadingHistory.java, code/cron/src/com/turning_leaf_technologies/cron/reading_history/UpdateReadingHistoryTask.java, code/web/Drivers/Sierra.php, code/web/release_notes/25.06.00.MD, sites/default/conf/config.cron.ini, sites/template.linux/conf/config.cron.ini
- Dramatically increased the processing rate of nightly user reading history updates.
- Enhanced log entries to show full configuration context and update progress for nightly user reading history updates.
- Fixed an issue where a failed Sierra INN-Reach connection would output errors in the nightly user reading history updates logs.
Test Plan:
1. Wait or manually run the nightly `UpdateReadingHistory` Java process.
2. Apply the patch and repeat step 1. If you compare the completion times between the two in the Cron Logs, you will notice that after the patch, there was a dramatic decrease in the amount of time it took to complete.
=> DIS-791: Enhance `UpdateReadingHistory` Cron with Configurable Thread Pool & Improved Logging

code/web/interface/themes/responsive/css/layout.less, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/theme.css.tpl
**Note**: After applying this patch, you must re-save your theme to regenerate the theme's CSS (or perform a DB maintenance, which regenerates CSS for all themes) and for the correct background color to display.
=> DIS-848: Corrected Collapsed Sidebar Button to Use Theme Primary BG Color

code/web/sys/Theming/Theme.php
- Removed "Warning" button on the Themes page, as it was an old idea for how to warn users, but it is no longer needed.
=> DIS-759: Removed Unnecessary Additional List Actions for Themes

code/web/cron/updateNYTLists.php, code/web/release_notes/25.05.01.MD, code/web/release_notes/25.06.01.MD
- Update the number of lists processed within the log entry while processing New York Times updates.
- Remove delay between processing lists for the New York Times since all information is immediately available.
=> DIS-853 New York Times API updates

code/web/interface/themes/responsive/horizontal-menu-bar.tpl, code/web/release_notes/25.07.00.MD
Change the display of header link titles and aria labels to accurately reflect whether the links will open in the current or new tabs.
=> DIS-937: Correct herader links title and aria label

code/reindexer/src/org/aspen_discovery/reindexer/AbstractGroupedWorkSolr.java, code/reindexer/src/org/aspen_discovery/reindexer/GroupedWorkSolr.java, code/reindexer/src/org/aspen_discovery/reindexer/GroupedWorkSolr2.java, code/reindexer/src/org/aspen_discovery/reindexer/MarcRecordProcessor.java, code/web/release_notes/25.07.00.MD, data_dir_setup/solr7/grouped_works_v2/conf/schema.xml, sites/default/conf/groupedWorksSearchSpecs.yaml, sites/default/conf/groupedWorksSearchSpecs2.yaml
- Update MARC indexing so that 490 fields with a first indicator of 0 are always added as series.  First indicator of 1 is ignored, since it should have duplicate content in 800 or 830. 800 and 830 series are still included as before.
- Remove series2 field from reindexer and Solr schema, since it's no longer necessary.
- Update release notes.
=> DIS-715: display uncontrolled series (490, first indicator 0)

code/web/Drivers/KohaApiUserAgent.php, code/web/release_notes/25.07.00.MD
Until now, every time Aspen makes a Koha API call, it is renewing the access token, which means that Aspen is accessing the API unnecessarily. 
This patch fixes the problem by storing the access token as a cached value and renewing it if it has not yet expired.
=> DIS-936: Refresh access token

code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/admin.js, code/web/release_notes/25.07.00.MD, code/web/services/WebBuilder/AJAX.php, code/web/services/WebBuilder/Images.php, code/web/services/WebBuilder/PDFs.php, code/web/sys/Account/User.php, code/web/sys/DBMaintenance/version_updates/25.07.00.php, code/web/sys/File/FileUpload.php, code/web/sys/File/ImageUpload.php
- Add new restrictive permission for managing images and pdfs for user home library
- Add related logic for this permission to ImageUpload.php, FileUpload.php, Images.php, PDFs.php, WebBuilder/AJAX.php, and User.php 
- Add new function for toggling showing/hiding sharing options in admin.js
- Update Release Notes
=> DIS-657: Prevent Uploaded File Overwrite Part I

code/web/RecordDrivers/MarcRecordDriver.php, code/web/release_notes/25.07.00.MD
- Implemented a check to confirm file existence in the file system before rendering the uploaded file.
Test Plan: 
1. Upload a supplemental file and manually delete it from the file system. 
2. View that record in the catalog and attempt to delete it through the interface. Notice the error that it could not be deleted.
3. Apply the patch, reload the page, and notice that any display about the file is gone.
=> DIS-1004: Added Check for File Existence for MARC Records

code/web/release_notes/25.07.00.MD, code/web/services/MyAccount/AJAX.php, code/web/sys/DBMaintenance/version_updates/25.07.00.php, code/web/sys/ECommerce/CompriseSetting.php
Libraries using Comprise payments reported that donations being made through Aspen are being lumped together with fine payments on Comprise reports. 
To fix this, we can add a separate optional section for Donation, with a different Customer Name and Customer ID. If libraries do not fill out the donation section, the donation will use the general customer name and customer ID.
To Test:
1. Set the payment method to Comprise in Library > Fines/e-commerce > Show E-Commerce Link
2. Set a patron account with $2 fines 
3. Apply this PR, leave Comprise Settings > Donation settings (Optional) as blank 
4. Add a logger for `$paymentRequestUrl` in `code/web/services/MyAccount/AJAX.php` > `createCompriseOrder()`
5. Go to My Account > Fines > Click to pay fines online, in `messages.log` see the …
=> DIS-977 Add optional donations settings in Comprise Settings

code/web/interface/themes/responsive/theme.css.tpl, code/web/release_notes/25.07.00.MD
I ended up picking `$bodyTextColor` instead of `$primaryForegroundColor` because it worked better with sample custom themes already in use for me locally ¯\_(ツ)_/¯
=> DIS-962: Use theme color for Explore More arrows

code/web/Drivers/Koha.php, code/web/release_notes/25.07.00.MD
- Corrected an issue where the `ils_password` was not being fetched from the user object, so the condition would always be true.
=> DIS-719: Correction to Fetch the `ils_password` from the User Object

code/web/interface/themes/responsive/Browse/newBrowseCategoryForm.tpl, code/web/release_notes/25.07.00.MD, code/web/services/Browse/AJAX.php
- Adjusted behavior to ensure administrators with the "Administer Library Browse Categories" permission can only add browse categories to their home library's catalog, regardless of which catalog they are currently viewing.
- The "Add as New Browse Category" modal now displays the library catalog where the category will appear, and includes usability improvements such as clearer field names, hover descriptions, and indicators for required fields.
Tested on CW Mars' test server.
Test Plan:
1. Log into an account that has the "Administer Library Browse Categories" permission; it should not have either of the other browse-category permissions.
2. Navigate to a catalog that is not the account’s home library.
3. On the search results page, click "Search Tools," click "Add to Browse," and click …
=> DIS-1026: Fixed Browse Category Creation for Admins Across Libraries and Improved Form Clarity

code/web/Drivers/Evergreen.php, code/web/release_notes/25.07.00.MD
- Fixed an issue where meta-record (M-level) holds were displaying incorrect titles in patrons' hold lists; they now show the correct associated title information.
Tested on CW Mars' test server. This requires that the hold be placed in the Evergreen ILS.
=> DIS-981: Fixed Incorrect Title Display for Evergreen Meta-Record Holds in Patron Hold Lists

code/web/release_notes/25.07.00.MD, code/web/sys/LibraryLocation/Location.php
- Updated the label "Automatically update hours from the ILS" to "Automatically Update with Closures from the ILS" under the Location settings to more accurately reflect its purpose. This option is now hidden for Aspen instances using other ILSs.
Test Plan:
1. Navigate to your Location settings and select a location.
2. Navigate to the Library Hours section and open the accordion. Note the current label "Automatically update hours from the ILS".
3. Apply the patch. Notice the label has changed to "Automatically Update with Closures from the ILS," and the option will be hidden for Aspen instances using an ILS other than Koha.
=> DIS-550: Updated ILS Hours Label and Hid It for non-Koha ILSs

code/web/Drivers/CloudLibraryDriver.php, code/web/release_notes/25.07.00.MD
If libraries do not require a PIN in their Cloud Library, patrons usually only need to use a barcode to sign in the Cloud Library website. When patrons check out Cloud Library records on Aspen, and click “Open In CloudLibrary”, Aspen will redirect patrons to Cloud Library, but see an error` {"error":"Invalid Token"}`
According to Cloud Library support, Aspen should not be passing a password field to {$userInterfaceUrl}/login if the library does not require a PIN in Cloud Library. 
To recreate:
1. Set Cloud Library to do not require a PIN in Cloud Library website 
2. Check out CL records on Aspen
3. Go to “Check out Titles” > Cloud Library > click “Open In CloudLibrary” 
4. See the error {"error":"Invalid Token"}
For {$webPatronUrl}/login endpoint:
1. If Aspen submits a correct barcode and …
=> DIS-1022 Cloud Library fix redirect handling

code/events_indexer/src/com/turning_leaf_technologies/events/SpringshareLibCalIndexer.java, code/web/release_notes/25.07.00.MD
- Fixed an issue where calendar syncing during indexing with Springshare LibCal could randomly stall by adding proper timeouts.
Test Plan: Difficult to test, but the best way would be to either let the events indexer run, or manually run it, to ensure that it still functions accordingly.
=> DIS-1042: Added HTTP Timeouts to LibCal Indexer to Prevent Stalling

code/web/interface/themes/responsive/DataObjectUtil/objectEditForm.tpl, code/web/release_notes/25.07.00.MD
- Resolved an issue where PHP warnings could display when editing the Administrators form.
Test Plan:
1. Navigate to the Administrators page in the admin interface.
2. Find and select the Aspen Admin’s setting. Notice the PHP warnings spanning the page.
- Your IP must have debug mode enabled in the IP Addresses settings to see the warnings.
3. Apply the patch and reload the page. Notice that the PHP warnings have disappeared.
=> DIS-1048: Removed PHP Warnings in Administrators Form

code/web/Drivers/OverDriveDriver.php, code/web/Drivers/PalaceProjectDriver.php, code/web/bootstrap.php, code/web/cron/runScheduledUpdate.php, code/web/index.php, code/web/interface/plugins/function.css.php, code/web/interface/plugins/function.js.php, code/web/interface/themes/responsive/Greenhouse/updateCenter.tpl, code/web/interface/themes/responsive/cssAndJsIncludes.tpl, code/web/interface/themes/responsive/footer_responsive.tpl, code/web/release_notes/25.07.00.MD, code/web/services/API/GreenhouseAPI.php, code/web/services/API/SearchAPI.php, code/web/services/API/SystemAPI.php, code/web/services/Admin/ReleaseNotes.php, code/web/sys/CurlWrapper.php, code/web/sys/LibraryLocation/Library.php, code/web/sys/Updates/ScheduledUpdate.php, code/web/version.json, tests/phpunit/tests/InitializationTests.php, tests/phpunit/tests/services/API/SystemAPITests.php
- Include stage of release within version information in footer.
- alpha during development process
- beta with number during testing period
- blank for full release
- Add a Supplemental.MD file for to display release notes for supplemental changes for a system that are not part of an official release.
- Load version from version.json rather than by scanning release notes.
=> DIS-392 include stage of release within version information

code/web/release_notes/25.07.00.MD, code/web/services/Admin/Administrators.php, code/web/sys/Account/User.php
- Properly allow access to Side Load functionality when masquerading as a user who has access to manage side loads or side load scopes for their home library from a user that has permission to administer all side loads.
- also DIS-1065  Allow setting up ILS users as Administrators based on the ILS Username rather than barcode.
=> DIS-1002 Sideload permissions for masquerade

code/web/interface/themes/responsive/GroupedWork/statusIndicator.tpl, code/web/release_notes/25.07.00.MD
- Corrected status display for records with mixed item availability when "Library Use Only" is the best option.
Test Plan:
1. Navigate to a record with copies that are all checked out except one or more copies mapped to the "Library Use Only" status. Notice that the grouped work's status is incorrectly "On Shelf" or whatever the equivalent is based upon your Indexing Profile's status mapping.
2. Apply the patch and reload the page. Notice that the grouped work's status is now "Library Use Only".
=> DIS-1056: Ensured Correct Status for Mixed Records When Library Use Only Is Top-Ranked

code/web/services/Search/AJAX.php
The initial list of facets were correct in the popup, but searching them resulted in the order being incorrect (most obvious when clearing a search)
=> DIS-990 Correct sorting of facets when searching within popup

code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/css/responsive_base.less
I noticed the fa-desktop icon disappear on the Help Center. It was because I forgot to import the regular stylesheet to go with v5 solid.min.css.
=> DIS-271: QA fix - forgot to include v5 fontawesome.min.css

code/web/CatalogConnection.php, code/web/release_notes/25.07.01.MD, code/web/sys/DB/DataObject.php
- Fixed an issue where patrons' updates to Home Library in My Preferences would not be reflected on first save.
- Clear `_changedFields` after every `update()` to prevent unexpected side effects.
=> DIS-1122: Clear Changed Fields on Update & Fix Updating Home Library

code/web/release_notes/25.08.00.MD, code/web/sys/UserLists/UserList.php
- Add left joins to relevant tables when getting user list entries to get title/author if possible for sorting 
- Update release notes
=> DIS-1091: List Entries that do not have a title set for them do not sort properly

code/web/release_notes/25.08.00.MD, code/web/services/API/UserAPI.php
- Added filter parameter to getPatronReadingHistory to User API to handle searching reading history in LiDA.
=> DIS-1118: Add searchable reading history to LiDA

code/web/Drivers/SirsiDynixROA.php, code/web/release_notes/25.08.00.MD
- Allow checking out titles using Scan and Go to patrons that have fines or fees, but the total fines have not reached the bill threshold for their patron type by providing an override code for the checkout.
=> DIS-1117 Allow self check for users with low fines

code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryEventHandler.java, code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryExporter.java, code/web/release_notes/25.08.00.MD
Currently, the expired Cloud library records can’t be removed in the incremental indexing; they can only be removed in a full update. 
This PR adds the deletion for expired records with the Events endpoint, and refactors the deletion logic for full update and incremental updates.
To Test:
1. Mark a Cloud Library record as expired via Cloud Library 
2. Set Last Update of Changed Records to a time earlier than the expired date.  See the record remaining in the catalog after incremental indexing. 
3. Apply PR
4. Set Last Update of Changed Records to a time earlier than the expired date. See the record gets removed from the catalog
=> DIS-1099 Cloud Library Remove Expired Records During Incremental Updates

code/web/release_notes/25.08.00.MD, code/web/sys/LibraryLocation/Location.php
- Refined pickup location display order so that search results availability now correctly prioritizes pickup locations in the logical sequence: preferred pickup location, alternate pickup location 1, alternate pickup location 2, home library, and so on.
- Resolved an issue where the patron's home library would always be the top result when selecting at what location to place a hold.
Test Plan:
1. Log into a patron account and check your “My Preferences” page. Keep note of your home library and pickup location preferences; set any that might be missing.
2. Search the catalog and click “Place Hold” on an ILS record. Notice that it does not display the pickup location options in the following order: preferred pickup location, alternate location 1, alternate location 2, then home library, …
=> DIS-1027: Fixed Location Display Order in Search Results Availability

code/web/openapi/aspen_openapi.json
Hi, 
This is a draft of creating a documentation for the ListAPI, specifically the getListTitles function, which enables developers to obtain a list of all works and events within a user created list. 
See the list API's getListTitles function in action at https://clevelandreads.com/recommended-reads/ 
Being my first PR and still learning about Aspen, 
I have several questions about OpenAPI formatting and the listAPI: 
**OpenApi formatting questions**
- how to cite items that items may sometimes be a empty string ? 
like  "length": "",
example https://gist.github.com/skora-cpl/76d9b8d0add53ed69d30dbff85a076e3#file-gistfile1-txt-L21
- ~~How to state if a parameter is required or optional ?~~ (see: https://github.com/Aspen-Discovery/aspen-discovery/blob/8defde7966e772e04e9b8ef9001f2f48e9dbab …
=> DIS-1123: Document getListTitles from ListAPI in the API docs

code/web/Drivers/OverDriveDriver.php, code/web/release_notes/25.08.00.MD, code/web/services/MaterialsRequest/RequestsNeedingHolds.php, code/web/sys/DB/DataObject.php
- Resolved an issue where placing holds on OverDrive titles through the Requests Needing Holds interface would fail when record IDs contained source and/or format prefixes.
- Corrected DataObject framework bug where zero values in database queries were incorrectly excluded from count operations due to PHP's loose equality comparison, affecting any interface using `count()` with zero-value conditions.
- Fixed a library scoping issue that allowed staff to see Requests Needing Holds from other Library Systems.
Test Plan:
1. Assuming there are requests needing holds, navigate to the Requests Needing Holds admin interface.
2. Attempt to place a hold on an Overdrive title and notice that it fails with an error.
3. If you have greater than 25 total requests that either need holds or needed …
=> DIS-1151: Fixed Placing Overdrive Holds, Library Scoping, and Pagination on Requests Needing Holds Interface

code/web/cron/purgeSoftDeleted.php, code/web/cron/updateNYTLists.php, code/web/interface/themes/responsive/Admin/cronRunner.tpl, code/web/release_notes/25.08.00.MD, code/web/services/Admin/CronRunner.php, code/web/sys/CronLogEntry.php, code/web/sys/DBMaintenance/version_updates/25.08.00.php, code/web/sys/SystemVariables.php
- Added Purge Soft-Deleted Objects and Update NYT Lists as supported cron processes to be run from the admin interface.
- Added "Log Frequent Cron Jobs" to System Variables and default it to be disabled to prevent frequently run cron jobs from cluttering the cron logs.
Test Plan:
1. Apply the patch.
2. Run the Purge Soft-Deleted Objects and Update NYT Lists from the Cron Runner. Notice they run successfully.
3. Notice that the "Log Frequent Cron Jobs" option on the System Variables page is disabled. There should be no logs of the Load Initial Reading History cron job.
4. If you enable it, notice the logs of the Load Initial Reading History cron job every 5 minutes.
=> DIS-1204: Added 2 Cron Jobs to Cron Runner & Added "Log Frequent Cron Jobs" Setting

code/web/interface/themes/responsive/Admin/cronLog.tpl, code/web/release_notes/25.08.00.MD, code/web/services/API/WorkAPI.php, code/web/services/Admin/CronLog.php
- Allow cron entries to be filtered by searched by name, to only show entries with errors, and allow page size to be set.
=> DIS-1192 allow filtering cron log

code/cron/src/com/turning_leaf_technologies/cron/reading_history/UpdateReadingHistory.java, code/web/Drivers/Koha.php, code/web/release_notes/25.08.00.MD, sites/default/conf/config.cron.ini
- Increased the connection and read timeouts during nightly reading history updates to prevent occasional errors for patron accounts.
- Reduced the Java thread count for nightly reading history updates to slow down the number of API calls within intervals of time.
- Patrons who have not performed any patron operations (e.g., checking out a record) within 23 hours will not have their reading histories updated during the nightly run.
=> DIS-1211: Reduce Reading History Thread Count & Change Koha Reading History Patron Activity

code/web/release_notes/25.08.00.MD, code/web/services/Admin/ReleaseNotes.php
- Allowed 'Q' in the second position of release notes naming.
=> DIS-1212: Allowed 'Q' in the Second Position of Release Notes

code/web/release_notes/25.08.00.MD, code/web/services/MyAccount/SelfReg.php
- Fixed error preventing self-registration form submission when validating USPS address information.
Test Plan:
1. With USPS settings enabled, attempt to submit a self registration. Notice the error.
2. Apply the patch and try again. The submission is successful.
=> DIS-1215: Fixed Unsupported Operand Types During Self Registration with USPS

code/web/release_notes/25.08.00.MD, code/web/sys/UserLists/UserList.php
- Fixed an issue where user lists would continue to display after being hard deleted until they are reindexed.
=> DIS-1076: Set Related Deletion Data for Hard Deleted Lists

code/web/release_notes/25.08.00.MD, code/web/sys/DBMaintenance/version_updates/25.07.00.php
- Fixed issue where multiple themes using images with identical filenames would lose their images during database upgrade to version 25.07.00 and beyond.
Test Plan:
1. Boot up or find an Aspen instance on a version before 25.07.00.
2. Upload the same image to various fields in different Themes.
3. Copy over the original `renameUploadedThemeImages()` function and the entry that runs it into a DB maintenance files (e.g., put in `25.06.00.php`).
4. Run it and notice that only one theme retains reference to the renamed file while the others still reference the old file name that no longer exists.
5. Repeat step 2 and copy the modified version of the function from this PR. Run it and notice that they retain different references to copies of the same image.
=> DIS-1219: Fixed Themes Losing Images If They Reference Same File

code/web/release_notes/25.09.00.MD, code/web/sys/CommunityEngagement/Campaign.php
- Fixed undefined array key warnings in Community Engagement campaigns when sorting milestone progress data by checkout date.
Test Plan: Create campaigns with milestones that would not have a checkout date and notice the errors.
=> DIS-1233: Fixed Undefined Array Key Warning on MyCampaigns Page

code/web/release_notes/25.09.00.MD, code/web/sys/DataObjectUtil.php
- Added missing 'time' property type handler for OneToMany relationships in DataObjectUtil that prevented manual changes to Library Hours from saving.
Test Plan:
1. Edit the Library Hours under the Locations settings.
2. Save the page and notice that the hours do not save.
3. Apply the patch and repeat steps 1-2. Notice that they save.
=> DIS-1260: Fixed Library Hours Not Saving

code/web/release_notes/25.09.00.MD, code/web/services/WebBuilder/SubmitForm.php
- Fixed form resubmission issue where refreshing the results page would create duplicate submissions.
Test Plan:
1. Submit a Custom Form.
2. Refresh the `SubmitForm` page with an ID. Notice that the form has been resubmitted.
3. Apply the patch and repeat steps 1-2. Notice that the form is not resubmitted and an error displays.
=> DIS-1278: Fixed Web Builder Custom Form Duplicate Resubmissions

code/web/interface/themes/responsive/js/aspen/admin.js, code/web/release_notes/25.09.00.MD
- The New Request Summary field is no longer hidden in Library Systems settings when the "ILS Request System" is enabled.
=> DIS-1276: Do Not Hide New Request Summary for ILS Request System

code/web/release_notes/25.09.00.MD, code/web/sys/DB/DataObject.php
- Fixes bug where if the volume number of a series was '03', it could not be changed to '3', because 03 and 3 were considered the same value.  
- I changed the check for whether a property has changed in setProperty in DataObject.php, so it might have unintended consequences, but I was having trouble thinking of any that would be bad -- it should just make it easier to edit fields and fix unwanted zeros and extra spaces.  But I'm happy to find a different, more limited way where it only impacts Administer Series if this seems like a bad idea.
=> DIS-1279: series numbers will not update

code/web/RecordDrivers/GroupedWorkDriver.php, code/web/interface/themes/responsive/GroupedWork/series-summary.tpl, code/web/interface/themes/responsive/GroupedWork/work-details.tpl, code/web/interface/themes/responsive/RecordDrivers/GroupedWork/result.tpl, code/web/release_notes/25.09.00.MD
- If the 'Include in Search' checkbox is unchecked in Administer Series, then don't include that series in the list of series for a grouped record.
=> DIS-1280: better 'Include in Search' checkbox functionality for series

code/hoopla_export/src/com/turning_leaf_technologies/hoopla/HooplaExportMain.java, code/web/release_notes/25.09.00.MD
During the Hoopla metadata extraction happens at 1 am local time, the Hoopla indexer extracts updated instant titles first, then extracts flex titles. A case where Aspen makes API requests by specifying an updated INSTANT title, Hoopla will return updated FLEX titles with `active: false`. Aspen deletes the records. Then, when Aspen makes api requests by specifying an updated FLEX title, Hoopla will return updated FLEX titles again with `active: true`, but Aspen wouldn’t add the records back due to the current existingRecords hashmap. The issue has been reported to Hoopla. But at the same time, Aspen can handle such a case in a better way. 
Difficult to test. After applying the PR, active Flex titles won’t be removed from the catalog during the data extraction.
=> DIS-1252 Delete Entry from Hoopla esistingRecords HashMap

code/web/release_notes/25.09.00.MD, code/web/services/MaterialsRequest/ManageRequests.php
- Fixed Materials Request date filters reverting after navigation because their values did not persist like other filters.
Test Plan:
1. Navigate to Manage Requests page in the admin interface.
2. Apply the date filter.
3. After page reload or after updating a patron’s request, notice that the filter does not persist like the others.
4. Apply the patch and repeat steps 2-3. Notice that the date filter does persist.
=> DIS-1247: Added Stickiness to Manage Requests Date Filters

code/web/release_notes/25.09.00.MD, code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
- Fixed an issue where navigation links "Previous" and "Next" would not display on grouped works beyond the first page of search results.
Test Plan:
1. Navigate to a page beyond page one when searching the catalog.
2. Click on a grouped work and notice that the “Previous” and “Next” links are missing.
3. Apply the patch.
4. Go back to the search results and click a grouped work. Notice that the links are there.
=> DIS-1268: Fixed Navigation Links Missing on Grouped Works Beyond Page One

code/web/Drivers/Koha.php, code/web/release_notes/25.09.00.MD, code/web/services/MyAccount/SelfReg.php, code/web/sys/Utils/SystemUtils.php
Now Aspen does honor to the Koha system preference 'PatronSelfRegistrationAgeRestriction' when submitting a new self registration form.
Before the patch: 
1 - Enable the system preference 'PatronSelfRegistrationAgeRestriction' in Koha
2 - Enable the ILS Based Self Registration
3 - Submit a self registration form with an age bigger than the set in 'PatronSelfRegistrationAgeRestriction'
4 - Aspen approves the form
After the patch:
- Repeat steps 1,2,3
- Aspen throws a message about the invalidation of the entered date of birth and submit nothing.
=> DIS-1227: Check the maximum age for self registration

code/polaris_export/src/com/turning_leaf_technologies/polaris/PolarisExportMain.java, code/web/release_notes/25.09.00.MD
For Polaris, during incremental indexing, Aspen currently handles record and item deletions by checking the /synch/bibs/deleted and /synch/items/deleted endpoints. However, this approach requires libraries to enable Retain Deleted Records in Polaris. If a library keeps that setting turned off, the deleted records/items will not appear in either of those deleted endpoints, nor will they appear in /synch/bibs/MARCXML (since that endpoint only returns updated bib MARC records with DisplayInPAC = true).
To address this, during incremental updates, instead of using /synch/bibs/MARCXML to retrieve updated bibs, Aspen could use the /synch/bibs/updated endpoint. This endpoint returns a list of bib IDs updated within a given timeframe. The updates captured include circulation changes, DisplayInPAC …
=> DIS-1274 Refactor Polaris Indexing

code/web/Action.php, code/web/interface/themes/responsive/Events/calendar.tpl, code/web/interface/themes/responsive/GroupedWork/multipleVariationManifestion.tpl, code/web/interface/themes/responsive/GroupedWork/singleVariationManifestion.tpl, code/web/interface/themes/responsive/GroupedWork/title-rating.tpl, code/web/interface/themes/responsive/MyAccount/list-print-options.tpl, code/web/interface/themes/responsive/MyAccount/list.tpl, code/web/interface/themes/responsive/RecordDrivers/CourseReserve/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/EBSCO/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/EBSCOhost/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/Events/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/GroupedWork/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/List/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/OpenArchives/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/Person/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/Series/listEntry.tpl, code/web/interface/themes/responsive/RecordDrivers/Summon/listEntry.tpl, code/web/interface/themes/responsive/css/calendar.less, code/web/interface/themes/responsive/css/main.css, code/web/interface/themes/responsive/css/print.css, code/web/interface/themes/responsive/css/print.less, code/web/interface/themes/responsive/css/responsive_base.css, code/web/interface/themes/responsive/js/aspen.js, code/web/interface/themes/responsive/js/aspen/lists.js, code/web/interface/themes/responsive/print-layout.tpl, code/web/release_notes/25.09.00.MD, code/web/services/MyAccount/AJAX.php, code/web/services/MyAccount/MyList.php, code/web/sys/UserLists/UserList.php
- added print interface option that uses an alternate layout template to reduce header/footer elements
- update print options button in My List to open a modal to prompt the user what elements they'd like to print: library name, library logo, list author, list description, list entry covers/series/formats/descriptions/notes/holdings/rating
- when using the print interface, always hide: Show Editions button, availability info, waitlist info, toolbars
=> DIS-1282: Add print options dialog for lists

code/web/CatalogConnection.php, code/web/Drivers/AbstractIlsDriver.php, code/web/Drivers/Koha.php, code/web/Drivers/SirsiDynixROA.php, code/web/interface/themes/responsive/ILS/selfCheckTester.tpl, code/web/release_notes/25.09.00.MD, code/web/services/API/UserAPI.php, code/web/services/AspenLiDA/SelfCheckCompletionMessages.php, code/web/services/ILS/SelfCheckTester.php, code/web/sys/Account/User.php, code/web/sys/AspenLiDA/SelfCheckCompletionMessage.php, code/web/sys/DBMaintenance/version_updates/25.09.00.php, code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php, code/web/sys/SearchObject/GroupedWorkSearcher2.php, code/web/sys/SolrConnector/GroupedWorksSolrConnector.php, code/web/sys/SolrConnector/GroupedWorksSolrConnector2.php, code/web/sys/SolrConnector/Solr.php
- Allow Self Check Messages to be configured for display after titles have been checked out from LiDA. Anyone with permission to administer Self Check Settings can update these.
- Return completion message at the end of successful Scan and Go operations.
=> DIS-1275 Allow Messages to be displayed after Self Check

code/web/release_notes/25.09.00.MD, code/web/sys/MaterialsRequests/MaterialsRequestFormat.php
- Modified the Format, Format Label, and Author Label fields to be required under the Formats of Materials that can be Requested table, as they are necessary functionality.
Test Plan:
1. Apply the patch.
2. Add a new row to the Formats of Materials that can be Requested table under Library Systems.
3. Try to save and notice that the fields are required.
=> DIS-1244: Make Certain Material Request Format Fields Required

code/web/release_notes/25.09.00.MD, code/web/services/MyAccount/AJAX.php, code/web/sys/Account/User.php
- Add the option to sort pending, frozen holds by "Reactivation Date".
Test Plan:
1. Log into a patron account.
2. Freeze a couple of Pending Holds.
3. Sort them by "Reactivation Date". Notice that frozen holds that will be reactivated with the earliest reactivation dates are at the top.
=> DIS-1255: Added Sorting by Frozen Holds

code/web/release_notes/25.09.00.MD, code/web/sys/SearchObject/BaseSearcher.php
- Corrected search history timestamps to display the current date instead of future dates.
Test Plan:
1. Perform a search in the catalog.
2. Save the search.
3. Navigate to Search History. Observe the incorrect timestamp for the saved search.
4. Apply the patch and repeat steps 1-3. Notice that the timestamp is correct.
=> DIS-1287: Fixed Saved Searches Timestamps

code/web/release_notes/25.09.00.MD, code/web/sys/Covers/DefaultCoverImageBuilder.php
- Fixed an issue where records without authors would have missing default covers (e.g., Open Archives Collections).
Test Plan:
1. Navigate to the Open Archives Collection search. Notice that covers may be missing if the record has no author.
2. Apply the patch and reload the page. Notice that the covers generate.
=> DIS-1299: Fixed Default Covers Without Authors Not Generating

code/web/interface/themes/responsive/RecordDrivers/GroupedWork/listEntry.tpl, code/web/release_notes/25.09.00.MD
- Fixed positioning of action buttons in list entries when titles lack summary descriptions.
Test Plan:
1. Navigate to a list with an entry that has no description. Notice that the action buttons are inline with the record manifestation(s).
2. Apply the patch and reload the page. Notice that the buttons correctly display below the manifestation(s).
=> DIS-1341: Fixed List Entry Buttons Misalignment When No Description Exists

code/web/release_notes/25.10.00.MD, code/web/sys/Utils/SystemUtils.php
Some libraries with valid credentials on the old USPS developer site couldn’t use the address validation function on the self-reg form,  see error `The address you entered does not appear to be valid `even when entering the valid address
USPS has moved its website from [Old site: developer.usps.com](http://developer.usps.com/) to [New site: developers.usps.com (added "s" after "developer")](http://developers.usps.com/) , the new developer API portal: https://www.usps.com/business/web-tools-apis/. We should updatet the USPS API URL from api.usps.com to apis.usps.com according to this USPS Github https://github.com/USPS/api-examples?tab=readme-ov-file
To Test: 
1. Libraries with valid credentials on the old USPS developer site see the error `The address you entered does not appear to be …
=> DIS-1323: Update USPS URL

code/web/release_notes/25.10.00.MD, code/web/sys/Grouping/Record.php
- Corrected an issue where a locally owned and available item at a search location would incorrectly display as "Checked Out/Available Elsewhere".
=> DIS-1297: Ensure Locally Owned and Available Items Show as Available at Search Location

code/web/Drivers/Koha.php, code/web/release_notes/25.10.00.MD
- Fixed an issue where password validation would be performed during self registration even though the field was not required.
=> DIS-922: Fixed Password Validation for Non-Mandatory Password During Koha Self-Reg

code/web/Drivers/Koha.php, code/web/Drivers/Polaris.php, code/web/release_notes/25.10.00.MD
Small changes in both Koha.php and Polaris.php to show renewals remaining for checked out items
Requires additional testing
=> DIS-1403: Show renewals remaining in addition to total renewals

code/web/interface/themes/responsive/Search/home.tpl, code/web/release_notes/25.10.00.MD, code/web/services/Browse/AJAX.php, code/web/services/Search/Home.php
- With "Use Accessible Layout" enabled for a Theme, browse categories on the home page now generate proper search URLs instead of placeholder links.
Test Plan:
1. Enable Accessible Layout in the Themes settings for a catalog.
2. Navigate to the home page to view browse categories.
3. Click on the main browse category search link that has subcategories. Notice that it does not navigate you anywhere.
4. Apply the patch, reload the page, and click the same search link. Notice that it navigates you to the appropriate results.
=> DIS-1301: Fixed Search URL for Accessible Browse Categories
