Aspen-Discovery/aspen-discovery

.gitignore

Updates .gitignore to exclude local .idea files

---

code/web/interface/themes/responsive/DataObjectUtil/password.tpl
code/web/interface/themes/responsive/DataObjectUtil/property.tpl
code/web/interface/themes/responsive/MyAccount/menu.tpl
code/web/interface/themes/responsive/MyAccount/registerRosenLevelUP.tpl
code/web/interface/themes/responsive/Rosen/breadcrumbs.tpl
code/web/manual/Rosen-LevelUP.MD
code/web/manual/table_of_contents.MD
code/web/services/Admin/DBMaintenance.php
code/web/services/MyAccount/RegisterRosenLevelUP.php
code/web/services/Rosen/RosenLevelUPSettings.php
code/web/sys/Interface.php
code/web/sys/Rosen/RosenLevelUPSetting.php
sites/nashville.aspenlocal/lang/en.ini
sites/nashville.production/lang/en.ini

@mdnoble73 let's play everyone's favorite game show "How Many Antipatterns Can You Find?"
Rather, let's have code review!

20.11.00 rosen register

---

code/web/interface/themes/responsive/DataObjectUtil/password.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/base.js
code/web/services/MyAccount/RegisterRosenLevelUP.php
code/web/sys/DataObjectUtil.php

Corrects passwordRepeat

---

sites/nashville.production/nashville.production.sh

https://trello.com/c/pY2sjMQG/1-sideloads-convert-pika-sideloads#comment-5f56bb70d9fea6671a7cda70

Increases Nashville solr java vm to 24g

---

code/web/Drivers/CarlX.php

Fix fix placing hold with remember pickup location on

---

code/web/Drivers/CarlX.php
code/web/interface/themes/responsive/Report/holdsReport.tpl

https://trello.com/c/HGPj4MpX/950-create-custom-fill-list-for-schools-pulling-holds#comment-5f94ea9a99a5a28e071aeda1

Updates holds report for CarlX

---

code/web/interface/themes/responsive/Search/horizontal-searchbox.tpl

Makes search source dropdown options translatable

---

code/web/interface/themes/responsive/MyAccount/ajax-login.tpl
code/web/interface/themes/responsive/MyAccount/login.tpl
code/web/interface/themes/responsive/header-menu.tpl

https://trello.com/c/Yjt0LuRC
https://trello.com/c/13AhStOk

Makes login and custom library menu links translatable

---

code/web/interface/themes/responsive/MyAccount/ajax-login.tpl
code/web/interface/themes/responsive/header-menu.tpl

Makes usernamelabel and passwordlabel translatable

---

code/web/Drivers/CarlX.php

Fixes diacritics in Student Reports and other ad hoc Oracle queries

---

code/web/interface/themes/responsive/css/nashville-collectionSpotlights.css
code/web/services/Search/AJAX.php

20.15.00 nashville collection spotlights

---

code/web/services/MyAccount/RegisterRosenLevelUP.php
code/web/services/Report/HoldsReport.php

https://trello.com/c/YWNjWV1m/352-data-migration-and-other-go-live#comment-5fb171cff5466975c603cd5c

Returns nav to Rosen and Holds report

---

code/web/interface/themes/responsive/Emails/rosen-levelup.tpl
code/web/services/MyAccount/RegisterRosenLevelUP.php

Emails registering parent following a successful registration.

Sends Rosen LevelUP registration confirmation email

---

code/web/sys/SIP2.php

Fixes NNA dates for thawed holds

---

sites/nashville.production/conf/crontab_settings.txt

https://trello.com/c/dzubwczp
https://ticket.bywatersolutions.com/Ticket/Display.html?id=75836

Updates Nashville crontab_settings.txt

---

.gitignore
.idea/aspen-discovery.iml
code/web/Drivers/CarlX.php
code/web/Drivers/Nashville.php
code/web/interface/themes/responsive/MyAccount/fines.tpl
code/web/interface/themes/responsive/MyAccount/msbPayments.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/services/API/FineAPI.php
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Fines.php
code/web/sys/Account/UserPayment.php
code/web/sys/DBMaintenance/user_updates.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/SIP2.php

21.02.00 nashville online payments

---

code/web/services/MyAccount/AJAX.php

https://github.com/mdnoble73/aspen-discovery/pull/198#pullrequestreview-580853328

Nashville Online Payments remove obsolete comment

---

code/web/services/MyAccount/RegisterRosenLevelUP.php

+ Fixes LevelUP registration form warning https://trello.com/c/PgghaMO4

Updates Rosen LevelUP registration form

---

code/web/Drivers/CarlX.php
code/web/Drivers/Nashville.php

https://trello.com/c/4cubEGse/
+ fixes matching Collection Agency fee
+ fixes assigning Collection Agency fees to NPL, not MNPS https://trello.com/c/4cubEGse/42-testing#comment-6021b161b3d2426e7ebd7744
+ fixes calculating Fine outstanding amount https://trello.com/c/4cubEGse/42-testing#comment-6021b189e055124e1369339d

Updates Nashville online payments

---

code/web/Drivers/CarlX.php
code/web/Drivers/Nashville.php

https://trello.com/c/KnlXnRBY/199-integrate-credit-card-processor#comment-60287245368ef26eb591a086

Nashville online payments: Fixes previous partial payments on Lost items

---

code/web/interface/themes/responsive/OpenArchives/openArchivesLog.tpl
code/web/services/Admin/AJAX.php

https://ticket.bywatersolutions.com/SelfService/Display.html?id=78718

Fixes Open Archives indexing log Show Notes

---

code/web/Drivers/Nashville.php
code/web/interface/themes/responsive/MyAccount/expirationFinesNotice.tpl
code/web/interface/themes/responsive/MyAccount/fines.tpl
code/web/interface/themes/responsive/MyAccount/msbPayments.tpl
code/web/services/API/FineAPI.php
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Fines.php
code/web/sys/DBMaintenance/library_location_updates.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/SIP2.php
install/aspen.sql

improves messaging to patron and improves logging

21.03.00 nashville online payments

---

code/web/Drivers/CarlX.php

Fixes MNPS school holds report
https://trello.com/c/cU2qWgXT

Updates CarlX Driver for CarlX 9.6.8.0

---

code/web/services/Report/StudentBarcodes.php
code/web/services/Report/StudentReport.php

Fixes MNPS Library Services permissions for Circ Reports

---

code/web/sys/DBMaintenance/indexing_updates.php
code/web/sys/Indexing/SideLoadScope.php

Embiggens sideload scope URL match and replace fields

---

code/web/interface/themes/responsive/MaterialsRequest/new.tpl
code/web/interface/themes/responsive/MaterialsRequest/request-form-fields.tpl
code/web/interface/themes/responsive/MyAccount/account-sidebar.tpl

https://trello.com/c/menRy5DW
@mdnoble73 The Title and Author labels need more work in ajax to make them translatable

Makes Materials Requests form translatable

---

code/web/Drivers/CarlX.php

Fixes Nashville MNPS 18+ not appearing in report

---

code/web/Drivers/FOLIO.php
code/web/sys/CurlWrapper.php

Creates a FOLIO ILS Driver based on work done with VuFind
Does initial account connection work, but does not interact
with the Inventory yet.
Also adds a function, getHeaderSize, to CurlWrapper to support
FOLIO connections

Initial FOLIO Driver

---

code/web/interface/themes/responsive/Report/holdsReport.tpl

Changes Nashville school hold slips

---

code/web/sys/SearchObject/EbscoEdsSearcher.php

Fix for EDS limiter options. Previously limiters were not being applied.

Fix limiters for EDS Search

---

sites/nashville.production/httpd-nashville.production.conf

https://ticket.bywatersolutions.com/SelfService/Display.html?id=91340

Fixes web builder initial setup for Nashville

---

sites/nashville.production/conf/groupedWorksFacets.ini

... to ensure all schools are viewable in the Available At facet.
https://ticket.bywatersolutions.com/Ticket/Display.html?id=89938

Embiggens Nashville facet lists

---

code/web/RecordDrivers/MarcRecordDriver.php

https://ticket.bywatersolutions.com/SelfService/Update.html?id=92524

Adds archival material dates to title

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
code/web/release_notes/22.02.00.MD

https://ticket.bywatersolutions.com/SelfService/Display.html?id=92524

Indexes titles of archival materials with dates

---

code/web/sys/DBMaintenance/version_updates/22.03.00.php

Increase regex column length for zip codes used on self registration form (ticket 93847)

Increase validSelfRegistrationZipCodes Length

---

code/web/sys/DBMaintenance/version_updates/22.03.00.php

allow zip regex to be 500 characters

Increase varchar to 500

---

code/web/manual/Library-Systems.MD
code/web/manual/System-Messages.MD
code/web/manual/table_of_contents.MD

Hi, my first commit! I will be happy to add to the manual in places if it is helpful.

Some amends/additions to the manual

---

code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl

As per email with Mark, expanded config options for TinyMCE to allow for more robust editing.

Tiny MCE Config Changes

---

code/web/interface/themes/responsive/Report/studentReport.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/globals.js
code/web/interface/themes/responsive/js/aspen/responsive.js

Fixes circulation reports Print Pages in Chrome

---

code/web/Drivers/Nashville.php

Fixes Fine API response for MSB confirmation

---

code/web/sys/ExploreMore.php

https://ticket.bywatersolutions.com/SelfService/Display.html?id=98666

Makes Explore More box labels translatable

---

code/web/services/SideLoads/UploadMarc.php
install/php.ini

I added an extra space so it would look like i changed something so that the 75M file limit would go through. i'm sure there's a more elegant way to do this, so let me know...

max file size limit

---

code/web/interface/themes/responsive/DataObjectUtil/objectEditForm.tpl
code/web/interface/themes/responsive/css-rtl/layout.less
code/web/interface/themes/responsive/css-rtl/main.css
code/web/interface/themes/responsive/css/layout.less
code/web/interface/themes/responsive/css/main.css

Adds a floating save button to editing pages for administrators.

Floating Save

---

code/web/Drivers/Nashville.php

https://trello.com/c/Fi2uzzZE/2317-some-msb-transactions-may-not-update-carlx#comment-62f673b5a8c9b566c1783318

Udates MSB payment error logging

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/IlsRecordProcessor.java
code/web/sys/Theming/Theme.php

Quick patch in logic for Laramie collection indexing (Ticket 101757)

Quick Patch for Ticket 101757

---

code/web/Drivers/Koha.php
code/web/Drivers/Polaris.php
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js

Actually fixed the payment success message translation :') Also fixed a small typo in Koha.php

Payment Message Translation Round 2

---

code/web/sys/DBMaintenance/version_updates/22.09.00.php

change REGEXP '.*[\s]+$' to LIKE '% %'

Small update to SQL query

---

install/samlsso_installer_centos.sh

Adds a CentOS equivalent of samlsso_installer_debian.sh

PR response - samlsso_installer_centos.sh

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/IlsRecordProcessor.java
code/web/sys/DBMaintenance/version_updates/22.09.00.php

Reindex grouped works with ID ending in -

Reindex grouped works with ID ending in -

---

code/web/interface/themes/responsive/Record/hold-popup.tpl

https://ticket.bywatersolutions.com/SelfService/Update.html?id=101621

Fixes "Log me out after requesting the item"

---

install/saml20-idp-remote.php
install/samlsso_installer_centos.sh
install/samlsso_installer_debian.sh

This replaces the one provided by SimpleSAML.
Missed from the original install script!

Add missing copy of saml20-idp-remote.php

---

sites/template.linux/httpd-{sitename}.conf
sites/template.windows/httpd-{sitename}.conf

This got missed in the original commit for the SSO work!
Sorry Mark, having to set up SSO from scratch on this new server is revealing a few things that got missed in the SSO install process!

Add block to Apache config template

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
code/web/release_notes/22.10.00.MD

The following details the updates on what formats are being checked where: 710: Playaway Launchpad, Playaway Bookpack, PLayaway Wonderbook 250a: Playaway, Playaway View, Wonderbook, GameCube, Nintendo Switch, Book Club Kit, Vox 300a:Playaway View, Wonderbook
538: 4k ultra hd blu-ray (will need to figure out combo still) Also added check for wonderbooks in filterPrintFormats()

Format Updates (first chunk)

---

code/web/Drivers/CarlX.php
code/web/Drivers/Nashville.php

https://trello.com/c/Fi2uzzZE/2317-some-msb-transactions-may-not-update-carlx#comment-632b6000bc7db300aef897ed

Attempt to improve MSB flow by checking for changed patronid

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
code/web/release_notes/22.10.00.MD

Add check for board books in 650a and 655a. Updated release notes

Check for board books

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java
sites/default/translation_maps/format_boost_map.properties
sites/default/translation_maps/format_category_map.properties
sites/default/translation_maps/format_map.properties

Added printFormats.remove/add for multiple formats: Playaway Launchpad, Playaway Bookpack, PlayawayView, 4k Blu-ray, 4K/Blu-ray, Pop-Up Book, and Board Book Added format mapping for these formats to format_boost_map.properties, format_category_map.properties, and format_map.properties

Format Things

---

code/web/interface/themes/responsive/css-rtl/layout.less
code/web/interface/themes/responsive/css-rtl/main.css
code/web/interface/themes/responsive/css/layout.less
code/web/interface/themes/responsive/css/main.css

Fixes issue when if a browse-category-column had too few items, alignment would be off

Grid Display Fix

---

code/java_shared_libraries/src/com/turning_leaf_technologies/strings/AspenStringUtils.java
code/reindexer/src/com/turning_leaf_technologies/reindexer/AbstractGroupedWorkSolr.java

Remove punctuation in the short title so the display title does not have " :: "

Title Display

---

code/web/RecordDrivers/CloudLibraryRecordDriver.php
code/web/RecordDrivers/GroupedWorkDriver.php
code/web/RecordDrivers/MarcRecordDriver.php
code/web/RecordDrivers/OverDriveRecordDriver.php
code/web/interface/themes/responsive/Record/invalidRecord.tpl

Loading staff view now is translatable

---

code/web/CatalogConnection.php
code/web/RecordDrivers/GroupedWorkDriver.php
code/web/RecordDrivers/IndexRecordDriver.php
code/web/interface/themes/responsive/MyAccount/list.tpl
code/web/interface/themes/responsive/js/aspen/lists.js
code/web/services/MaterialsRequest/ManageRequests.php
code/web/services/MyAccount/AJAX.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
code/web/sys/UserLists/UserList.php

Does not yet output User Lists > Location and Call Number
Although the name is different, this branch is currently based on 22.11.00

22.10.00 excel

---

code/web/interface/themes/responsive/adminMessages.tpl

maintenance database message is translatable

---

code/web/release_notes/22.11.00.MD

Release notes

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/AbstractGroupedWorkSolr.java
code/web/interface/themes/responsive/MyAccount/account-sidebar.tpl
code/web/release_notes/22.11.00.MD

Fixes issue where : were at the end of titles that did not have subtitles

LiDA Title Display Fix

---

code/web/services/MaterialsRequest/ManageRequests.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
code/web/sys/UserLists/UserList.php

Full error:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error106240_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\jstaub\Downloads\UserList.xlsx'</summary><additionalInfo><info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info></additionalInfo></recoveryLog>

Excel export: fixes "Errors were detected in file"

---

code/web/Drivers/Koha.php

Fixed tooltip on contact info screen

---

code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/22.11.01.MD

Updates Symphony patron fields to check for separate City and State and combined City/State

City/State Fields

---

code/web/Drivers/VdxDriver.php
code/web/release_notes/22.11.01.MD

Updated code style to use tabs

VDX Change

---

code/web/CatalogConnection.php
code/web/Drivers/Koha.php
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/interface/themes/responsive/layout.tpl
code/web/release_notes/22.12.00.MD
code/web/services/API/UserAPI.php
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/User.php
code/web/sys/Account/UserLink.php
code/web/sys/Account/UserMessage.php
code/web/sys/DBMaintenance/version_updates/22.12.00.php

Remove old functionality for disabling account linking upon pin reset 
Update messaging for when accounts are linked to

Update to User Link

---

code/web/interface/themes/responsive/layout.tpl

Fixes user messages not closing until after page refresh

Fix for User Messages

---

code/web/interface/themes/responsive/MyAccount/home.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/admin.js
code/web/services/Admin/GroupedWorkDisplay.php
code/web/sys/Grouping/GroupedWorkDisplaySetting.php

Adds a blurb below "Your Account" on /MyAccount/Home that states what accounts are linked to you as managing accounts (if any)

Linked Account Info Blurb

---

code/web/interface/themes/responsive/MyAccount/expirationFinesNotice.tpl
code/web/sys/DBMaintenance/version_updates/22.12.00.php

This will actually fix the fine payment translation issue. sorry for the multiple commits!

Translation Fix

---

code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/admin.js
code/web/release_notes/23.01.00.MD
code/web/services/Admin/AJAX.php
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/PType.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.01.00.php

Added ability to assign account linking permissions by patron type

Linked Accounts Permissions

---

code/web/interface/themes/responsive/MyAccount/home.tpl
code/web/release_notes/23.01.00.MD
code/web/services/Record/AJAX.php
code/web/sys/Account/PType.php

Added space between the "." and "Learn" on accounts home page where linked accounts are shown 
Changed function for if accountLinkingSetting == 3

Small Changes

---

code/web/interface/themes/responsive/MyAccount/home.tpl
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/User.php

Fix spacing issue in display of linked accounts on /Account/Home 
Fix issue where linking was not honoring pType setting

Account Linking Fixes

---

code/web/services/MyAccount/AJAX.php

Update messaging for account linking denials

Update Linking Messaging 

---

code/web/interface/themes/responsive/Enrichment/novelistApiData.tpl
code/web/release_notes/23.01.00.MD
code/web/services/Enrichment/NovelistAPIData.php
code/web/sys/Account/User.php
code/web/sys/Enrichment/Novelist3.php

Creates a test page to see what information we get from Novelist for an ISBN

Novelist Test Page

---

code/web/services/Admin/ObjectEditor.php
code/web/services/Development/Tasks.php
code/web/sys/DataObjectUtil.php

https://docs.google.com/spreadsheets/d/1oK90a1hhV4njGwAZIQ5kFUWIo1EmVcg7k1STS2uIkes/edit

php8 fix getFormContentType

---

code/web/services/Admin/ACISpeedpaySettings.php
code/web/services/Admin/PayPalSettings.php
code/web/services/Admin/WorldPaySettings.php
code/web/services/Admin/XpressPaySettings.php

Opens the ecommerce accordion instead of primary configuration

Fixes ecommerce admin nav

---

code/web/services/MaterialsRequest/ManageRequests.php
code/web/services/MyAccount/AJAX.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
code/web/sys/SearchObject/GenealogySearcher.php
code/web/sys/UserLists/UserList.php

Updates the following files to use CSV export instead of excel: -UserList.php
-AbstractGroupedWorkSearcher.php
-GenealogySearcher.php
-ManageRequests.php
-MyAccount/AJAX.php
Will update release notes once all are finished

Excel to CSV

---

code/web/services/MaterialsRequest/Dashboard.php
code/web/services/MaterialsRequest/Graph.php
code/web/services/MaterialsRequest/SummaryReport.php

Fixed an error for $header[] = 'Date';

Last CSV Thing (for now...)

---

code/web/services/MaterialsRequest/SummaryReport.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
code/web/sys/UserLists/UserList.php

- Fix AbstractGroupedWorkSearcher.php to handle OverDrive better, especially their eMagazines that do not have publish dates 
- Fix UserList.php to handle records on lists that are no longer available in the library catalog and don't have a valid grouped work 
- Fix SummaryReport.php so you don't get repeat data and the correct status data is pulled

CSV Things

---

code/web/services/MaterialsRequest/Dashboard.php
code/web/services/MaterialsRequest/Graph.php
code/web/sys/UserLists/UserList.php

- Fixes to the export for materials request dashboard/graphs
- Fixes to the user list export to skip items that don't exist in the array

CSV stands for "Cool Stuff, Verily!"

---

code/web/interface/themes/responsive/MaterialsRequest/dashboard.tpl
code/web/interface/themes/responsive/MaterialsRequest/graph.tpl
code/web/services/MaterialsRequest/Dashboard.php
code/web/services/MaterialsRequest/Graph.php
code/web/sys/Enrichment/Novelist3.php
code/web/sys/UserLists/UserList.php

Removed location loop for materials request dashboard and graphs
Updated userList csv export
Updated Novelist API Info retrieval to retrieve all info if there's no series info (fix for white screen when searching isbns with no series info)

CSV Export Fixes and Novelist API Info Fix 

---

code/web/sys/Enrichment/Novelist3.php

Novelist API 

---

code/web/Action.php
code/web/interface/themes/responsive/MyAccount/account-sidebar.tpl

Fixes div for materials request submission page when user is staff

Materials Request Submit Page 

---

code/web/interface/themes/responsive/MyAccount/linkedAccounts.tpl
code/web/services/MyAccount/LinkedAccounts.php

Hide Account Linking settings based on setting for the user's PType

Account Linking

---

code/java_shared_libraries/src/com/turning_leaf_technologies/indexing/InclusionRule.java
code/java_shared_libraries/src/com/turning_leaf_technologies/indexing/Scope.java
code/reindexer/src/com/turning_leaf_technologies/reindexer/IlsRecordProcessor.java

Updates isItemOwnedByScope to properly include/exclude owned items

Inclusion/Exclusion Rules for Owned Records

---

code/java_shared_libraries/src/com/turning_leaf_technologies/indexing/InclusionRule.java

Handle cases where shelf location is empty properly
If shelf location is empty and we are only including JUV - empty shelf locations will be excluded
If shelf location is empty and we are only excluding JUV - empty shelf locations will be included

Shelf Location Inclusion/Exclusion 

---

code/java_shared_libraries/src/com/turning_leaf_technologies/indexing/InclusionRule.java

- Properly handle including/excluding collection codes with empty strings or null values 
- Also updated shelf location to check for null just in case we do come across null values for that

Collection Code Inclusion/Exclusion Fix

---

code/web/services/MyAccount/AJAX.php

Fix for the Checkouts.CSV export to show renew count - also fixes showing linked users & waitlist (not yet reported)

Export CheckOuts Fix

---

code/web/release_notes/23.02.00.MD
code/web/sys/SearchObject/EventsSearcher.php
code/web/sys/SearchObject/ListsSearcher.php
code/web/sys/SearchObject/WebsitesSearcher.php

- Allows sorting alphabetically for list searches, event searches, and website searches 

Fix for title sort

---

code/web/sys/DBMaintenance/version_updates/23.02.00.php

Sets Include eContent and Include Items On Order to true for owned records

Include eContent and Items On Order

---

code/web/Drivers/Evergreen.php

Missing allowStaffToken param.
Signed-off-by: Jason Boyer <jboyer@equinoxOLI.org>

Fix getAPIAuthToken call

---

code/web/RecordDrivers/GroupedWorkDriver.php
code/web/sys/Grouping/Record.php

Separates items with different formats on a bib in grouped work display. Places bib level hold.

Multiple Formats on Bib part I 

---

code/web/RecordDrivers/MarcRecordDriver.php
code/web/interface/themes/responsive/Record/full-record.tpl
code/web/interface/themes/responsive/Record/multipleVariationDisplay.tpl
code/web/interface/themes/responsive/Record/view-title-details.tpl

- Check for mulitple variations on a record
- If there are multiple variations, get record for each variation 
- Display each variation on the bib page
- Added new tpl for multiple variation dislplay of ILS items

Display all formats for a bib

---

code/web/services/Record/AJAX.php
code/web/sys/Grouping/Record.php

Check bibs with multiple variation formats for a format that allows holds and use that to place a bib level hold

Multiple Variations on a Bib Holds

---

code/web/interface/themes/responsive/GroupedWork/singleVariationManifestion.tpl
code/web/interface/themes/responsive/Record/multipleVariationDisplay.tpl
code/web/sys/Grouping/Manifestation.php

Hide action button if format is not holdable

Multiple Variations on a Bib

---

code/koha_export/src/com/turning_leaf_technologies/koha_export/KohaExportMain.java
code/web/release_notes/23.03.00.MD

- Updated updatePatronTypes() function in KohaExportMain.java to update 'canSuggestMaterials' by pType based on info from Koha DB 
- Updated Release notes

22.11 Update

---

code/web/interface/themes/responsive/CollectionSpotlight/singleWithNextTitleSpotlight.tpl
code/web/interface/themes/responsive/CollectionSpotlight/textCollectionSpotlight.tpl

Fix for smarty error:
Warning: Undefined array key "showCollectionSpotlightTitle" in /usr/local/aspen-discovery/tmp/smarty/compile/1b28a7ea9daff6766d533b62cd8dd33ef6f8c43d_0.file.textCollectionSpotlight.tpl.php on line 28
Warning: Attempt to read property "value" on null in /usr/local/aspen-discovery/tmp/smarty/compile/1b28a7ea9daff6766d533b62cd8dd33ef6f8c43d_0.file.textCollectionSpotlight.tpl.php on line 28
Also added fix for singleWithNextTItleSpotlight.tpl

Smarty Fix

---

code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/index.php
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/services/LibraryMarket/Event.php

Update redirect for LM calendar events to  an Aspen hosted page
New files added:
\LibraryMarket\event.tpl
\LibraryMarket\Event.php
Added new functions to fetch info in LibraryCalendarEventRecordDriver.php
Also fixed a small php error in SpringshareLibCalEventRecordDriver.php where age_group sometimes didn't exist

Library Market Page

---

code/web/interface/themes/responsive/MyAccount/editListTitle.tpl

Fix for smarty error when editing position on user defined lists

Smarty Error

---

code/web/services/Events/CommunicoSettings.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.04.00.php
code/web/sys/Events/CommunicoEvent.php
code/web/sys/Events/CommunicoSetting.php

Added files:
\services\Events\CommunicoSettings.php
\sys\Events\CommunicoEvent.php
\sys\Events\CommunicoSetting.php
Updated 23.04.00.php to add communico settings, permissions, and event info to the db
Updated \Account\User.php to add Communico Settings as an admin action

Create Communico Settings and Permissions

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoEvent.java
code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java
code/events_indexer/src/com/turning_leaf_technologies/events/EventsIndexerMain.java

Indexing Communico events
Added files:
CommunicoEvent.java
CommunicoIndexer.java
Altered Files:
Added Communico indexing statement to EventsIndexerMain.java

Communico Indexing

---

code/web/interface/themes/responsive/Search/list-none.tpl
code/web/interface/themes/responsive/Search/list.tpl

Display "Didn't find it?" link at all times unless $showMaterialsRequest is false (regardless of user being logged in/allowed to submit requests)

Show "Didn't find it?" Link

---

code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/index.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/services/Communico/Event.php
code/web/sys/Covers/BookCoverProcessor.php
code/web/sys/SearchObject/EventsSearcher.php

Add register button to results page for library market events

Register Button for LM

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java
code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl

- Some small updates for the information displayed for Communico Events (short vs full description)
- Added searchTags field as the categories for events

Communico Updates

---

code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/interface/themes/responsive/Springshare/event.tpl

Add line breaks between "register/view on ____" and description for all events integrations

Line Breaks

---

code/web/interface/themes/responsive/Record/evergreenHoldNotifications.tpl

Correct a template typo to correctly pre-select users' SMS carrier.

Fix Evergreen SMS template

---

code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Events/result-tools-horizontal.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/listEntry.tpl
code/web/release_notes/23.04.00.MD
code/web/services/MyAccount/AJAX.php
code/web/sys/DBMaintenance/version_updates/23.04.00.php
code/web/sys/UserLists/UserListEntry.php

Adds ability to save events to lists for all event integrations
Added Files:
--RecordDrivers\Events\listEntry.tpl
Updated Files:
--Events\result-tools-horizontal.tpl
--Communico, Springshare, & Library Market record drivers 
--MyAccount\AJAX.php & UserListEntry.php - added source for Events 
--23.04.00.php - Increased size for sourceId for list entries (library market source ids are long)

Event Lists

---

code/web/Action.php
code/web/interface/themes/responsive/Events/result-tools-horizontal.tpl
code/web/interface/themes/responsive/MyAccount/account-sidebar.tpl
code/web/interface/themes/responsive/MyAccount/myEvents.tpl
code/web/interface/themes/responsive/MyAccount/myEventsList.tpl
code/web/interface/themes/responsive/account-menu.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/release_notes/23.04.00.MD
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/MyEvents.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.04.00.php
code/web/sys/Events/UserEventsEntry.php
code/web/sys/Interface.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/Pager.php

Added ability to save events to a "My Events" page for all event integrations
Added Files:
--responsive\MyAccount\myEvents.tpl
--responsive\MyAccount\myEventsList.tpl
--services\MyAccount\myEvents.php
--Events\UserEventsEntry.php
File Updates:
Updated Pager.php to handle options['fileName']
Added table for user_events_entry in 23.04.00.MD
Added check for event settings so only those with events integrations will see the "My Events" page  (Interface.php, Action.php, and Library.php)
Added functions for saving, deleting, and fetching events (.js and ajax files)

Saved Events

---

code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/Events/result-tools-horizontal.tpl
code/web/interface/themes/responsive/MyAccount/myEvents.tpl
code/web/interface/themes/responsive/MyAccount/myEventsList.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/services/MyAccount/AJAX.php

- Change "Add to My Events" to "Add to Your Events"
- Fix display of Your Events page so "loading events" and "you have no saved events" is on a different line than the dropdown
- Change "title" added to list successfully to "event" added to list successfully
- Fix toolbar for events so buttons group together
- Fix issue when clicking on a Program Type on an event page for Communico Events

Event Fixes

---

code/web/Drivers/Nashville.php

Update credit card process to set expdate

---

code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/Springshare/event.tpl

Updates to how events pages display:
--Moved title to very top of page
--Added more action buttons for saving, adding to lists, and registering/viewing on calendar sites 
--Moved around some rows and other divs to make the display more consistent

Events Page Updates

---

code/web/Drivers/Evergreen.php
code/web/interface/themes/responsive/MyAccount/evergreenEmailResetPinLink.tpl
code/web/interface/themes/responsive/MyAccount/evergreenPasswordRecovery.tpl
code/web/interface/themes/responsive/MyAccount/evergreenPasswordRecoveryResult.tpl

This set of patches adds support for patron password reset and recovery when using Evergreen. It also proposes a minor renaming of some page templates used by ILS-driver-based password recovery.

Evergreen: password recovery and reset

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/MarcRecordProcessor.java

Small change to pagesPattern2 in MarcRecordProcessor.java

pagesPattern2

---

code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/MyAccount/deletedListEntry.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/sys/Covers/BookCoverProcessor.php
code/web/sys/UserLists/UserList.php

Generate event covers for past events that are on lists

Past Event Covers

---

code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/interface/themes/responsive/account-menu.tpl
code/web/sys/DBMaintenance/version_updates/23.04.00.php

- Increase size for sourceId in user_events_entry table for library market events 
- Fixed some small issues with event page displays
- Fixed an issue with the "Your Events" option in dropdown menu (wrong div class)

Small Fixes

---

code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Index/browse_result.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/services/MyAccount/AJAX.php
code/web/sys/DBMaintenance/version_updates/23.04.00.php
code/web/sys/LibraryLocation/Library.php

- Display if an event is an all day event or if it is a multi-day event
- Made some things translatable that weren't before on event pages 
- Fixed check to see if library has event integration 
- Fix cover style for events in browse categories
- Fix unique key for user_events_entry table

More Small Event Fixes

---

code/web/RecordDrivers/IndexRecordDriver.php

Pass in browseCategoryRatingsMode for events in browse categories

Update IndexRecordDriver.php 

---

code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/release_notes/23.04.01.MD

Changes display for all day and multi-day events to reflect that they are all day or span multiple days

All Day and Multi-Day Events

---

code/web/Drivers/Evergreen.php
code/web/Drivers/Koha.php
code/web/Drivers/OverDriveDriver.php
code/web/interface/themes/responsive/MyAccount/ilsHold.tpl

Update "Frozen until ..." to be translatable

"Frozen until ..." Translation

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java
code/events_indexer/src/com/turning_leaf_technologies/events/SpringshareLibCalIndexer.java
code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/MyAccount/myEventsList.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/release_notes/23.05.00.MD
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.05.00.php
code/web/sys/Events/UserEventsEntry.php
code/web/sys/Events/UserEventsRegistrations.php

- If a user has registered with their barcode for Communico or Springshare LibCal events, the "Check Registration" button will read "You Are Registered" 

Event Registration

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java
code/web/release_notes/23.05.00.MD

Per request, search tags will no longer be indexed for Communico Updated release notes

No Indexing Search Tags for Communico

---

code/web/interface/themes/responsive/Events/searchError.tpl
code/web/release_notes/23.06.00.MD
code/web/services/Events/Results.php
code/web/sys/DBMaintenance/version_updates/23.06.00.php
code/web/sys/Events/CommunicoSetting.php
code/web/sys/Events/EventsBranchMapping.php
code/web/sys/Events/LMLibraryCalendarSetting.php
code/web/sys/Events/SpringshareLibCalSetting.php
code/web/sys/LibraryLocation/Location.php
code/web/sys/SolrConnector/EventsSolrConnector.php

- Updated search errors for events to show solr info 
- Added new table for mapping aspen locations to locations in event integrations 
- Updated Location.php to add new, update existing, and delete event mapping locations where necessary 
- Updated event search relevancy to boost events at patron home library first 

Event Location Mapping & Relevancy

---

code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/MyAccount/myEventsList.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/interface/themes/responsive/Springshare/event.tpl

Add a space between "Check Registration"/"You Are Registered" and external link icon

Events Registration Buttons

---

code/web/interface/themes/responsive/GroupedWork/upload-cover-form-url.tpl
code/web/interface/themes/responsive/GroupedWork/upload-cover-form.tpl
code/web/interface/themes/responsive/js/aspen/grouped-work.js
code/web/release_notes/23.06.00.MD
code/web/services/GroupedWork/AJAX.php
code/web/sys/Covers/CoverImageUtils.php

Added options to uploading covers:
for bib level upload:
Apply to Only This Record
AND Apply to Grouped Work (default)
and for grouped work level upload:
Apply to Only Grouped Work
Also Apply to All Records
Also Apply to All Records with a Default Cover (default) 
Updated Release Notes

Upload Cover Options

---

code/web/release_notes/23.06.00.MD
code/web/services/GroupedWork/AJAX.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php

- If uploading a cover image for a grouped work with only one record, use the uploaded cover for that record 
- Fixed a small php error

Cover Image

---

code/web/Drivers/CarlX.php
code/web/Drivers/Nashville.php

Fixes Nashville Nonresident update

---

code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/listEntry.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/release_notes/23.06.00.MD

-Make "In Your Events" and "Add To Events" buttons on event pages the same width 
-Show "Add To Events" buttons for events on lists
-Fix white space issues for Library Market event pages 
-Updated release notes

Events Fixes

---

code/web/services/GroupedWork/AJAX.php
code/web/sys/Covers/CoverImageUtils.php

Reload covers for additional works that are changed when uploading a new cover image

Upload Cover Fix

---

code/web/services/GroupedWork/AJAX.php

Cover Upload Messaging Updates

---

code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js

-Now, after create a new account via Self-Registration Form, the users are redirected to the Home page instead of Self-Registration Form

New users should be redirected correctly after logging in.

---

code/web/Drivers/CarlX.php

Fixes Nashville fees report

---

code/web/release_notes/23.07.00.MD
code/web/sys/DBMaintenance/version_updates/23.07.00.php
code/web/sys/Recommend/TopFacets.php
code/web/sys/Theming/Theme.php

- Adds ability to upload custom icons for format category icons 
- New columns in themes table for the icon images

Custom Format Category Icons

---

code/web/release_notes/23.07.00.MD
code/web/sys/Covers/BookCoverProcessor.php
sites/default/translation_maps/format_category_map.properties

Add format category "other" for bingepass to clear Hoopla extract errors

Bingepass Format Category

---

code/cron/src/com/turning_leaf_technologies/cron/DatabaseCleanup.java
code/web/index.php
code/web/release_notes/23.07.00.MD

- Update databasecleanup.java to optimize the search table

Database Cleanup

---

code/symphony_export/src/com/turning_leaf_technologies/symphony/SymphonyExportMain.java
code/web/release_notes/23.07.00.MD

- Hide staff/private notes but show public notes for Symphony if note field is specified in indexing profile 

Public notes

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java

Adds more debugging notes/log entries for event indexing

Debugging for events indexing

---

code/web/app/readme.txt
code/web/release_notes/23.08.00.MD
code/web/services/API/SearchAPI.php

Update indexing errors/warnings for side loads to use same logic we use for website indexing

Side Loads Indexing Error Log

---

code/web/RecordDrivers/CommunicoEventRecordDriver.php
code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/Events/result-tools-horizontal.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/release_notes/23.08.00.MD
code/web/services/Communico/Event.php
code/web/services/LibraryMarket/Event.php
code/web/services/Springshare/Event.php
code/web/sys/DBMaintenance/version_updates/23.08.00.php
code/web/sys/Events/CommunicoSetting.php
code/web/sys/Events/LMLibraryCalendarSetting.php
code/web/sys/Events/SpringshareLibCalSetting.php

- Added ability to prevent certain users from adding events to lists 
- Added ability to bypass the Aspen event pages

Event Page Bypass & Events in Lists

---

code/web/sys/DBMaintenance/version_updates/23.08.00.php
code/web/sys/LibraryLocation/Location.php

- A new field, referring to a library's secondary phone number, has been added to the localization form.

Secondary phone number was added to Location Forms

---

code/web/services/GroupedWork/AJAX.php

fix issue with missing require_once for bookcoverinfo.php

BookCoverInfo fix

---

code/web/release_notes/23.08.00.MD
code/web/services/API/SearchAPI.php
code/web/sys/Ebsco/EBSCOhostDatabase.php
code/web/sys/OpenArchives/OpenArchivesCollection.php
code/web/sys/WebsiteIndexing/WebsiteIndexSetting.php
code/web_indexer/src/com/turning_leaf_technologies/website_indexer/WebsiteIndexer.java

Fix for website indexing using .xml files

Website Indexing

---

code/symphony_export/src/com/turning_leaf_technologies/symphony/SymphonyExportMain.java
code/web/interface/themes/responsive/RecordDrivers/GroupedWork/grouping-information.tpl
code/web/release_notes/23.08.00.MD

Fix issue where image source = "Not Available" for all works

Image Source

---

code/web/RecordDrivers/LibraryCalendarEventRecordDriver.php
code/web/RecordDrivers/SpringshareLibCalEventRecordDriver.php
code/web/interface/themes/responsive/Communico/event.tpl
code/web/interface/themes/responsive/Events/result-tools-horizontal.tpl
code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/Springshare/event.tpl
code/web/services/LibraryMarket/Event.php
code/web/services/Springshare/Event.php

changes $isStaffWithPermissions to $isStaff when checking if user can add events to lists

isStaff check for adding events to lists

---

code/web/interface/themes/responsive/LibraryMarket/event.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/communico_result.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/library_calendar_result.tpl
code/web/interface/themes/responsive/theme.css.tpl
code/web/services/MyAccount/AJAX.php

Fix error when adding an event to a newly created list 
Fix UI styling issues with buttons - size of buttons and hover effect

Events Small Fixes

---

code/web/services/Events/EventsFacets.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.08.00.php
code/web/sys/DBMaintenance/version_updates/23.08.10.php
code/web/sys/Events/EventsFacet.php
code/web/sys/Events/EventsFacetGroup.php
code/web/sys/Events/LibraryEventsSetting.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/Recommend/SideFacets.php
code/web/sys/SearchObject/EventsSearcher.php

3 new files:
services\Events\EventsFacets.php
sys\Events\EventsFacet.php
sys\Events\EventsFacetGroup.php
2 Edited:
sys\Account\User.php - Add section for Event Facet Settings in Admin sys\SearchObject\EventsSearcher.php - Update how we search with facets for events (note, this does not work at all yet)
23.08.00.php updates:
--Add permissions for editing events facets
--Add table for Events Facets

Events Updates Progress

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java
code/events_indexer/src/com/turning_leaf_technologies/events/LibraryMarketLibraryCalendarIndexer.java
code/events_indexer/src/com/turning_leaf_technologies/events/SpringshareLibCalIndexer.java

Finish up limiting indexed events by number of days

Events Indexing

---

code/web/release_notes/23.08.10.MD
code/web/sys/SearchObject/EventsSearcher.php

Fixed an issue where, if no events integrations were active, getEventFacetSettings() would throw an error on null

Update Release Notes & Small Bug Fix 

---

code/web/release_notes/23.08.01.MD
code/web/services/GroupedWork/AJAX.php

Fix for cover images not uploaded at the grouped work level when using URL upload

Image Upload by URL

---

code/web/release_notes/23.09.00.MD
code/web/services/OpenArchives/OpenArchivesFacets.php
code/web/services/Websites/WebsiteFacets.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.09.00.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/LibraryLocation/Location.php
code/web/sys/OpenArchives/OpenArchivesFacet.php
code/web/sys/OpenArchives/OpenArchivesFacetGroup.php
code/web/sys/SearchObject/EventsSearcher.php
code/web/sys/SearchObject/OpenArchivesSearcher.php
code/web/sys/SearchObject/WebsitesSearcher.php
code/web/sys/WebsiteIndexing/WebsiteFacet.php
code/web/sys/WebsiteIndexing/WebsiteFacetGroup.php

New Files:
\services\OpenArchives\OpenArchivesFacets.php
\sys\OpenArchives\OpenArchivesFacet.php
\sys\OpenArchives\OpenArchivesFacetGroup.php
\services\Websites\WebsiteFacets.php
\sys\WebsiteIndexing\WebsiteFacet.php
\sys\WebsiteIndexing\WebsiteFacetGroup.php
Updated Files:
EventsSearcher.php - Removed unused code
User.php - Added admin sections for website and OA facet settings
23.09.00.php - Added tables, permissions, and defaults for website and OA facet settings
Library.php and Location.php - added necessary functions for getting website and OA facet settings per library/location
OpenArchivesSearcher.php and WebsitesSearcher.php - updated getFacetConfig() functions
Updated Release Notes

Facet Config for Websites and OA 

---

code/reindexer/src/com/turning_leaf_technologies/grouping/RecordGroupingProcessor.java
code/web/interface/themes/responsive/Search/Recommend/calendarFacet.tpl
code/web/release_notes/23.09.00.MD
code/web/services/Search/AJAX.php
code/web/sys/Recommend/SideFacets.php

- Updated event date facet to limit max date by numberOfDaysToIndex 
- Added check for instance of Aspen Error on saved searches 

Event Date Facet & Error Fix

---

code/web/release_notes/23.09.00.MD
code/web/services/Admin/UsageDashboard.php
code/web/sys/SystemLogging/AspenUsage.php

- Fix issue where aspen_usage variables are inaccessible 

Usage Dashboard

---

code/web/RecordDrivers/MarcRecordDriver.php
code/web/RecordDrivers/OverDriveRecordDriver.php
code/web/release_notes/23.09.00.MD

- Fix issue where wrong language shows in More Details for non-English works 
strlen($field008->getData() >= 37) calculation within if statement was returning false - declaring a variable for the length and checking that fixes the issue

More Details Language

---

code/web/release_notes/23.10.00.MD
code/web/sys/DBMaintenance/version_updates/23.10.00.php
code/web/sys/ExploreMore.php
code/web/sys/Theming/Theme.php

Adds ability to upload images for the explore more icons (settings in themes) 

Explore More Icon Images

---

code/web/index.php
code/web/sys/LibraryLocation/Library.php

Comment out ability to enabled cookies consent control whilst we await further follow-ups from @Jacobomara901

Disable Cookie Consent

---

code/web/interface/themes/responsive/MyAccount/contactInformation.tpl
code/web/interface/themes/responsive/MyAccount/myPreferences.tpl
code/web/interface/themes/responsive/Search/Recommend/multiSelectFacet.tpl
code/web/interface/themes/responsive/Search/Recommend/standardFacet.tpl
code/web/release_notes/23.10.00.MD
code/web/services/MyAccount/ContactInformation.php
code/web/services/MyAccount/MyPreferences.php

Fix for honoring number of entries to show for facets
Fix for updating wrong contact information and preferences 

Num Entries & Contact Info/My Preferences

---

code/web/cron/checkBackgroundProcesses.php
sites/template.linux/conf/config.ini

- New variable saves data about solr host
- The condition checks solr host while checkBackgroundProcesses is running

A new variable and a new condition, related to Solr, have been added

---

code/web/Drivers/SirsiDynixROA.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/SelfRegistrationForms/SelfRegistrationForm.php
code/web/sys/SelfRegistrationForms/SelfRegistrationFormValues.php

- moved CITY/STATE vs City AND State variable from self registration form and back into primary config 
- reorganized selfRegister() in SirsiDynixROA.php to check for custom selfReg forms and loop through each field in order of weight

Symphony Self Reg

---

code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/23.10.10.MD
code/web/sys/DBMaintenance/version_updates/23.10.10.php
code/web/sys/SelfRegistrationForms/SelfRegistrationForm.php
sites/arlington.production/conf/crontab_settings.txt
sites/aspencat.production/conf/crontab_settings.txt
sites/basinlibraries.production/conf/crontab_settings.txt
sites/model.production/conf/crontab_settings.txt
sites/model2.production/conf/crontab_settings.txt
sites/nashville.production/conf/crontab_settings.txt
sites/pueblo.production/conf/crontab_settings.txt

Updated crontab_settings.txt in sites directory for those that needed it
Added option to use barcode prefixes for symphony custom self registration forms

Cron Updates & Barcode Prefixes

---

code/web/release_notes/23.11.00.MD
code/web/services/API/UserAPI.php

Make UserAPI.php honor pType restrictions for account linking

Update UserAPI.php 

---

code/web/Drivers/SirsiDynixROA.php
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/release_notes/23.11.00.MD
code/web/sys/DBMaintenance/version_updates/23.11.00.php
code/web/sys/SelfRegistrationForms/SelfRegistrationForm.php
code/web/sys/SelfRegistrationForms/SelfRegistrationFormValues.php
sites/nashville.production/conf/crontab_settings.txt

-displayName field is now required
-Updated city/state field logic
-Added prompting for parent name to custom forms
-Updated release notes

Symphony Self Registration Updates

---

code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/23.11.01.MD

Fix issue showing/hiding parent name when prompting user for parent info Updated release notes

Show/Hide Parent Name Field (Symphony Self Registration)

---

code/web/release_notes/23.11.01.MD
code/web/sys/LibraryLocation/Library.php

Make expirationNearMessage and ExpiredMessage type 'html' 

Expiry Messaging

---

code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/23.11.01.MD
code/web/sys/DBMaintenance/version_updates/23.11.01.php
code/web/sys/SelfRegistrationForms/SelfRegistrationFormValues.php

Fix case sensitivity issue when checking cellphone vs cellPhone field for SMS Notice information 

Symphony Self Registration Case Sensitive

---

code/web/RecordDrivers/GroupedWorkDriver.php
code/web/RecordDrivers/MarcRecordDriver.php
code/web/interface/themes/responsive/Record/select-view-item-link-form.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/record.js
code/web/release_notes/23.12.00.MD
code/web/services/Record/AJAX.php
code/web/services/Record/AccessOnline.php

Fix Access Online button redirects when multiple variations are present on a record 

Access Online

---

code/web/Drivers/OverDriveDriver.php
code/web/RecordDrivers/Axis360RecordDriver.php
code/web/RecordDrivers/GroupedWorkDriver.php
code/web/RecordDrivers/MarcRecordDriver.php
code/web/RecordDrivers/OverDriveRecordDriver.php
code/web/interface/themes/responsive/OverDrive/dashboard.tpl
code/web/interface/themes/responsive/OverDrive/overdriveApiData.tpl
code/web/interface/themes/responsive/OverDrive/overdriveAspenData.tpl
code/web/interface/themes/responsive/OverDrive/overdriveExtractLog.tpl
code/web/interface/themes/responsive/RecordDrivers/GroupedWork/grouping-information.tpl
code/web/interface/themes/responsive/RecordDrivers/GroupedWork/staff-view.tpl
code/web/interface/themes/responsive/RecordDrivers/OverDrive/staff.tpl
code/web/release_notes/23.12.00.MD
code/web/services/Axis360/IndexingLog.php
code/web/services/Axis360/Scopes.php
code/web/services/Axis360/Settings.php
code/web/services/MyAccount/AJAX.php
code/web/services/OverDrive/APIData.php
code/web/services/OverDrive/AspenData.php
code/web/services/OverDrive/Dashboard.php
code/web/services/OverDrive/Graphs.php
code/web/services/OverDrive/IndexingLog.php
code/web/services/OverDrive/Scopes.php
code/web/services/OverDrive/Settings.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/23.12.00.php
code/web/sys/OverDrive/OverDriveScope.php
code/web/sys/Theming/Theme.php

Changes to make "OverDrive" a custom set name
Note: java file changes not included since I am working on changes to make the value scoped

OverDrive to Custom Reader Name

---

code/web/Action.php
code/web/interface/themes/responsive/MyAccount/account-sidebar.tpl
code/web/interface/themes/responsive/MyAccount/checkedout.tpl
code/web/interface/themes/responsive/MyAccount/holds.tpl
code/web/interface/themes/responsive/MyAccount/overDriveOptions.tpl
code/web/interface/themes/responsive/MyAccount/overdriveCheckedOutTitle.tpl
code/web/interface/themes/responsive/MyAccount/overdriveHold.tpl
code/web/interface/themes/responsive/OverDrive/dashboard.tpl
code/web/interface/themes/responsive/OverDrive/overdriveApiData.tpl
code/web/interface/themes/responsive/OverDrive/overdriveAspenData.tpl
code/web/interface/themes/responsive/RecordDrivers/OverDrive/staff.tpl
code/web/interface/themes/responsive/account-menu.tpl
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/CheckedOut.php
code/web/services/MyAccount/Holds.php
code/web/services/MyAccount/MyAccount.php
code/web/services/MyAccount/OverDriveOptions.php
code/web/services/OverDrive/Dashboard.php

updated some missed areas where OverDrive was visible to patrons

More OverDrive -> custom reader name

---

code/web/interface/themes/responsive/Donations/newDonation.tpl
code/web/interface/themes/responsive/MyAccount/fines.tpl
code/web/interface/themes/responsive/MyAccount/stripePayments.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/services/Admin/StripeSettings.php
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Fines.php
code/web/sys/Account/User.php
code/web/sys/Account/UserPayment.php
code/web/sys/DBMaintenance/version_updates/24.01.00.php
code/web/sys/ECommerce/StripeSetting.php
code/web/sys/LibraryLocation/Library.php

so far I've just been testing with the stripePayments.tpl to try and get the UI showing on the user fines page.
I've been using these sites for reference: 
- https://stripe.com/docs/payments/payment-element
- https://stripe.com/docs/js/initializing
- https://stripe.com/docs/payments/quickstart (this one requires using the stripe php library, so not sure if it's too helpful)

Stripe So Far

---

code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/24.01.00.MD
code/web/sys/DBMaintenance/version_updates/24.01.00.php
code/web/sys/SelfRegistrationForms/SelfRegistrationForm.php

Added option to disable duplicate patron check
Tested on localhost ✓

Symphony Self Registration Fixes

---

code/web/interface/themes/responsive/Donations/deluxeCertifiedPaymentsPayments.tpl
code/web/interface/themes/responsive/Donations/newDonation.tpl
code/web/interface/themes/responsive/Donations/stripePayments.tpl
code/web/interface/themes/responsive/MyAccount/stripePayments.tpl
code/web/services/Donations/NewDonation.php
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Fines.php
code/web/sys/Donations/Donation.php
code/web/sys/ECommerce/StripeSetting.php

Added donations for Stripe
Fixed issue where special parameters for some vendors weren't being declared in NewDonation.php
NOTE: Donations integration was only tested for Stripe. For now, we only know that PayPal and comprise SMARTPAY are working for donations. Stripe donations were tested on my local but need to be QA'd

Stripe & Donations

---

code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryAvailabilityType.java
code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryAvailabilityTypeHandler.java
code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryExporter.java
code/cloud_library_export/src/com/turning_leaf_technologies/cloud_library/CloudLibraryMarcHandler.java
code/reindexer/src/com/turning_leaf_technologies/reindexer/CloudLibraryProcessor.java
code/web/release_notes/24.02.00.MD
code/web/sys/DBMaintenance/version_updates/24.02.00.php

- Adds support for on order items for cloud library and fix some availability discrepancies 
- Fixed a couple syntax errors in DB updates for 24.02
- Tested on my local machine

Cloud Library Updates

---

code/web/interface/themes/responsive/MyAccount/stripePayments.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/release_notes/24.02.00.MD

Fixes issue where payment submission button gets stuck on "Submitting Payment..." for Stripe 

Stripe Payment Button Fix

---

code/events_indexer/src/com/turning_leaf_technologies/events/CommunicoIndexer.java
code/web/release_notes/24.02.00.MD

Fix issue with the Communico API request for event registrations 

Communico API Call Fix

---

code/web/interface/themes/responsive/Donations/form-fields.tpl
code/web/release_notes/24.01.00.MD
code/web/release_notes/24.02.00.MD
code/web/services/Donations/NewDonation.php
code/web/sys/DBMaintenance/version_updates/24.02.00.php
code/web/sys/Donations/Donation.php
code/web/sys/Donations/DonationFormFields.php
code/web/sys/ECommerce/DonationsSetting.php

- Added a checkbox to request users to add their address (street, city, state and zip code) when making a donation.

User's address information can be added to the donations

---

code/web/interface/themes/responsive/MyAccount/selfReg.tpl
code/web/release_notes/24.02.00.MD
code/web/services/Admin/USPS.php
code/web/services/MyAccount/ContactInformation.php
code/web/services/MyAccount/SelfReg.php
code/web/sys/Account/User.php
code/web/sys/Administration/USPS.php
code/web/sys/DBMaintenance/version_updates/24.02.00.php
code/web/sys/Utils/SystemUtils.php

Adds USPS address validation functionality via their API 
Tested on my local for Koha and Symphony

USPS Address Validation

---

code/web/services/API/EventAPI.php
code/web/services/MyAccount/ContactInformation.php
code/web/sys/Covers/BookCoverProcessor.php
code/web/sys/Covers/EventCoverBuilder.php
code/web/sys/UserLists/UserList.php

Added check for validating address in contact info to make sure the user can edit their address 
Updated event cover builder to build greyscale cover for past events 
Updated user list to use medium size covers for events that have passed (these will disappear anyway when the cron runs but it was bothering me :))

Event Covers & Small USPS Update

---

code/web/sys/Utils/SystemUtils.php

urlencodes the city parameter for address validation in case the city has spaces in the name

urlencode city for address validation

---

code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/24.02.00.MD

Fix for empty sections in Symphony self registration 

Empty Sections

---

code/web/interface/themes/responsive/DataObjectUtil/objectEditForm.tpl
code/web/interface/themes/responsive/Error/400.tpl
code/web/interface/themes/responsive/MaterialsRequest/new.tpl
code/web/interface/themes/responsive/MyAccount/ajax-login.tpl
code/web/interface/themes/responsive/MyAccount/login.tpl
code/web/release_notes/24.03.00.MD
code/web/services/Admin/ObjectEditor.php
code/web/services/Error/Handle400.php
code/web/services/MaterialsRequest/NewRequest.php
code/web/services/MaterialsRequest/Submit.php
code/web/services/WebBuilder/SubmitForm.php
code/web/sys/Grouping/HideSeries.php
code/web/sys/Grouping/HideSubjectFacet.php
code/web/sys/WebBuilder/CustomForm.php

- Fix for smarty error $tos being undefined
- Fix for normalized series values removing trailing "t"s
- Added check for patronId match in custom forms on submission (if user is logged in)
- Added check for patronId match in materials request form on submission

Various Things

---

code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/interface/themes/responsive/Springshare/event.tpl

Hide "Location:" if it is empty

Springshare Event Display

---

security.md

Will need some filling in and ensuring that the noted resources exist, but is a start.

Add security policy via security.md

---

code/web/Drivers/CarlX.php
code/web/interface/themes/responsive/RecordDrivers/Events/springshare_libcal_result.tpl
code/web/release_notes/24.04.00.MD
code/web/sys/DBMaintenance/version_updates/24.04.00.php
code/web/sys/Email/EmailTemplate.php
code/web/sys/LibraryLocation/Library.php

Update carlX Self Registration to be non-specific (Ticket 127443) - Needs testing with ILS access 
Fix issue with Springshare LibCal events display when no 'campus' is defined 

carlX Self Registration

---

code/web/Drivers/PalaceProjectDriver.php
code/web/sys/LibraryLocation/Library.php

Add "Forces Reindex = true" for additionalLocationsToShowAvailabilityFor in Library.php 
Update log entry type for placeHold in PalaceProjectDriver.php to 'palaceProject.placeHold' instead of 'palaceProject.checkoutTitle'

Tiny Changes (Ticket Time)

---

code/reindexer/src/com/turning_leaf_technologies/reindexer/PalaceProjectProcessor.java
code/web/release_notes/24.04.01.MD
code/web/sys/PalaceProject/PalaceProjectCollection.php

Change audience to "Adult" instead of "Adults"
Add getNumericColumnNames() for PalaceProjectCollection.php

Small Palace Project Things

---

code/web/interface/themes/responsive/MyAccount/ajax-masqueradeAs.tpl
code/web/interface/themes/responsive/MyAccount/masqueradeAs.tpl
code/web/release_notes/24.05.00.MD
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Masquerade.php
code/web/sys/DBMaintenance/version_updates/24.05.00.php
code/web/sys/LibraryLocation/Library.php

Added a toggle that allows/disallows masquerading using a username 

Username Login For Masquerade

---

.github/workflows/main.yml

Change the docker hub repo name from aspendiscoveryofficial to aspendiscovery

---

code/reindexer/src/org/aspen_discovery/reindexer/Axis360Processor.java
code/web/release_notes/24.05.00.MD

Updated where we set itemInfo in Axis360Processor.java to fix issue with availability when we have lots of different settings Updated release notes
Tested on my local with single work index

Axis360 Availability

---

code/web/interface/themes/responsive/Assabet/event.tpl
code/web/services/API/EventAPI.php
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/User.php

Small fixes for Assabet integration

Assabet Fixes

---

code/web/robots.txt

gptbot is very aggressive, let's disallow them along with the other very aggressive bots.

Add GPTBot to robots.txt

---

sites/default/conf/bots.txt

Adding gptbot to bots.txt to allow statistical collection for requests via gptbot

Add gptbot to bots.txt

---

code/reindexer/src/org/aspen_discovery/grouping/MarcRecordGrouper.java
code/web/Drivers/Polaris.php
code/web/Drivers/Sierra.php
code/web/interface/themes/responsive/Events/list.tpl
code/web/interface/themes/responsive/Genealogy/list.tpl
code/web/interface/themes/responsive/Search/search-toolbar-no-display-mode.tpl
code/web/release_notes/24.05.00.MD
code/web/services/MyAccount/SelfReg.php
code/web/sys/CloudLibrary/CloudLibraryScope.php
code/web/sys/DBMaintenance/version_updates/24.05.00.php
code/web/sys/Indexing/SideLoadScope.php
code/web/sys/LibraryLocation/Library.php

- Fixed incorrect info for some tooltips
- Fixed search tools not showing at the top of results for Events or Genealogy 
- Added option for Sierra libraries to define what field in Sierra corresponds to username 
- Updated naming for external log request entry for updating usernames for Polaris 
- Added in an if/else statement in MarcRecordGrouper.java where I was receiving an error about a null value 

Small Fixes & Ticket Request

---

code/events_indexer/src/com/turning_leaf_technologies/events/AssabetIndexer.java
code/web/release_notes/24.05.01.MD

- Fix for "canceled" value not being a string
- Deleted redundant code 
- Tested on my local

Assabet Indexing Fix

---

code/web/Drivers/Polaris.php
code/web/release_notes/24.07.00.MD
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/UserPayment.php

Donations Fix

---

code/web/interface/themes/responsive/Donations/stripePayments.tpl
code/web/release_notes/24.08.00.MD
code/web/sys/Donations/Donation.php

Fix issues with Stripe and Square donations where the card info box does not appear when user is not logged in

Stripe and Square Donations

---

code/web/release_notes/24.08.00.MD
code/web/sys/DBMaintenance/version_updates/24.08.00.php
code/web/sys/WebBuilder/CustomForm.php

https://ticket.bywatersolutions.com/SelfService/Display.html?id=132417

Increase web builder custom form email-to size

---

code/web/interface/themes/responsive/Summon/list.tpl
code/web/release_notes/24.08.00.MD

Updated version of the addition of search tools to the top of the Summon results with the correct files to not show the unimplemented list / cover option.

Summon search tools

---

code/web/index.php
code/web/release_notes/24.08.00.MD

- Allow Aspen to change languages when users fill out forms.

Change of languages in custom forms

---

code/web/sys/DBMaintenance/grapes_web_builder_updates.php

Update the table name that the blank template is assigned to in order to match change of table name from templates to grapes_templates.

refactor: Update table blank template is assigned to

---

code/web/sys/DBMaintenance/grapes_web_builder_updates.php

Remove insert to template table as this is now grapes_templates table

refactor: Remove insert to template table

---

code/web/index.php
code/web/release_notes/24.09.00.MD
code/web/services/API/SystemAPI.php
code/web/services/Translation/ImportTranslations.php
code/web/services/Translation/Translations.php
code/web/sys/Email/EmailTemplate.php

- Added display name as second factor everywhere Aspen already sorts language by weight.

Sort languages consistently by weight then by display name

---

code/web/Drivers/Sierra.php
code/web/Drivers/SirsiDynixROA.php
code/web/release_notes/24.08.10.MD
code/web/services/ILS/SelfRegistrationForms.php
code/web/services/MyAccount/SelfReg.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/24.08.10.php
code/web/sys/SelfRegistrationForms/SelfRegistrationForm.php
code/web/sys/SelfRegistrationForms/SelfRegistrationFormValues.php
code/web/sys/SelfRegistrationForms/SelfRegistrationTerms.php
code/web/sys/SelfRegistrationForms/SierraSelfRegistrationForm.php

- Functionality for custom self registration forms and ILS-based self registration via Sierra APIs for Sierra libraries 
- Added TOS functionality for CarlX self registration via ILS 
- Added release notes & DB updates

Sierra Self Reg

---

.github/workflows/main.yml

- Fix relative paths either for solr and tunnel dockerfiles

Fix continuous integration script for building solr and tunnel images

---

code/web/sys/DBMaintenance/version_updates/24.08.10.php

Fix error when using RENAME COLUMN by using CHANGE COLUMN instead

Use CHANGE instead of RENAME

---

code/web/sys/DBMaintenance/version_updates/24.08.10.php

Increase Note column size for self_reg_form_values

Note Column Size for Self Reg Values

---

code/web/Drivers/Nashville.php

removes sql-query-killing semicolon

Fixes Nashville-specific Holds Report

---

code/web/release_notes/24.09.00.MD
code/web/sys/Account/UserPayment.php

Remove false error message when NCR payments are completed 

False Error NCR

---

.github/workflows/main.yml
code/web/release_notes/24.09.00.MD

This pull request greatly reduces the build time for the Aspen docker images. Previously each registry ran an independent build and push step. This branch collapses those down to a single build and push step for each Dockerfile while also adding in support for GHCR. Any future container registry additions would only add a few more seconds to the build time.

Update GitHub actions to improve build time and add support for GHCR

---

code/web/Drivers/Nashville.php

- Fixes dumb SQL mistake in whole-grade report
- Improves record sort order with feedback from KW. Whole-grade report now sorts by student name. Whole-school report now sorts by grade, then student name.

Improvements to Nashville Student Barcode report

---

code/web/bootstrap.php
code/web/interface/themes/responsive/Admin/usage_by_user_agent.tpl
code/web/release_notes/24.09.00.MD
code/web/services/Admin/UsageByUserAgent.php

- Added pagination to Usage by User Agent Report

Add pagination to Usage by User Agent Report

---

code/web/Drivers/Koha.php
code/web/Drivers/Sierra.php
code/web/migrations/importBiblioCommonsData.php
code/web/release_notes/24.08.01.MD

Fix issue where importing BiblioCommons data for Sierra libraries is not working correctly 
Tested on my local by running a BiblioCommons import with shelves and  staff list csv files

BiblioCommons Import

---

code/web/.idea/dataSources.local.xml
code/web/interface/themes/responsive/Report/barcodeGenerator.tpl
code/web/interface/themes/responsive/Report/discBarcodeGenerator.tpl
code/web/interface/themes/responsive/Report/studentBarcodes.tpl
code/web/release_notes/24.09.00.MD
code/web/services/Report/BarcodeGenerator.php
code/web/services/Report/DiscBarcodeGenerator.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/24.09.00.php

Adds Code 39 barcode generator for Avery 5160 labels to Circulation Reports.
Still needs testing in Nashville to ensure print alignment on Avery 5160 labels using browser Edge

24.09.00 Barcode Generator

---

.github/workflows/pull_request_qa.yml
code/web/release_notes/24.09.00.MD

This action attempts to do basic checking of changes to createSite.php that would need changes to Docker files, and then checks to see if any files in the docker directory have been changes. I'm sure we can improve this check with experience.
Closes Aspen-Discovery/aspen-discovery#2026

Add GH Action to check for changes in createSite.php that may need changes in docker

---

code/web/Drivers/Sierra.php

add pickup location/home library for sierra self registration
tested on my local by creating a new patron via self registration

update sierra self registration

---

code/oai_indexer/src/com/turning_leaf_technologies/oai/OAISolrRecord.java
code/oai_indexer/src/com/turning_leaf_technologies/oai/OaiIndexerMain.java
code/web/release_notes/24.10.00.MD
code/web/sys/DBMaintenance/version_updates/24.10.00.php
code/web/sys/OpenArchives/OpenArchivesCollection.php
data_dir_setup/solr7/open_archives/conf/schema.xml

Add date formatting setting for OpenArchives collections to select how to show the date metadata to allow for flexibility of EDTF date formats

Updates to add date formatting setting for Open Archives

---

code/web/release_notes/24.10.00.MD
code/web/sys/LibraryLocation/Location.php

Adjusted the tooltip to be more specific per BWS ticket #138766.

Adjusted tooltip for "Automatically Update Hours from the ILS"

---

code/web/interface/themes/responsive/Report/barcodeGenerator.tpl
code/web/release_notes/24.10.00.MD

All this does is remove an errant quotation mark.

24.10.00 barcode generator

---

code/web/release_notes/24.10.00.MD
code/web/sys/Email/SMTPSetting.php

The plaintext message was causing AJAX errors when using the sendEmail method.

Comment out debugging code from SMTPSetting.php

---

code/web/release_notes/24.10.01.MD
code/web/services/MyAccount/AJAX.php

Backporting of patch accepted into 24.11.00

24.10.01 idor fix

---

code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/release_notes/24.11.00.MD
code/web/services/API/UserAPI.php

+ when guiding user initiates masquerade, keep the browser on the page rather than jump to the active user's MyAccount screen
+ when guiding user ends masquerade, return the browser to the page from which masquerade was initiated rather than jump to the guiding user's MyAccount screen

Change Masquerade flow

---

code/web/release_notes/25.01.00.MD
docker/files/scripts/initKohaLink.php

- Check if ils tables have been initialized in the DB

Add an initialization condition

---

code/web/sys/DBMaintenance/version_updates/25.02.00.php

- Modified SQL query to aggregate usage by user agent to use renaming and run quicker.

DIS-250: Modified SQL query to aggregate usage by user agent.

---

code/web/interface/themes/responsive/GroupedWork/full-record.tpl
code/web/release_notes/25.02.00.MD
code/web/services/Authentication/LiDA.php
code/web/sys/AspenLiDA/GeneralSetting.php
code/web/sys/DBMaintenance/version_updates/25.02.00.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/Session/SharedSession.php

- Add check for id parameter in request
- Add support for starting a shared session with LiDA to opening a Grouped Work page, if goTo is set to "GroupedWork" AND id is provided.

Add support for starting GroupedWork shared session (DIS-207)

---

code/web/bootstrap.php
code/web/release_notes/25.02.00.MD
code/web/sys/SystemLogging/UsageByIPAddress.php
code/web/sys/SystemLogging/UsageByUserAgent.php

- Added checks about whether a user usage agent exists; if it does not, insert one.
- Implemented atomic SQL updating of user usage agent requests and blocked requests.
- Moved the initialization of local time in `bootstrap.php` to occur before any usage table operations.

DIS-250: Fixed User Usage Checks & Added Atomic SQL Updates

---

code/web/interface/themes/responsive/WebBuilder/resourcesFiltered.tpl
code/web/interface/themes/responsive/WebBuilder/webResource.tpl
code/web/release_notes/25.03.00.MD
code/web/services/WebBuilder/ResourceAudience.php
code/web/services/WebBuilder/ResourceCategory.php
code/web/sys/DBMaintenance/version_updates/25.03.00.php
code/web/sys/WebBuilder/WebBuilderAudience.php
code/web/sys/WebBuilder/WebBuilderCategory.php

Add pages for each category and audience for Web Resources
Database Update: Add descriptions for categories and audiences for the Web Builder module
New Files:
\services\WebBuilder\ResourceAudience.php
\services\WebBuilder\ResourceCategory.php
\themes\responsive\WebBuilder\resourcesFiltered.tpl

DIS-336 : Updates to Aspen Web Resources

---

code/web/index.php
code/web/interface/themes/responsive/WebBuilder/resourcesFiltered.tpl
code/web/release_notes/25.03.00.MD
code/web/services/WebBuilder/CustomWebResourcePage.php
code/web/services/WebBuilder/CustomWebResourcePages.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/25.03.00.php
code/web/sys/WebBuilder/CustomWebResourcePage.php
code/web/sys/WebBuilder/CustomWebResourcePageAccess.php
code/web/sys/WebBuilder/CustomWebResourcePageAudience.php
code/web/sys/WebBuilder/CustomWebResourcePageCategory.php
code/web/sys/WebBuilder/LibraryCustomWebResourcePage.php

Add ability to create Custom Resource Pages
DB Updates for Custom Web Resource Pages:
- /25.03.00.php
- Add permissions
- Add specific tables for Custom Web Resource Pages
New Objects for Custom Web Resource Pages:
- /sys/WebBuilder/CustomWebResourcePage.php (Library Linked Object)
- /sys/WebBuilder/CustomWebResourcePageAccess.php
- /sys/WebBuilder/CustomWebResourcePageAudience.php
- /sys/WebBuilder/CustomWebResourcePageCategory.php
- /sys/WebBuilder/LibraryCustomWebResourcePage.php
Other:
- Add a link to get to Administration of Custom Web Resource Pages in Admin panel (User.php)
- Create /services/WebBuilder/CustomWebResourcePages.php for admin pages
- Handle redirects to URL Aliases set for Custom Web Resource Pages (index.php)
- Build the page using …

DIS-336 : Updates to Aspen Web Resources Part II

---

code/web/RecordDrivers/CustomResourcePagesRecordDriver.php
code/web/interface/themes/responsive/WebBuilder/resourcesAtoZ.tpl
code/web/interface/themes/responsive/css/main.css
code/web/interface/themes/responsive/css/responsive_base.less
code/web/release_notes/25.03.00.MD
code/web/services/WebBuilder/ResourcesAtoZ.php
code/web/services/WebBuilder/WebResourceSettings.php
code/web/sys/Account/User.php
code/web/sys/Covers/BookCoverProcessor.php
code/web/sys/DBMaintenance/version_updates/25.03.00.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/SearchObject/WebsitesSearcher.php
code/web/sys/WebBuilder/CustomWebResourcePage.php
code/web/sys/WebBuilder/WebResourcesSetting.php
code/web/sys/WebBuilder/WebResourcesToIndex.php
code/web_indexer/src/com/turning_leaf_technologies/website_indexer/WebBuilderIndexer.java

Create Resources A to Z page
-services/WebBuilder/ResourcesAtoZ.php
-responsive/WebBuilder/resourcesAtoZ.tpl
Added a few new classes to main.css
Create Web Resource Settings page
- /services/WebBuilder/WebResourcesSettings.php
- User.php
- /responsive/resourcesAtoZ.tpl
DB Updates:
- Create web_builder_web_resources_settings table
- Create web_builder_web_resources_to_index table
- Update Library table to include webResourcesSettingId
Update WebBuilderIndexer.java to index pages defined in web_builder_web_resources_to_index with scoping respecting web_builder_web_resources_to_index Library scope values
Update WebsiteSearcher.php and BookCoverProcessor.php to handle all the new types of web builder pages
Update Release Notes
**NOTE** I did not include …

DIS-336 : Updates to Aspen Web Resources Part IV

---

code/web/release_notes/25.03.00.MD
code/web/sys/DBMaintenance/version_updates/25.03.00.php
code/web/sys/SearchObject/SummonSearcher.php
code/web/sys/Summon/SummonSettings.php

https://aspen-discovery.atlassian.net/jira/software/c/projects/DIS/issues/DIS-314?filter=reportedbyme&jql=project%20%3D%20%22DIS%22%20AND%20reporter%20IN%20%28currentUser%28%29%29%20ORDER%20BY%20created%20DESC

Dis 314 remove results from summon search

---

code/evolve_export/src/org/aspendiscovery/evolve_export/EvolveExportMain.java
code/web/release_notes/25.03.00.MD

- Added existence check for the `"CircStatus"` JSON field, following the same pattern as the other fields' existence checks.
- Refractored the code for setting the subfield values from the JSON fields in order to remove duplicate lines.

DIS-430: Added CircStatus JSON field Existence Check For Evolve Exporter

---

code/symphony_export/src/com/turning_leaf_technologies/symphony/SymphonyExportMain.java
code/web/release_notes/25.03.00.MD

- Enhanced error and file handling for corrupt files sent from Symphony, thus preventing Aspen from looping while attempting to process those files.
- Added try-catch around the deletion of the original gzip/zip file after successful extraction.
IntelliJ also automatically fixed some weird indenting that was done for courses.

DIS-456: Enhanced Handling of Corrupted Symphony Export Files

---

code/web/interface/themes/responsive/MyAccount/holds.tpl
code/web/interface/themes/responsive/MyAccount/holdsList.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/release_notes/25.03.00.MD
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Holds.php
code/web/sys/DBMaintenance/version_updates/25.03.00.php
code/web/sys/LibraryLocation/Library.php

https://aspen-discovery.atlassian.net/browse/DIS-219?focusedCommentId=10510&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10510

DIS-219-Filter-Holds

---

code/web/Drivers/Evergreen.php
code/web/release_notes/25.03.00.MD

Jira ticket: [DIS-239](https://aspen-discovery.atlassian.net/browse/DIS-239)
[DIS-239]: https://aspen-discovery.atlassian.net/browse/DIS-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DIS-239: Evergreen patron email update

---

code/web/Drivers/Koha.php
code/web/interface/themes/responsive/CommunityEngagement/campaignTable.tpl
code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/services/MyAccount/AJAX.php

Bug fix for checkouts and holds milestones updating.

DIS-51: PTFS Community Engagement - Bug Fix 

---

code/events_indexer/src/com/turning_leaf_technologies/events/AspenEvent.java
code/events_indexer/src/com/turning_leaf_technologies/events/AspenEventsIndexer.java
code/web/RecordDrivers/AspenEventRecordDriver.php
code/web/interface/themes/responsive/AspenEvents/event.tpl
code/web/interface/themes/responsive/DataObjectUtil/property.tpl
code/web/interface/themes/responsive/Events/copyEventsForm.tpl
code/web/interface/themes/responsive/Events/event-graph.tpl
code/web/interface/themes/responsive/RecordDrivers/Events/aspenEvent_result.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/events.js
code/web/release_notes/25.03.00.MD
code/web/services/Events/AJAX.php
code/web/services/Events/EventFieldSets.php
code/web/services/Events/EventFields.php
code/web/services/Events/EventGraphs.php
code/web/services/Events/EventInstances.php
code/web/services/Events/EventTypes.php
code/web/services/Events/Events.php
code/web/services/Events/IndexingSettings.php
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/User.php
code/web/sys/DBMaintenance/version_updates/25.03.00.php
code/web/sys/Events/Event.php
code/web/sys/Events/EventField.php
code/web/sys/Events/EventFieldSet.php
code/web/sys/Events/EventInstance.php
code/web/sys/Events/EventType.php
code/web/sys/LibraryLocation/Location.php
code/web/sys/SystemVariables.php

Big changes:
- Add ability to copy events
- Add ability to set the sublocation at the event instance level to override the sublocation for the overall event.  For example, if just one instance has a room change in the same branch.
Lots of small fixes:
- Remove the 'enable Aspen Events toggle in Systems Variables, which was there temporarily to prevent Aspen Events being turned on before it was complete.
- Add a date range filter to Aspen Event Report
- Turn off run full index after a successful full index has run.
- Fix problem where the event menu wasn't showing from Event Reports
- Fix problem where there were no tooltips showing for custom event fields
- Prevent an annoying popup message if you picked the placeholder value when choosing an event type
- Fix bug where archived event …

DIS-192: QA Fixes Part 3

---

code/web/interface/themes/responsive/WebBuilder/resourcesAtoZ.tpl
code/web/services/Admin/ObjectEditor.php
code/web/services/WebBuilder/ResourcesAtoZ.php
code/web/services/WebBuilder/WebResourceSettings.php

Fix breadcrumbs for Web Resource Settings page
Fix "#" button showing up as "num" on A to Z page
Add note for placards that are customized indicating that they are customized
Fix issue with pulling the wrong A to Z page description

DIS-336 : Updates to Aspen Web Resources - QA Updates

---

code/web/services/WebBuilder/ResourceAudience.php
code/web/services/WebBuilder/ResourceCategory.php

Properly filter web resources by library on audience and category pages

DIS-336 : Updates to Aspen Web Resources - QA Updates II

---

code/reindexer/src/org/aspen_discovery/reindexer/MarcRecordProcessor.java
code/web/release_notes/25.04.00.MD
code/web/sys/SearchObject/GroupedWorkSearcher2.php

- Add author_additional to GroupedWorkSearcher2.php $fields_to_return
- Add 505t to marc fields to look at for alternate titles 
- Update Release notes

DIS-449: Enhanced 505 field for Author and Title

---

code/web/RecordDrivers/GroupedWorkDriver.php
code/web/release_notes/25.04.00.MD

https://aspen-discovery.atlassian.net/jira/software/c/projects/DIS/list?selectedIssue=DIS-544&text=endnote

DIS-544: Add Space to RIS Field

---

code/web/RecordDrivers/MarcRecordDriver.php

Add $isPeriodical variable in getMoreDetailsOptions() in MarcRecordDriver.php to fix error when checking for $marcHoldings later on in the same function (line 1745)

DIS-353: Sort Serials with the newest issue copy first in search results and in the place hold modal

---

code/web/services/MaterialsRequest/NewRequest.php
code/web/sys/SearchObject/TalpaSearcher.php

1. catch errors key in Talpa API response and report to Aspen using AspenError
2. add an isset() on $_REQUEST for `talpaOther` key in NewRequest.php to fix php warning

DIS-321 talpa clean up

---

code/web/Drivers/AbstractIlsDriver.php
code/web/Drivers/Koha.php
code/web/interface/themes/responsive/DataObjectUtil/enum.tpl
code/web/interface/themes/responsive/DataObjectUtil/property.tpl
code/web/interface/themes/responsive/MyAccount/fines.tpl
code/web/interface/themes/responsive/MyAccount/heyCentricPayments.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/release_notes/25.05.00.MD
code/web/services/API/SystemAPI.php
code/web/services/Admin/HeyCentricSettings.php
code/web/services/MyAccount/AJAX.php
code/web/services/MyAccount/Fines.php
code/web/sys/Account/User.php
code/web/sys/Account/UserPayment.php
code/web/sys/DBMaintenance/heycentric_updates.php
code/web/sys/DataObjectUtil.php
code/web/sys/ECommerce/HeyCentricSetting.php
code/web/sys/ECommerce/HeyCentricUrlParameter.php
code/web/sys/ECommerce/HeyCentricUrlParameterSetting.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/LibraryLocation/Location.php
code/web/sys/SystemVariables.php

Jira ticket at: https://aspen-discovery.atlassian.net/browse/DIS-76

DIS-76: HeyCentric integration

---

code/web/interface/themes/responsive/WebBuilder/resourcesList.tpl
code/web/release_notes/25.05.00.MD
code/web/services/WebBuilder/ResourcesList.php

Add button to default Research & Learn page for a to z web resources 

DIS-336: Updates to Aspen Web Resources

---

code/web/interface/themes/responsive/MyAccount/home.tpl
code/web/interface/themes/responsive/campaign-highlight.tpl
code/web/release_notes/25.05.00.MD
code/web/services/MyAccount/Home.php
code/web/sys/DBMaintenance/version_updates/25.05.00.php
code/web/sys/LibraryLocation/Library.php

https://aspen-discovery.atlassian.net/browse/DIS-632

Dis 632 highlight campaigns in my account

---

code/web/release_notes/25.05.00.MD
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/CommunityEngagement/CampaignMilestone.php
code/web/sys/DBMaintenance/version_updates/25.05.00.php

https://aspen-discovery.atlassian.net/browse/DIS-606

DIS-606: Milestone Order in Bento Box

---

code/web/release_notes/25.05.00.MD
code/web/services/MyAccount/AJAX.php
code/web/sys/Account/UserPayment.php
code/web/sys/DBMaintenance/version_updates/25.05.00.php
code/web/sys/ECommerce/ACISpeedpaySetting.php
code/web/sys/ECommerce/InvoiceCloudSetting.php
code/web/sys/ECommerce/NCRPaymentsSetting.php
code/web/sys/ECommerce/PayPalPayflowSetting.php
code/web/sys/ECommerce/PayPalSetting.php
code/web/sys/ECommerce/ProPaySetting.php
code/web/sys/ECommerce/SquareSetting.php
code/web/sys/ECommerce/StripeSetting.php
code/web/sys/SystemLogging/ExternalRequestLogEntry.php

Test plan :
Login as a staff user with permissions to manage ecommerce payments settings
Set your prefer ecommerce to manage your payments like Paypal, ProPay, NCR, PaypalPayflow with valid credentials
Go to Greenhouse -> External Log Entry
Login with a user who has fines to pay (use an incognito window for testing)
Pay the fines
The staff user should be able to watch debugging information about movements related with the ecommerce

DIS-416: Debugging ecommerce applications

---

code/web/RecordDrivers/MarcRecordDriver.php
code/web/release_notes/25.05.00.MD
code/web/sys/SearchObject/ListsSearcher.php

Jira ticket: https://aspen-discovery.atlassian.net/browse/DIS-645

DIS-645: newsletter consent error handling

---

code/web/RecordDrivers/MarcRecordDriver.php
code/web/release_notes/25.05.00.MD
code/web/sys/SearchObject/ListsSearcher.php

Jira ticket: https://aspen-discovery.atlassian.net/browse/DIS-644

DIS-644: reset curl connection options

---

code/web/release_notes/25.05.00.MD
code/web/services/MyAccount/MyPrivacySettings.php

Jira ticket: https://aspen-discovery.atlassian.net/browse/DIS-613

DIS-613: fix privacy settings reload

---

code/web/release_notes/25.05.00.MD
code/web/sys/CommunityEngagement/Campaign.php

https://aspen-discovery.atlassian.net/browse/DIS-696

DIS-696: Share All Rewards on Social Media

---

code/web/release_notes/25.05.00.MD
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/CommunityEngagement/CampaignMilestone.php

https://aspen-discovery.atlassian.net/browse/DIS-607

DIS-607: Display Milestones In Order

---

code/web/sys/IP/IPAddress.php

Explanation: https://aspen-discovery.atlassian.net/browse/DIS-742

DIS-742: Reverted behavior So There is No Fallback IP If Invalid IP

---

code/web/release_notes/25.05.00.MD
code/web/sys/LibraryLocation/Location.php
code/web/sys/UserLists/UserList.php

Jira ticket: https://aspen-discovery.atlassian.net/browse/DIS-681

DIS-681: fix: open archives indexing

---

code/web/release_notes/25.06.00.MD
code/web/sys/CommunityEngagement/Campaign.php

https://aspen-discovery.atlassian.net/browse/DIS-608

DIS-608: Prevent Adding Duplicate Milestones

---

code/web/sys/CommunityEngagement/Campaign.php

I had dropped these columns from the display, rechecked functionality working as it should be.

DIS-352: fix: readd enrollment dates in display

---

code/web/interface/themes/responsive/Record/renew-results.tpl
code/web/release_notes/25.05.00.MD
code/web/sys/Events/EventType.php

Jira ticket: https://aspen-discovery.atlassian.net/browse/DIS-740

DIS-740: fix: missing translate tags

---

code/web/release_notes/25.05.00.MD
code/web/sys/Theming/Theme.php

- Fixed an issue when attempting to create a new theme and an initialization error would appear.

DIS-757: Initialize Placard Image Max Height Variable

---

code/web/interface/themes/responsive/Search/home-searchbox.tpl
code/web/interface/themes/responsive/Search/horizontal-searchbox.tpl
code/web/interface/themes/responsive/css/home.less
code/web/interface/themes/responsive/css/main.css
code/web/interface/themes/responsive/js/aspen/base.js
code/web/release_notes/25.06.00.MD

- Added an 'X' button inside the search box to easily clear entered text; the button appears automatically when text is present.

DIS-778: Added Clear Search Button

---

code/web/Drivers/CarlX.php
code/web/release_notes/25.06.00.MD

Add call number to the information we take from the getPatronTransactions() API response
(resubmitted because pullbot ate the first PR :( )

DIS-781: Add Call Number in Checked Out TItles for Carl.X

---

code/web/interface/themes/responsive/DataObjectUtil/textarea.tpl
code/web/release_notes/25.06.00.MD

- Discontinued use of TinyMCE's deprecated spellchecker plugin and enabled native browser spellcheck.

DIS-588: Remove TinyMCE Deprecated Spell Checker

---

code/web/release_notes/25.05.00.MD
code/web/services/CommunityEngagement/CampaignTable.php

https://aspen-discovery.atlassian.net/browse/DIS-797

DIS-797: Fix permissions to admin page

---

code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/release_notes/25.05.00.MD

https://aspen-discovery.atlassian.net/browse/DIS-793 Fix table width displays

DIS-793: Fix Table Width Displays

---

code/web/release_notes/25.05.00.MD
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/LibraryLocation/Library.php

https://aspen-discovery.atlassian.net/browse/DIS-805 this fixes the issue noted in the comments on DIS 352

DIS-805: Display User in Leaderboard Fix

---

code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/release_notes/25.06.00.MD

https://aspen-discovery.atlassian.net/browse/DIS-822

DIS-822: Translation Mode With Aria Labels Community Engagement Fix

---

code/web/interface/themes/responsive/Admin/propertiesList.tpl
code/web/release_notes/25.06.00.MD

https://aspen-discovery.atlassian.net/browse/DIS-813

DIS-813: Correct Description For User Age

---

code/web/interface/themes/responsive/Admin/propertiesList.tpl
code/web/release_notes/25.06.00.MD

https://aspen-discovery.atlassian.net/browse/DIS-796

DIS-796: Allow Images For Physical Rewards

---

code/web/interface/themes/responsive/Admin/usage_by_ip.tpl
code/web/release_notes/25.06.00.MD
code/web/services/Admin/UsageByIP.php
code/web/services/Admin/UsageByUserAgent.php

- Added pagination to improve load times.
- Introduced a "Sort by" dropdown to sort data by any column (e.g., IP Address, Requests, Logins).
- Fixed pagination to work more efficiently at the database level.
- Reduced data load by filtering stats using only relevant user agent IDs.
Test Plan:
1. Navigate to the Usage by IP Address page in the admin interface. Notice that it loads slowly and loads all entries onto one page.
2. Navigate to the Usage by User Agent page in the admin interface. Notice that it loads slowly.
- Note: If there are millions of entries, with the number of columns being loaded, it will load slowly anyway.
3. Apply the patch and repeat steps 1-2.

DIS-818: Pagination & Sorting Improvements to Usage Pages

---

code/web/release_notes/25.06.00.MD
code/web/sys/CommunityEngagement/Reward.php
code/web/sys/DBMaintenance/version_updates/25.06.00.php

https://aspen-discovery.atlassian.net/browse/DIS-860

DIS-860: Update Award Automatically

---

code/web/interface/themes/responsive/AJAX/libraryHoursAndLocations.tpl

https://aspen-discovery.atlassian.net/browse/DIS-849?focusedCommentId=14886

DIS-849: Remove Errant Curly Brace

---

code/web/default_translatable_text_fields/Reward_description.MD
code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/interface/themes/responsive/Search/advertise-campaigns.tpl
code/web/release_notes/25.06.00.MD
code/web/services/Search/AdvertiseCampaigns.php
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/CommunityEngagement/CampaignMilestone.php

https://aspen-discovery.atlassian.net/browse/DIS-840

DIS-840: Display Descriptions

---

code/web/release_notes/25.06.00.MD
code/web/services/MaterialsRequest/ManageRequests.php
code/web/sys/Administration/StickyFilter.php
code/web/sys/DBMaintenance/version_updates/25.06.00.php

Add table for admin sticky filters
Update logic for applying/saving filters on the Manage Materials Requests admin page

DIS-801: Materials Request: Remember Assigned To and Status Filters

---

code/web/interface/themes/responsive/Admin/propertiesList.tpl
code/web/release_notes/25.06.00.MD
code/web/sys/DBMaintenance/version_updates/25.06.00.php

Ticket: https://aspen-discovery.atlassian.net/browse/DIS-814

DIS-814: koha login error messages

---

code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/release_notes/25.06.00.MD

https://aspen-discovery.atlassian.net/browse/DIS-851

DIS-851: Do Not Duplicate Campaigns

---

code/web/release_notes/25.06.01.MD
code/web/sys/CommunityEngagement/UserCampaign.php

https://aspen-discovery.atlassian.net/browse/DIS-978

DIS-978_prevent_unassigned_variable

---

code/web/interface/themes/responsive/cookie-consent.tpl
code/web/release_notes/25.07.00.MD

Test plan: http://aspen-discovery.atlassian.net/browse/DIS-957

Dis 957 cookie consent template typo

---

code/web/bootstrap.php
code/web/release_notes/25.07.00.MD
code/web/sys/DBMaintenance/version_updates/25.07.00.php
code/web/sys/SystemVariables.php

Test plan: https://aspen-discovery.atlassian.net/browse/DIS-887

Dis 887 make user agents table toggleable

---

code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/communityEngagement.js
code/web/release_notes/25.07.00.MD
code/web/services/CommunityEngagement/Milestones.php
code/web/sys/CommunityEngagement/CampaignMilestone.php
code/web/sys/CommunityEngagement/Milestone.php

https://aspen-discovery.atlassian.net/browse/DIS-826

DIS-826: list conditional field

---

code/web/interface/themes/responsive/DataObjectUtil/enum.tpl
code/web/release_notes/25.06.01.MD

- Remove extraneous } and do not show an extra enum option if the currently set value is present

DIS-846 - Code cleanup

---

code/web/Drivers/Koha.php
code/web/release_notes/25.07.00.MD

https://aspen-discovery.atlassian.net/browse/DIS-998

DIS-998 koha selfreg workflow

---

code/web/release_notes/25.07.00.MD
code/web/services/MyAccount/MyList.php
code/web/sys/UserLists/UserList.php

- Added the option to sort user lists by "Author".
Test Plan:
1. Apply the patch.
2. Navigate to a user list, click “Sort by,” and select “Author.” Notice that the list is sorted alphabetically by the author’s name.

DIS-1007: Add "Author" Sort Option for User Lists

---

code/web/release_notes/25.07.00.MD
code/web/services/MaterialsRequest/ManageRequests.php

Allow local administrators to manage material requests by loading valid assignees based on the additional locations to administer in addition to the user's home location.

DIS-1014 Allow local administrators to manage material requests

---

code/web/interface/themes/responsive/MyAccount/list.tpl
code/web/interface/themes/responsive/cssAndJsIncludes.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/account.js
code/web/interface/themes/responsive/js/aspen/base.js
code/web/interface/themes/responsive/js/aspen/globals.js
code/web/release_notes/25.07.00.MD
code/web/services/API/SystemAPI.php
code/web/services/MyAccount/AJAX.php

- Delete Selected and Delete All Titles buttons have been moved to the top of the screen and merged into a dropdown with the Delete List button.
- Added a new Select All / Deselect All button
- Made messages to confirm operations translatable and made the confirm button a danger button so it shows in red.
- Allow retrieving translations from SystemAPI without additional IP checks to enable translations within JavaScript.
- Allow getBulkTranslations to return translation of terms within get parameters in addition to JSON encoded body.
- Show spinner while adding bulk titles to a list.

DIS-1021 Improve deleting titles from lists as well as deleting entire lists

---

code/web/release_notes/25.07.00.MD
code/web/sys/CommunityEngagement/action-hooks.php

https://aspen-discovery.atlassian.net/browse/DIS-1032

DIS-1032: Refactor Campaign Date Check

---

code/web/sys/DBMaintenance/version_updates/25.07.00.php

Use correct paths on non-windows systems when renaming files and add safety check that the file was actually renamed before updating the database.

DIS-657 Prevent File Overwrite

---

code/web/release_notes/25.07.00.MD
code/web/sys/LibraryLocation/Location.php

- Optimize loading certain location information so it is only loaded once rather than reloading the data repetitively within a page load

DIS-1037 Location Performance Improvements

---

code/web/release_notes/25.07.00.MD
code/web/services/CommunityEngagement/AJAX.php

https://aspen-discovery.atlassian.net/browse/DIS-1049

DIS-1049: FIX - campaign complete email always sends when manual progress added

---

code/web/services/Admin/HeyCentricSettings.php
code/web/sys/Account/User.php

https://aspen-discovery.atlassian.net/browse/DIS-1069

DIS-1069: FIX: restore heycentric admin menu link

---

code/web/interface/themes/responsive/MyAccount/myPreferences.tpl
code/web/interface/themes/responsive/css/account.less
code/web/interface/themes/responsive/css/main.css
code/web/interface/themes/responsive/theme.css.tpl
code/web/release_notes/25.07.00.MD
code/web/sys/SearchObject/EventsSearcher.php
code/web/sys/Theming/Theme.php
code/web/version.json

- Combine all search preferences into a single section
- Correct theming of preference panels
- Expand all preferences by default
- Remove System Default from search dropdowns
- Change order of sort options for events so Best Match (default) is first
- Correct scope of library and locations properties within Theme

DIS-1025 Minor updates

---

code/web/cron/runScheduledUpdate.php
code/web/release_notes/25.07.00.MD
code/web/services/API/SystemAPI.php
code/web/services/Admin/DBMaintenance.php
code/web/sys/Covers/BookCoverInfo.php
code/web/sys/Theming/Theme.php

- Also improve the speed of updates

DIS-1094 Update Themes during scheduled updates

---

code/reindexer/src/org/aspen_discovery/format_classification/MarcRecordFormatClassifier.java
code/reindexer/src/org/aspen_discovery/reindexer/SideLoadedEContentProcessor.java
code/web/release_notes/25.07.01.MD

- Only apply 300$a "online_resource" format consideration for ILS records.

DIS-1015: Only Apply `online_resource` Format Consideration for ILS Records

---

code/web/RecordDrivers/GroupedWorkDriver.php
code/web/interface/themes/responsive/GroupedWork/relatedManifestations.tpl
code/web/interface/themes/responsive/GroupedWork/whileYouWait.tpl
code/web/interface/themes/responsive/GroupedWork/youMightAlsoLike.tpl
code/web/interface/themes/responsive/MyAccount/ilsCheckedOutTitle.tpl
code/web/interface/themes/responsive/MyAccount/ilsHold.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/grouped-work.js
code/web/release_notes/25.08.00.MD
code/web/robots.txt
code/web/services/GroupedWork/AJAX.php
code/web/services/GroupedWork/Home.php
code/web/sys/DBMaintenance/version_updates/25.08.00.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
code/web/sys/SolrConnector/GroupedWorksSolrConnector2.php

- Add scoping options for While You Wait and You Might Also Like to limit by owning library and format
- Add new parameters to the getWhileYouWait and getYouMightAlsoLike functions to pass format and search source
- Add /GroupedWork/*/Home?* to robots.txt to prevent crawling pages with the new activeFormat and activeSearchSource URL parameters
- Update release notes

DIS-995: While You Wait and You Might Also Like Improvements

---

code/web/interface/themes/responsive/CommunityEngagement/adminView.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/communityEngagement.js
code/web/release_notes/25.08.00.MD
code/web/services/CommunityEngagement/AJAX.php
code/web/services/CommunityEngagement/AdminView.php
code/web/services/MyAccount/AJAX.php
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/DBMaintenance/version_updates/25.08.00.php
code/web/sys/LibraryLocation/Library.php

https://aspen-discovery.atlassian.net/browse/DIS-470

DIS-470: Rebased Allow Admin to Enroll

---

code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/interface/themes/responsive/campaign-highlight.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/admin.js
code/web/release_notes/25.08.00.MD
code/web/services/Admin/Libraries.php
code/web/services/MyAccount/Home.php
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/DBMaintenance/version_updates/25.08.00.php
code/web/sys/LibraryLocation/Library.php

https://aspen-discovery.atlassian.net/browse/DIS-1126

DIS- 1126: Add Ability to Highlight Campaigns Open to Enroll

---

code/web/release_notes/25.08.00.MD
code/web/services/CommunityEngagement/AJAX.php

https://aspen-discovery.atlassian.net/browse/DIS-1144

DIS-1144: Display Progress Data Title In Staff View

---

code/web/cron/talpaRecalculationCron.php
code/web/cron/talpaWorksCron.php
code/web/release_notes/25.08.00.MD

- Talpa Works Crons no longer use the `global $library `variable, but instead rely on any `talpaSettings` found for the library system (bug fix)
- Updated API Endpoint and response handling.

DIS 1195: Updates to Talpa Works Crons

---

code/web/cron/createDefaultDatabaseScript.php
code/web/release_notes/25.08.00.MD

- update script to create default database to automatically disable foreign key checks during load

DIS-1198 - Fix foreign key constraints during site creation

---

code/koha_export/src/com/turning_leaf_technologies/koha_export/KohaExportMain.java
code/web/release_notes/25.08.00.MD

- Fixed an issue where new Locations could not be imported from Koha to Aspen.

DIS-1137: Fixed Failure to Import Locations from Koha

---

code/web/RecordDrivers/GroupedWorkDriver.php
code/web/interface/themes/responsive/GroupedWork/youMightAlsoLike.tpl
code/web/services/GroupedWork/AJAX.php
code/web/sys/LibraryLocation/Library.php
code/web/sys/SearchObject/AbstractGroupedWorkSearcher.php
code/web/sys/SolrConnector/GroupedWorksSolrConnector.php
code/web/sys/SolrConnector/GroupedWorksSolrConnector2.php

- Check if active format is not set when showing you might also like
- Add scope when showing you might also like and while you wait
- Add Yes, include materials in global scope in the same format only. as an option for You Might Also Like
- Clarify labels -

DIS-995 Updates

---

code/web/RecordDrivers/GroupedWorkDriver.php
code/web/interface/themes/responsive/RecordDrivers/GroupedWork/seriesEntry.tpl
code/web/release_notes/25.09.00.MD
code/web/sys/Series/Series.php

- When the same title appears multiple times in a series, but has different volume numbers, each entry on the Series page should show the correct volume.

DIS-1281: Display correct volume on Series page

---

code/web/interface/themes/responsive/MyAccount/myCampaigns.tpl
code/web/interface/themes/responsive/Search/advertise-campaigns.tpl
code/web/interface/themes/responsive/js/aspen.js
code/web/interface/themes/responsive/js/aspen/communityEngagement.js
code/web/release_notes/25.09.00.MD
code/web/services/CommunityEngagement/AJAX.php
code/web/services/GroupedWork/AJAX.php
code/web/services/MyAccount/AJAX.php
code/web/services/Search/AdvertiseCampaigns.php
code/web/sys/CommunityEngagement/Campaign.php
code/web/sys/CommunityEngagement/CampaignExtraCredit.php
code/web/sys/DBMaintenance/version_updates/25.09.00.php
code/web/sys/LocalEnrichment/UserWorkReview.php

https://aspen-discovery.atlassian.net/browse/DIS-1263

DIS-1263:  Minor Community Engagement Enhancements

---

code/web/sys/Account/User.php

DIS-1275: Display Messages after Self Check small fix

---

code/web/services/API/UserAPI.php

https://aspen-discovery.atlassian.net/browse/DIS-646

DIS-646: FIX: pass ispast and isupcoming to api

---

code/web/services/API/EventAPI.php
code/web/services/API/SearchAPI.php

- Prepend site URL to native event cover URL
- Add native events as a valid event source to save via API
- Add null coalescing to URL on event search results to prevent error if URL is not set

DIS-1262: QA Fixes

---

code/web/release_notes/25.09.00.MD
code/web/sys/DBMaintenance/version_updates/25.09.00.php
code/web/sys/Hoopla/HooplaExtract.php

- correct loading hoopla records
- remove unused islandora permissions

DIS-1288, DIS-1251

---

code/web/interface/themes/responsive/GroupedWork/allManifestations.tpl
code/web/interface/themes/responsive/GroupedWork/horizDisplayEdition.tpl
code/web/interface/themes/responsive/GroupedWork/work-details.tpl
code/web/interface/themes/responsive/RecordDrivers/GroupedWork/listEntry.tpl
code/web/interface/themes/responsive/RecordDrivers/GroupedWork/seriesEntry.tpl
code/web/interface/themes/responsive/RecordDrivers/Talpa/result.tpl
code/web/interface/themes/responsive/Series/seriesMembers.tpl
code/web/interface/themes/responsive/css/grouped_work.less
code/web/interface/themes/responsive/css/main.css
code/web/services/GroupedWork/AJAX.php
code/web/services/MyAccount/MyList.php
code/web/services/Series/Home.php
code/web/services/Talpa/Results.php

- Show new format in series page
- Show new format in lists page
- Show new format in popup for a grouped work from Browse Category
- Show new format for Talpa results
- Show message if no copies are owned
- Remove eContent source since it's redundant with other information

DIS-1251 - New format display updates

---

code/web/release_notes/25.10.00.MD
code/web/version.json

Update version
Merge release notes

25.10 release tasks

---

code/web/release_notes/25.10.00.MD
code/web/sys/CommunityEngagement/Campaign.php

https://aspen-discovery.atlassian.net/browse/DIS-1425

DIS-1425: Fix upcoming campaign display
